$axure.loadCurrentPage({
  "url":"home__.html",
  "generationDate":new Date(1406213757415.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79e1f630f2894257b84a5da90f604a1e",
    "type":"Axure:Page",
    "name":"Home展开",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Verdana",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"592d3f01d5874b09a8843f0fb8f6422d",
          "label":"左右滑动",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":52},
            "size":{
              "width":1177,
              "height":632}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0bff2eaee2d94f408247d2b5df41b365",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"63448bb8b7324e26b40d583923feab47",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":376,
                      "y":-23},
                    "size":{
                      "width":412,
                      "height":655},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94c6e64793c84237afea5983c701a17e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":376,
                          "y":-23},
                        "size":{
                          "width":412,
                          "height":655},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home__/u1.gif"}},
{
                  "id":"9b2a8cb707dc46628fdc6d5887a4bce3",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":-14,
                      "y":-23},
                    "size":{
                      "width":394,
                      "height":656},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50139cd970ad417f8e6e2384ee139ae1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":-14,
                          "y":-23},
                        "size":{
                          "width":394,
                          "height":656},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home__/u3.png"}},
{
                  "id":"6fda682d72c8413489fe3a4006c02de1",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":787,
                      "y":-23},
                    "size":{
                      "width":393,
                      "height":655},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fed31c4fada4b6f9623cfdfe5202339",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":787,
                          "y":-23},
                        "size":{
                          "width":393,
                          "height":655},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"d624ce4bc05743afa8c9ad72b393131e",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":585},
                    "size":{
                      "width":62,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d516559262a7458a9f9b9f0076b9f87a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":585},
                        "size":{
                          "width":62,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move 左右滑动 by (-393,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["592d3f01d5874b09a8843f0fb8f6422d"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-393",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cd7d371586024714bc9b1c56fcbd7655",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1131,
                      "y":585},
                    "size":{
                      "width":49,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"145c66f854bc4f00a104f84c0ee25f77",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1131,
                          "y":585},
                        "size":{
                          "width":49,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Toggle more diandian",
                              "objectsToFades":[{
                                  "objectPath":["75b27ce4b0464b29b1f771ce25a23738"],
                                  "fadeInfo":{
                                    "fadeType":"toggle",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2029644eb22f44e0886f6af09e72aedf",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":11,
                      "y":91},
                    "size":{
                      "width":100,
                      "height":133},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b4a260283ea4325a70983af5c683e4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":11,
                          "y":91},
                        "size":{
                          "width":100,
                          "height":133},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open My profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"my_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d55bf63b47354026ba808df47a9b55c9",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":788,
                      "y":585},
                    "size":{
                      "width":66,
                      "height":49},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91504ea854a04fceb2cfb0a2a10cfe8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":788,
                          "y":585},
                        "size":{
                          "width":66,
                          "height":49},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move 左右滑动 by (393,0) linear 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["592d3f01d5874b09a8843f0fb8f6422d"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"393",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"75b27ce4b0464b29b1f771ce25a23738",
                  "label":"more diandian",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":1061,
                      "y":459},
                    "size":{
                      "width":117,
                      "height":125},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"54fbbe5eac6043ad80cfde18a0b09c52",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ab0807a4dfd54be1996a380fd644843c",
                          "label":"",
                          "parentDynamicPanel":"75b27ce4b0464b29b1f771ce25a23738",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontName":"'Verdana Normal', 'Verdana'",
                            "fontWeight":"400",
                            "fontStyle":"normal",
                            "size":{
                              "width":123,
                              "height":132},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"23167325bc984247a36a6b3abb38ff35",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"75b27ce4b0464b29b1f771ce25a23738",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Verdana Normal', 'Verdana'",
                                "fontWeight":"400",
                                "fontStyle":"normal",
                                "size":{
                                  "width":123,
                                  "height":132},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u18.png"}}]}]},
{
                  "id":"cb35c42f43144eedaa6750ef2067bcf5",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":439,
                      "y":28},
                    "size":{
                      "width":115,
                      "height":110},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28f55fa8b25d458bacceb57272680257",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":439,
                          "y":28},
                        "size":{
                          "width":115,
                          "height":110},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open message+ in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"message_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4465c5c7c3424e48a745bb780b29ce5f",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":637,
                      "y":29},
                    "size":{
                      "width":115,
                      "height":110},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2dc1ccf1f5e4a5589de9f45899304d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":637,
                          "y":29},
                        "size":{
                          "width":115,
                          "height":110},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open call+ in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"call_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2b5fcc65589644e3b27ff0ce6ab37501",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":637,
                      "y":158},
                    "size":{
                      "width":115,
                      "height":110},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3b3d505b4f447aa832140d65e2eb137",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":637,
                          "y":158},
                        "size":{
                          "width":115,
                          "height":110},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open key board+ in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"key_board_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6f1c0966720486a9ffa24c7762630a0",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":447,
                      "y":158},
                    "size":{
                      "width":104,
                      "height":110},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"813a63590e254e9f855fc24e76cbfdfd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":447,
                          "y":158},
                        "size":{
                          "width":104,
                          "height":110},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open video+ in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"video_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d8db2cba42144fb6ae661c1089869d66",
                  "label":"",
                  "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":752,
                      "y":255},
                    "size":{
                      "width":34,
                      "height":39},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1d253fb301241aaa3fad1f498413db1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"592d3f01d5874b09a8843f0fb8f6422d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":752,
                          "y":255},
                        "size":{
                          "width":34,
                          "height":39},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home关闭 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home___1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"4a0ab713df7141c39bd0fdd609bf5f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":-178,
              "y":29},
            "size":{
              "width":625,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec5d250b993a497f87b87d5a4098e8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":-178,
                  "y":29},
                "size":{
                  "width":625,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"fa7f7cfc19614330bf166866a842a901",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":842,
              "y":50},
            "size":{
              "width":766,
              "height":665},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4360137a0ddf48b89122573525af74aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":842,
                  "y":50},
                "size":{
                  "width":766,
                  "height":665},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"143d8fabda1a4bc8a5d46962d7bfd937",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":448,
              "y":29},
            "size":{
              "width":394,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdbecd8affe44702bea9fdd65efe6180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":448,
                  "y":29},
                "size":{
                  "width":394,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u46.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "592d3f01d5874b09a8843f0fb8f6422d":{
      "scriptId":"u0"},
    "63448bb8b7324e26b40d583923feab47":{
      "scriptId":"u1"},
    "94c6e64793c84237afea5983c701a17e":{
      "scriptId":"u2"},
    "9b2a8cb707dc46628fdc6d5887a4bce3":{
      "scriptId":"u3"},
    "50139cd970ad417f8e6e2384ee139ae1":{
      "scriptId":"u4"},
    "6fda682d72c8413489fe3a4006c02de1":{
      "scriptId":"u5"},
    "6fed31c4fada4b6f9623cfdfe5202339":{
      "scriptId":"u6"},
    "d624ce4bc05743afa8c9ad72b393131e":{
      "scriptId":"u7"},
    "d516559262a7458a9f9b9f0076b9f87a":{
      "scriptId":"u8"},
    "cd7d371586024714bc9b1c56fcbd7655":{
      "scriptId":"u9"},
    "145c66f854bc4f00a104f84c0ee25f77":{
      "scriptId":"u10"},
    "2029644eb22f44e0886f6af09e72aedf":{
      "scriptId":"u11"},
    "2b4a260283ea4325a70983af5c683e4f":{
      "scriptId":"u12"},
    "d55bf63b47354026ba808df47a9b55c9":{
      "scriptId":"u13"},
    "91504ea854a04fceb2cfb0a2a10cfe8c":{
      "scriptId":"u14"},
    "75b27ce4b0464b29b1f771ce25a23738":{
      "scriptId":"u15"},
    "ab0807a4dfd54be1996a380fd644843c":{
      "scriptId":"u16"},
    "23167325bc984247a36a6b3abb38ff35":{
      "scriptId":"u17"},
    "cb35c42f43144eedaa6750ef2067bcf5":{
      "scriptId":"u18"},
    "28f55fa8b25d458bacceb57272680257":{
      "scriptId":"u19"},
    "4465c5c7c3424e48a745bb780b29ce5f":{
      "scriptId":"u20"},
    "f2dc1ccf1f5e4a5589de9f45899304d1":{
      "scriptId":"u21"},
    "2b5fcc65589644e3b27ff0ce6ab37501":{
      "scriptId":"u22"},
    "f3b3d505b4f447aa832140d65e2eb137":{
      "scriptId":"u23"},
    "e6f1c0966720486a9ffa24c7762630a0":{
      "scriptId":"u24"},
    "813a63590e254e9f855fc24e76cbfdfd":{
      "scriptId":"u25"},
    "d8db2cba42144fb6ae661c1089869d66":{
      "scriptId":"u26"},
    "e1d253fb301241aaa3fad1f498413db1":{
      "scriptId":"u27"},
    "4a0ab713df7141c39bd0fdd609bf5f1c":{
      "scriptId":"u28"},
    "ec5d250b993a497f87b87d5a4098e8ff":{
      "scriptId":"u29"},
    "fa7f7cfc19614330bf166866a842a901":{
      "scriptId":"u30"},
    "4360137a0ddf48b89122573525af74aa":{
      "scriptId":"u31"},
    "143d8fabda1a4bc8a5d46962d7bfd937":{
      "scriptId":"u32"},
    "fdbecd8affe44702bea9fdd65efe6180":{
      "scriptId":"u33"}}});