$axure.loadCurrentPage({
  "url":"流程图.html",
  "generationDate":new Date(1403437198555.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31a4bdd67fd24a2090e301938536d648",
    "type":"Axure:Page",
    "name":"流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d54b962fb7cc4718ba1468600a77ba4f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":154,
              "y":90},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7a5e230c8f492ca1101d4b8c0f43df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":154,
                  "y":90},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"fee85cf397b4417881379abc64eece56",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":154,
              "y":195},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e604e5d8b0b4f6b84b9e93e6f9cefa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":154,
                  "y":195},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"59d220a3ac77481b9a5732b873e6fabb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":154,
              "y":343},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686bd904d2a64f3381b58aadd2746878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":154,
                  "y":343},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"200bd14711924ca0b6f4f936b849129a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":389,
              "y":343},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc3a0ae1105402d96783d6308d9343c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":389,
                  "y":343},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"c1db36b48fbb4fd7968faab3b94fb452",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":594,
              "y":343},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e89993e9a24238831e5a044f051ba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":594,
                  "y":343},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"86aa0653e8f348a3b607a941ec399729",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7321c9e64c4cc3bc7369583a6e88aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"1a3ff451fd3849479089fb2d214908ec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":389,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b2f935350304f458c269c63abdad550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":389,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"df91a835795e4fd9864623bd3aa8d54c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":153},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24fa17d57e364965ae4ad97279fbd3c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":153},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"e248706289444d0db951a2bfbcba2808",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":255},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77a2e658dc2949969263fb1402c9b954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":255},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"560948e7103443fa951a36962d6c1770",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":255},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3459c95254984d7ba0107861d49ac352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":255},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"3db152407c4b4411adef9943e3f10867",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":255},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd07daa0e8194fac93f059d89ebea090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":255},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"84347996478742c5b49715f63323d003",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":439,
              "y":403},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc42c236a9784c57b6d11b32d2aef9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":439,
                  "y":403},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"5e11b111e5a44ff1b18f6a55f6667bf5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":238,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e8765b0f8b4a1e8282fe27d4789ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":238,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"224f7664ad5c4c3db507649b54f82842",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":71,
              "y":692},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbceb8eb23e742aebf29447157977f90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":71,
                  "y":692},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"5b5a0deb6cdd49f7bcc9ed95616d8585",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":244,
              "y":692},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d71720c6ae4dbeab2d4a8fb5b132cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":244,
                  "y":692},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"392edeb7c6dd43f4ace59ae94f1a61c2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":422,
              "y":692},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b4ebc5dc5984dd9816f285ba86da400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":422,
                  "y":692},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"ac1f4c1679ba4e849b7d8e82730e8ec4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":403},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"083dfdf5fd4d442296cf0ae7a94ecf9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":403},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"c2597c712c6847849aa0af09a3bbf962",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":121,
              "y":752},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d01bdd328c4e25a91abf1f6822d89e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":121,
                  "y":752},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"7dd2d0c1edc5467693877fd6bdc4e6e1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":171,
              "y":722},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b9236c338e44629db0f9e59cec5245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":171,
                  "y":722},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"b973d01ed588482cb4dda0309ff7501a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":294,
              "y":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca9e2f8e77e48c8b12fb1ad2bf77e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":294,
                  "y":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"90a489aaedea41ee8db44a9c0243479e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":338,
              "y":720},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5b2cc4bf3e4540b752f9714174babd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":338,
                  "y":720},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"85609d3dca324172a4e73fb4f71453c6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":71,
              "y":820},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d99806ed97f4319ae0fb3c1ce438652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":71,
                  "y":820},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"140ba49dfeb34e23841fefe9d2088911",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":244,
              "y":820},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f41517503f5e4eaa984ecf02c30f8f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":244,
                  "y":820},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}},
{
          "id":"af271b559cfe445b942c79399b535993",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":549,
              "y":480},
            "size":{
              "width":190,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13412e5a479d4a59ba67c14c7c51e675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":549,
                  "y":480},
                "size":{
                  "width":190,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u46.png"}},
{
          "id":"f99359a906bb4d25aa0f58ff383653f5",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":644,
              "y":403},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7c90438c62421b927c3da0338ba1fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":644,
                  "y":403},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"ea1cc812cd2647eb9e8f621010af5d69",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":29,
              "y":20},
            "size":{
              "width":195,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28ce8fd84c7c4f34b15858820ab42699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":29,
                  "y":20},
                "size":{
                  "width":195,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0641354b12b9440391576b37cd4d9600",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":204,
              "y":403},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bf50a00a6de48c7b196c1d3ce1ffc55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":403},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"9615af152bfe4123aa3549617d966815",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":238,
              "y":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a5b4487e7ba436b8fdda8711dac3ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":238,
                  "y":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"027bcc7b074849b399ce5eca3aadf81a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5e702c558d422590c1615da98d59c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"6a3c218ecfa84c81a16f9a3d93d45236",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b57a9a8be0840d7b6a2ce5bae4f5fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fd21994bbe14512af2a7222eaccb348",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"428907cf76ab4e33868c16bbe41cdad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"1c8353617f914765851ecf2fc1f52ab7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":644,
              "y":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83321405f2c64b16b1c9c4ba5eabe8b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":644,
                  "y":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"40dcde5765a4446db8ea3da58221df04",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":373},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1bf265770bb4aed8242aae932171b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":373},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"28ddc842fe204b5fb0b18f9aff65ce34",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":376},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4db247c24b64ce69a6ac888079840c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":376},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"881db434a8eb443db01c7dc89b63c38a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":373},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c094b3b75a245858494282ddcc60b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":373},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "d54b962fb7cc4718ba1468600a77ba4f":{
      "scriptId":"u0"},
    "9f7a5e230c8f492ca1101d4b8c0f43df":{
      "scriptId":"u1"},
    "fee85cf397b4417881379abc64eece56":{
      "scriptId":"u2"},
    "4e604e5d8b0b4f6b84b9e93e6f9cefa3":{
      "scriptId":"u3"},
    "59d220a3ac77481b9a5732b873e6fabb":{
      "scriptId":"u4"},
    "686bd904d2a64f3381b58aadd2746878":{
      "scriptId":"u5"},
    "200bd14711924ca0b6f4f936b849129a":{
      "scriptId":"u6"},
    "9dc3a0ae1105402d96783d6308d9343c":{
      "scriptId":"u7"},
    "c1db36b48fbb4fd7968faab3b94fb452":{
      "scriptId":"u8"},
    "d1e89993e9a24238831e5a044f051ba7":{
      "scriptId":"u9"},
    "86aa0653e8f348a3b607a941ec399729":{
      "scriptId":"u10"},
    "3a7321c9e64c4cc3bc7369583a6e88aa":{
      "scriptId":"u11"},
    "1a3ff451fd3849479089fb2d214908ec":{
      "scriptId":"u12"},
    "9b2f935350304f458c269c63abdad550":{
      "scriptId":"u13"},
    "df91a835795e4fd9864623bd3aa8d54c":{
      "scriptId":"u14"},
    "24fa17d57e364965ae4ad97279fbd3c4":{
      "scriptId":"u15"},
    "e248706289444d0db951a2bfbcba2808":{
      "scriptId":"u16"},
    "77a2e658dc2949969263fb1402c9b954":{
      "scriptId":"u17"},
    "560948e7103443fa951a36962d6c1770":{
      "scriptId":"u18"},
    "3459c95254984d7ba0107861d49ac352":{
      "scriptId":"u19"},
    "3db152407c4b4411adef9943e3f10867":{
      "scriptId":"u20"},
    "fd07daa0e8194fac93f059d89ebea090":{
      "scriptId":"u21"},
    "84347996478742c5b49715f63323d003":{
      "scriptId":"u22"},
    "fc42c236a9784c57b6d11b32d2aef9d2":{
      "scriptId":"u23"},
    "5e11b111e5a44ff1b18f6a55f6667bf5":{
      "scriptId":"u24"},
    "16e8765b0f8b4a1e8282fe27d4789ef6":{
      "scriptId":"u25"},
    "224f7664ad5c4c3db507649b54f82842":{
      "scriptId":"u26"},
    "cbceb8eb23e742aebf29447157977f90":{
      "scriptId":"u27"},
    "5b5a0deb6cdd49f7bcc9ed95616d8585":{
      "scriptId":"u28"},
    "29d71720c6ae4dbeab2d4a8fb5b132cd":{
      "scriptId":"u29"},
    "392edeb7c6dd43f4ace59ae94f1a61c2":{
      "scriptId":"u30"},
    "0b4ebc5dc5984dd9816f285ba86da400":{
      "scriptId":"u31"},
    "ac1f4c1679ba4e849b7d8e82730e8ec4":{
      "scriptId":"u32"},
    "083dfdf5fd4d442296cf0ae7a94ecf9d":{
      "scriptId":"u33"},
    "c2597c712c6847849aa0af09a3bbf962":{
      "scriptId":"u34"},
    "50d01bdd328c4e25a91abf1f6822d89e":{
      "scriptId":"u35"},
    "7dd2d0c1edc5467693877fd6bdc4e6e1":{
      "scriptId":"u36"},
    "19b9236c338e44629db0f9e59cec5245":{
      "scriptId":"u37"},
    "b973d01ed588482cb4dda0309ff7501a":{
      "scriptId":"u38"},
    "cca9e2f8e77e48c8b12fb1ad2bf77e68":{
      "scriptId":"u39"},
    "90a489aaedea41ee8db44a9c0243479e":{
      "scriptId":"u40"},
    "3e5b2cc4bf3e4540b752f9714174babd":{
      "scriptId":"u41"},
    "85609d3dca324172a4e73fb4f71453c6":{
      "scriptId":"u42"},
    "0d99806ed97f4319ae0fb3c1ce438652":{
      "scriptId":"u43"},
    "140ba49dfeb34e23841fefe9d2088911":{
      "scriptId":"u44"},
    "f41517503f5e4eaa984ecf02c30f8f1b":{
      "scriptId":"u45"},
    "af271b559cfe445b942c79399b535993":{
      "scriptId":"u46"},
    "13412e5a479d4a59ba67c14c7c51e675":{
      "scriptId":"u47"},
    "f99359a906bb4d25aa0f58ff383653f5":{
      "scriptId":"u48"},
    "3d7c90438c62421b927c3da0338ba1fd":{
      "scriptId":"u49"},
    "ea1cc812cd2647eb9e8f621010af5d69":{
      "scriptId":"u50"},
    "28ce8fd84c7c4f34b15858820ab42699":{
      "scriptId":"u51"},
    "0641354b12b9440391576b37cd4d9600":{
      "scriptId":"u52"},
    "4bf50a00a6de48c7b196c1d3ce1ffc55":{
      "scriptId":"u53"},
    "9615af152bfe4123aa3549617d966815":{
      "scriptId":"u54"},
    "4a5b4487e7ba436b8fdda8711dac3ff4":{
      "scriptId":"u55"},
    "027bcc7b074849b399ce5eca3aadf81a":{
      "scriptId":"u56"},
    "be5e702c558d422590c1615da98d59c0":{
      "scriptId":"u57"},
    "6a3c218ecfa84c81a16f9a3d93d45236":{
      "scriptId":"u58"},
    "3b57a9a8be0840d7b6a2ce5bae4f5fbe":{
      "scriptId":"u59"},
    "0fd21994bbe14512af2a7222eaccb348":{
      "scriptId":"u60"},
    "428907cf76ab4e33868c16bbe41cdad5":{
      "scriptId":"u61"},
    "1c8353617f914765851ecf2fc1f52ab7":{
      "scriptId":"u62"},
    "83321405f2c64b16b1c9c4ba5eabe8b8":{
      "scriptId":"u63"},
    "40dcde5765a4446db8ea3da58221df04":{
      "scriptId":"u64"},
    "a1bf265770bb4aed8242aae932171b0f":{
      "scriptId":"u65"},
    "28ddc842fe204b5fb0b18f9aff65ce34":{
      "scriptId":"u66"},
    "c4db247c24b64ce69a6ac888079840c2":{
      "scriptId":"u67"},
    "881db434a8eb443db01c7dc89b63c38a":{
      "scriptId":"u68"},
    "9c094b3b75a245858494282ddcc60b61":{
      "scriptId":"u69"}}});