$axure.loadCurrentPage({
  "url":"home___1.html",
  "generationDate":new Date(1406213757892.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"57ce20842c3c423088c5c13b304b9781",
    "type":"Axure:Page",
    "name":"Home关闭",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Verdana",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"05f1a06bdc3f46b8bbb5882ee3b45888",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":29},
            "size":{
              "width":1172,
              "height":655}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7caafb5ace4c44f695a7aae370148135",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7d0f01efdca04da4b83b3ae4bddece66",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":-3,
                      "y":0},
                    "size":{
                      "width":393,
                      "height":655},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ae180b686dc417bbe82266006b601f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":-3,
                          "y":0},
                        "size":{
                          "width":393,
                          "height":655},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u1.jpg"}},
{
                  "id":"92bc12339f2b43ba8c52a4d405c94c0b",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":390,
                      "y":9},
                    "size":{
                      "width":394,
                      "height":629},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f9677b08565c4473b3efc18fd94714e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":390,
                          "y":9},
                        "size":{
                          "width":394,
                          "height":629},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home___1/u3.gif"}},
{
                  "id":"20a04c8aa9b747fc9e4f6194cfa204cf",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":784,
                      "y":30},
                    "size":{
                      "width":388,
                      "height":625},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cdf42f8c8c14ec58de03e8a2d3b1371",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":784,
                          "y":30},
                        "size":{
                          "width":388,
                          "height":625},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home___1/u5.png"}},
{
                  "id":"30647660cf1c4d4fb511703365e6d742",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":611},
                    "size":{
                      "width":61,
                      "height":44},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"036465d90dc04d1095197aa849ddeb02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":611},
                        "size":{
                          "width":61,
                          "height":44},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move (Dynamic Panel) by (-395,0) linear 400ms",
                              "objectsToMoves":[{
                                  "objectPath":["05f1a06bdc3f46b8bbb5882ee3b45888"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-395",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":400}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fbf6c6e158b442f7aecef36df17d76eb",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":1123,
                      "y":607},
                    "size":{
                      "width":48,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e529a2f9e397451abc40f751a3c82954",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":1123,
                          "y":607},
                        "size":{
                          "width":48,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Toggle more diandian",
                              "objectsToFades":[{
                                  "objectPath":["2cec4ca792244a3fb6d99aebc8ad9f74"],
                                  "fadeInfo":{
                                    "fadeType":"toggle",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"95e81d10e50b48819a34224bf04a8e1a",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":12,
                      "y":114},
                    "size":{
                      "width":358,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae0cc156c4034a8cbe7fd231e4e07057",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":12,
                          "y":114},
                        "size":{
                          "width":358,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open My profile in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"my_profile.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"69d660447b794bb7bd20ff5af06dad79",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":790,
                      "y":609},
                    "size":{
                      "width":52,
                      "height":44},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95e895e297db4ad19152cf2c6d4e6551",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":790,
                          "y":609},
                        "size":{
                          "width":52,
                          "height":44},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move (Dynamic Panel) by (393,0) linear 400ms",
                              "objectsToMoves":[{
                                  "objectPath":["05f1a06bdc3f46b8bbb5882ee3b45888"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"393",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":400}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2cec4ca792244a3fb6d99aebc8ad9f74",
                  "label":"more diandian",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":1048,
                      "y":478},
                    "size":{
                      "width":119,
                      "height":127},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a80436ea67794ff989d05768ce3dd6e2",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"5a2d95c3147c4041b9f6b10905484336",
                          "label":"",
                          "parentDynamicPanel":"2cec4ca792244a3fb6d99aebc8ad9f74",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontName":"'Verdana Normal', 'Verdana'",
                            "fontWeight":"400",
                            "fontStyle":"normal",
                            "size":{
                              "width":123,
                              "height":132},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"15c899577df24cb18edf3baf11e1f740",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2cec4ca792244a3fb6d99aebc8ad9f74",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Verdana Normal', 'Verdana'",
                                "fontWeight":"400",
                                "fontStyle":"normal",
                                "size":{
                                  "width":123,
                                  "height":132},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u18.png"}}]}]},
{
                  "id":"51d6c108c95248c7b8b5c5ea61c656d7",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":744,
                      "y":31},
                    "size":{
                      "width":40,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7de0e65667174658a73b8e393acd99da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":744,
                          "y":31},
                        "size":{
                          "width":40,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home展开 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home__.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e6c177ea2844368b1d0e31054f3792d",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":784,
                      "y":0},
                    "size":{
                      "width":388,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c84b51d7d444ba2989347e6637ee81e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":784,
                          "y":0},
                        "size":{
                          "width":388,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u46.png"}},
{
                  "id":"128ee66f85304500b836ffad8237150f",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":1,
                      "y":0},
                    "size":{
                      "width":389,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c57eab4d9eed4ef6a2670d21b9c7ef8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":1,
                          "y":0},
                        "size":{
                          "width":389,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u46.png"}},
{
                  "id":"170a9a987a844db6be3c477752d77e2e",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":390,
                      "y":-3},
                    "size":{
                      "width":394,
                      "height":31},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d52d3163a6784cc1bd2d0bc8c7936c2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":390,
                          "y":-3},
                        "size":{
                          "width":394,
                          "height":31},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u46.png"}},
{
                  "id":"a49cfab4134d41eaa7fdec9447d467cb",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":739,
                      "y":300},
                    "size":{
                      "width":43,
                      "height":59},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d0e44c2aa2b43e490167d144867db4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":739,
                          "y":300},
                        "size":{
                          "width":43,
                          "height":59},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move (Dynamic Panel) by (-394,0) linear 400ms",
                              "objectsToMoves":[{
                                  "objectPath":["05f1a06bdc3f46b8bbb5882ee3b45888"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-394",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":400}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6dce3335f4524a8d9a42750b7889c348",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":395,
                      "y":300},
                    "size":{
                      "width":44,
                      "height":64},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9bb148e15e52401ebdd61411e4ff823f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":395,
                          "y":300},
                        "size":{
                          "width":44,
                          "height":64},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move (Dynamic Panel) to (452,28) linear 400ms",
                              "objectsToMoves":[{
                                  "objectPath":["05f1a06bdc3f46b8bbb5882ee3b45888"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"452",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"28",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":400}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"914da7858b644e298a30cab979a13e37",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF3F3F3},
                    "location":{
                      "x":390,
                      "y":595},
                    "size":{
                      "width":394,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34acdfa742c54939ba07bca9b1befa59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F3F3},
                        "location":{
                          "x":390,
                          "y":595},
                        "size":{
                          "width":394,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home___1/u30.png"}},
{
                  "id":"b9cd48b21da7427ebc2fb038da29da72",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":440,
                      "y":136},
                    "size":{
                      "width":284,
                      "height":94},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffcf9241c9ab4741a83e8cb0fbd4b4da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":440,
                          "y":136},
                        "size":{
                          "width":284,
                          "height":94},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open contacts in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e6d0ca6a73049ababad4897e5a645ad",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":440,
                      "y":250},
                    "size":{
                      "width":285,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cff05a6c9d947f8bccbc341cc49a112",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":440,
                          "y":250},
                        "size":{
                          "width":285,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open recents in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"recents.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cb9bfab011454459b6a727ee37958e5a",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":440,
                      "y":370},
                    "size":{
                      "width":285,
                      "height":90},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6a314646b3743b8920d063c6f3acf56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":440,
                          "y":370},
                        "size":{
                          "width":285,
                          "height":90},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open messages in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"messages.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8614f0beb504442b10a4c1109b9cc5d",
                  "label":"",
                  "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Verdana Normal', 'Verdana'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":440,
                      "y":486},
                    "size":{
                      "width":285,
                      "height":94},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ac13ff7e101488da4f93675ce91cc0d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"05f1a06bdc3f46b8bbb5882ee3b45888",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Verdana Normal', 'Verdana'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":440,
                          "y":486},
                        "size":{
                          "width":285,
                          "height":94},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open favorites in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"favorites.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f45c7171c3aa4cb6acf73ddd8e5b8fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":-20,
              "y":28},
            "size":{
              "width":467,
              "height":682},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"806d8dd05e4b4af5b93a25f63bc339ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":-20,
                  "y":28},
                "size":{
                  "width":467,
                  "height":682},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home___1/u40.png"}},
{
          "id":"d695c0ac4a5845f9a55d21fb9d00ff71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":842,
              "y":26},
            "size":{
              "width":467,
              "height":682},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a700ac34e3e94d7fbf66041a996058b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":842,
                  "y":26},
                "size":{
                  "width":467,
                  "height":682},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home___1/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "05f1a06bdc3f46b8bbb5882ee3b45888":{
      "scriptId":"u0"},
    "7d0f01efdca04da4b83b3ae4bddece66":{
      "scriptId":"u1"},
    "6ae180b686dc417bbe82266006b601f2":{
      "scriptId":"u2"},
    "92bc12339f2b43ba8c52a4d405c94c0b":{
      "scriptId":"u3"},
    "f9677b08565c4473b3efc18fd94714e2":{
      "scriptId":"u4"},
    "20a04c8aa9b747fc9e4f6194cfa204cf":{
      "scriptId":"u5"},
    "6cdf42f8c8c14ec58de03e8a2d3b1371":{
      "scriptId":"u6"},
    "30647660cf1c4d4fb511703365e6d742":{
      "scriptId":"u7"},
    "036465d90dc04d1095197aa849ddeb02":{
      "scriptId":"u8"},
    "fbf6c6e158b442f7aecef36df17d76eb":{
      "scriptId":"u9"},
    "e529a2f9e397451abc40f751a3c82954":{
      "scriptId":"u10"},
    "95e81d10e50b48819a34224bf04a8e1a":{
      "scriptId":"u11"},
    "ae0cc156c4034a8cbe7fd231e4e07057":{
      "scriptId":"u12"},
    "69d660447b794bb7bd20ff5af06dad79":{
      "scriptId":"u13"},
    "95e895e297db4ad19152cf2c6d4e6551":{
      "scriptId":"u14"},
    "2cec4ca792244a3fb6d99aebc8ad9f74":{
      "scriptId":"u15"},
    "5a2d95c3147c4041b9f6b10905484336":{
      "scriptId":"u16"},
    "15c899577df24cb18edf3baf11e1f740":{
      "scriptId":"u17"},
    "51d6c108c95248c7b8b5c5ea61c656d7":{
      "scriptId":"u18"},
    "7de0e65667174658a73b8e393acd99da":{
      "scriptId":"u19"},
    "1e6c177ea2844368b1d0e31054f3792d":{
      "scriptId":"u20"},
    "5c84b51d7d444ba2989347e6637ee81e":{
      "scriptId":"u21"},
    "128ee66f85304500b836ffad8237150f":{
      "scriptId":"u22"},
    "c57eab4d9eed4ef6a2670d21b9c7ef8e":{
      "scriptId":"u23"},
    "170a9a987a844db6be3c477752d77e2e":{
      "scriptId":"u24"},
    "d52d3163a6784cc1bd2d0bc8c7936c2c":{
      "scriptId":"u25"},
    "a49cfab4134d41eaa7fdec9447d467cb":{
      "scriptId":"u26"},
    "6d0e44c2aa2b43e490167d144867db4d":{
      "scriptId":"u27"},
    "6dce3335f4524a8d9a42750b7889c348":{
      "scriptId":"u28"},
    "9bb148e15e52401ebdd61411e4ff823f":{
      "scriptId":"u29"},
    "914da7858b644e298a30cab979a13e37":{
      "scriptId":"u30"},
    "34acdfa742c54939ba07bca9b1befa59":{
      "scriptId":"u31"},
    "b9cd48b21da7427ebc2fb038da29da72":{
      "scriptId":"u32"},
    "ffcf9241c9ab4741a83e8cb0fbd4b4da":{
      "scriptId":"u33"},
    "7e6d0ca6a73049ababad4897e5a645ad":{
      "scriptId":"u34"},
    "0cff05a6c9d947f8bccbc341cc49a112":{
      "scriptId":"u35"},
    "cb9bfab011454459b6a727ee37958e5a":{
      "scriptId":"u36"},
    "c6a314646b3743b8920d063c6f3acf56":{
      "scriptId":"u37"},
    "b8614f0beb504442b10a4c1109b9cc5d":{
      "scriptId":"u38"},
    "6ac13ff7e101488da4f93675ce91cc0d":{
      "scriptId":"u39"},
    "f45c7171c3aa4cb6acf73ddd8e5b8fe7":{
      "scriptId":"u40"},
    "806d8dd05e4b4af5b93a25f63bc339ba":{
      "scriptId":"u41"},
    "d695c0ac4a5845f9a55d21fb9d00ff71":{
      "scriptId":"u42"},
    "a700ac34e3e94d7fbf66041a996058b8":{
      "scriptId":"u43"}}});