$axure.loadCurrentPage({
  "url":"message_.html",
  "generationDate":new Date(1406213759274.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0d85c94ce0634b1f9af32640026a2c41",
    "type":"Axure:Page",
    "name":"message+",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d5e06f9393c842f08e68100b68f8459a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":28},
            "size":{
              "width":394,
              "height":657},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b27bab82344359909ae108368078e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":28},
                "size":{
                  "width":394,
                  "height":657},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/message_/u0.png"}},
{
          "id":"db83be88d61d4acdb71463aa56158b0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":454,
              "y":633},
            "size":{
              "width":50,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea715c13cbc4ed487aa0e9eb85a9892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":454,
                  "y":633},
                "size":{
                  "width":50,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42a636ee8d284507bcf39bacd0f06032",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF444444},
            "location":{
              "x":730,
              "y":636},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c3438cf95449a0b1d8feaff13a9bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF444444},
                "location":{
                  "x":730,
                  "y":636},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/message_/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d5e06f9393c842f08e68100b68f8459a":{
      "scriptId":"u0"},
    "31b27bab82344359909ae108368078e6":{
      "scriptId":"u1"},
    "db83be88d61d4acdb71463aa56158b0a":{
      "scriptId":"u2"},
    "dea715c13cbc4ed487aa0e9eb85a9892":{
      "scriptId":"u3"},
    "42a636ee8d284507bcf39bacd0f06032":{
      "scriptId":"u4"},
    "94c3438cf95449a0b1d8feaff13a9bfd":{
      "scriptId":"u5"}}});