$axure.loadCurrentPage({
  "url":"recents.html",
  "generationDate":new Date(1406213758786.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b71d7e477af48bfbcc7a787b139091a",
    "type":"Axure:Page",
    "name":"recents",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"853b4240bfdf41d19b91c8dfa4443d95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":29},
            "size":{
              "width":394,
              "height":176},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c648f518de9495086d865350783147f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":447,
                  "y":29},
                "size":{
                  "width":394,
                  "height":176},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/recents/u0.png"}},
{
          "id":"f690fd66481945eca1be6a481ec0d569",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":297},
            "size":{
              "width":394,
              "height":388},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89643712ece74c04b92b8e708a8e47f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":447,
                  "y":297},
                "size":{
                  "width":394,
                  "height":388},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/recents/u2.png"}},
{
          "id":"6d338be4c706423f98cf21df348cc773",
          "label":"move",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":205},
            "size":{
              "width":394,
              "height":92}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d5a7b2e4b94243d3b85c035e9aca8fb4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8427a35899d84ee4a0b1040386707d06",
                  "label":"move-inner",
                  "parentDynamicPanel":"6d338be4c706423f98cf21df348cc773",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-222,
                      "y":0},
                    "size":{
                      "width":840,
                      "height":93}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"75fe9b59522f4fba919ab19ef433cc42",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"521d9c63643847a58b2028e222abf869",
                          "label":"",
                          "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":222,
                              "y":0},
                            "size":{
                              "width":396,
                              "height":93},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7bee484a70ab4cae9c0cffa2f428ee58",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":222,
                                  "y":0},
                                "size":{
                                  "width":396,
                                  "height":93},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/recents/u6.png"}},
{
                          "id":"c55fc7bd236444b29cd133820d7309f8",
                          "label":"",
                          "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":222,
                              "height":93},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fb55c61312554d34805f8cddb5646f7d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":222,
                                  "height":93},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/recents/u8.png"}},
{
                          "id":"3e9ef6767fb34ecf8440aab7e2466ea5",
                          "label":"",
                          "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":618,
                              "y":0},
                            "size":{
                              "width":222,
                              "height":92},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b91f9eddac974c5dad618b9b4e2ef45f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":618,
                                  "y":0},
                                "size":{
                                  "width":222,
                                  "height":92},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/recents/u10.png"}},
{
                          "id":"eb19d50582a04230bcb2eaa8bbc54061",
                          "label":"",
                          "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":223,
                              "y":0},
                            "size":{
                              "width":394,
                              "height":92},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF000000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6231599f042c4adb98e37ab04c3813e3",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8427a35899d84ee4a0b1040386707d06",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":223,
                                  "y":0},
                                "size":{
                                  "width":394,
                                  "height":92},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/recents/u12.png"}}]}]}]}]},
{
          "id":"5edfcb2b366d467bbb06544475500144",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":636},
            "size":{
              "width":63,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece84a31880440498efd8290abd8171c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":636},
                "size":{
                  "width":63,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a3eca692f0141a98a4adcdc9d71ee69",
          "label":"more",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":721,
              "y":456},
            "size":{
              "width":154,
              "height":178},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"948fc68b3d044a7292d4776fa7473b3a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8211370a502946b29fed2ae66ff80bb7",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF363636},
                    "size":{
                      "width":110,
                      "height":173},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8cd9e873213c40209746b34bf3f47d36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF363636},
                        "size":{
                          "width":110,
                          "height":173},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/recents/u17.png"}},
{
                  "id":"0ae058267846440fac432a7bcbf7d5d5",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":56},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a52337cf2fcd4c228d79fcd4cefd70bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":56},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a2f05ce2de1544c5a8d9d45927d8c742",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":99},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fcd5626bb2142fd8fc203adc8e88606",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":99},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"95eee486c9b84349a621f82ef8bede95",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":82},
                    "size":{
                      "width":110,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/contacts/u27_line.png"}},
{
                  "id":"0a0532695e4d4fb3a76ba06e2a543bdd",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":38},
                    "size":{
                      "width":110,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/contacts/u27_line.png"}},
{
                  "id":"66c9c4c4d2b349abaccf2741ef1e8178",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":13},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77119f2d7165418c9ce58a480abaef89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":13},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9178f026001149aeab931e5eb1498b95",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":142},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f143577a6d5942a6b9c3278f18b2b38a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":142},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c3fa5ad4c83401ea3c035a8aede1781",
                  "label":"",
                  "parentDynamicPanel":"6a3eca692f0141a98a4adcdc9d71ee69",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":110,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/contacts/u27_line.png"}}]}]},
{
          "id":"1646b864ec5a4243aff7aded51193927",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":791,
              "y":636},
            "size":{
              "width":48,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4b3fd499324bc5bcfa17717ad8afba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":791,
                  "y":636},
                "size":{
                  "width":48,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle more",
                      "objectsToFades":[{
                          "objectPath":["6a3eca692f0141a98a4adcdc9d71ee69"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2808bbaaf5034266a0883fe462bbf1f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":246},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/home/u38_end.png",
            "line~":"images/home/u38_line.png"}},
{
          "id":"bc947e031861472c967a1cd102b6bdc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":921,
              "y":243},
            "size":{
              "width":398,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efccf223a2414d28a29fa99defc5f1ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":921,
                  "y":243},
                "size":{
                  "width":398,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc9d5268f6a34f18994e42a8acda107e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":336},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/home/u38_end.png",
            "line~":"images/home/u38_line.png"}},
{
          "id":"b0834e12fe554a63827a6946225817b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":921,
              "y":331},
            "size":{
              "width":398,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f8856582ef413d8690524c1e738d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":921,
                  "y":331},
                "size":{
                  "width":398,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab5ee39678dc447a93aaf850fbc90570",
          "label":"left-2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":206},
            "size":{
              "width":394,
              "height":92}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cd99771242b44af0957053e917e12915",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bb589a26729c4f988eb40f98086d9be8",
                  "label":"right",
                  "parentDynamicPanel":"ab5ee39678dc447a93aaf850fbc90570",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":394,
                      "height":92},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56d898e2d6e54821a81fefc375b8b5f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ab5ee39678dc447a93aaf850fbc90570",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":394,
                          "height":92},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring left to Front ",
                              "panelPaths":[{
                                  "panelPath":["53a18ccdc63d431894fc7e05f9b6c278"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"moveWidget",
                              "description":"Move move-inner to (-222,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["8427a35899d84ee4a0b1040386707d06"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-222",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"d1daaf5691ce4c3db50a2d3c0b0f1902",
          "label":"right",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":206},
            "size":{
              "width":394,
              "height":92}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"28476691526d42a68297764aa6b3380f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ff3f1644176442ab4ce63e9c155ccfe",
                  "label":"right",
                  "parentDynamicPanel":"d1daaf5691ce4c3db50a2d3c0b0f1902",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":394,
                      "height":92},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cac109690b74d8598294fb8c1e8a4df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d1daaf5691ce4c3db50a2d3c0b0f1902",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":394,
                          "height":92},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring left-2 to Front ",
                              "panelPaths":[{
                                  "panelPath":["ab5ee39678dc447a93aaf850fbc90570"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"moveWidget",
                              "description":"Move move-inner to (-444,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["8427a35899d84ee4a0b1040386707d06"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-444",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"56aa3b08f6634d6b87a6a4f8d8a0819d",
          "label":"middle",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":206},
            "size":{
              "width":394,
              "height":92}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2257b815bc244cc7a18e38304648fbea",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d91bbcd8effa4c92a9849e1a4bef9a41",
                  "label":"middle",
                  "parentDynamicPanel":"56aa3b08f6634d6b87a6a4f8d8a0819d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":394,
                      "height":92},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d8f84cd2f62247bca60d6aa2d535081c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"56aa3b08f6634d6b87a6a4f8d8a0819d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":394,
                          "height":92},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring right to Front ",
                              "panelPaths":[{
                                  "panelPath":["d1daaf5691ce4c3db50a2d3c0b0f1902"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"moveWidget",
                              "description":"Move move-inner to (-222,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["8427a35899d84ee4a0b1040386707d06"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-222",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"53a18ccdc63d431894fc7e05f9b6c278",
          "label":"left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":206},
            "size":{
              "width":394,
              "height":92}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c21babbc6b1142d58039ac353e833c47",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4163684343714d6a821aa9a7c2039746",
                  "label":"left",
                  "parentDynamicPanel":"53a18ccdc63d431894fc7e05f9b6c278",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":394,
                      "height":92},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68ff689571d947468355d6390cd724a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"53a18ccdc63d431894fc7e05f9b6c278",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":394,
                          "height":92},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelOrder",
                              "description":"Bring middle to Front ",
                              "panelPaths":[{
                                  "panelPath":["56aa3b08f6634d6b87a6a4f8d8a0819d"],
                                  "setOrderInfo":{
                                    "bringToFront":true}}]},
{
                              "action":"moveWidget",
                              "description":"Move move-inner to (0,0) swing 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["8427a35899d84ee4a0b1040386707d06"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"swing",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "853b4240bfdf41d19b91c8dfa4443d95":{
      "scriptId":"u0"},
    "2c648f518de9495086d865350783147f":{
      "scriptId":"u1"},
    "f690fd66481945eca1be6a481ec0d569":{
      "scriptId":"u2"},
    "89643712ece74c04b92b8e708a8e47f2":{
      "scriptId":"u3"},
    "6d338be4c706423f98cf21df348cc773":{
      "scriptId":"u4"},
    "8427a35899d84ee4a0b1040386707d06":{
      "scriptId":"u5"},
    "521d9c63643847a58b2028e222abf869":{
      "scriptId":"u6"},
    "7bee484a70ab4cae9c0cffa2f428ee58":{
      "scriptId":"u7"},
    "c55fc7bd236444b29cd133820d7309f8":{
      "scriptId":"u8"},
    "fb55c61312554d34805f8cddb5646f7d":{
      "scriptId":"u9"},
    "3e9ef6767fb34ecf8440aab7e2466ea5":{
      "scriptId":"u10"},
    "b91f9eddac974c5dad618b9b4e2ef45f":{
      "scriptId":"u11"},
    "eb19d50582a04230bcb2eaa8bbc54061":{
      "scriptId":"u12"},
    "6231599f042c4adb98e37ab04c3813e3":{
      "scriptId":"u13"},
    "5edfcb2b366d467bbb06544475500144":{
      "scriptId":"u14"},
    "ece84a31880440498efd8290abd8171c":{
      "scriptId":"u15"},
    "6a3eca692f0141a98a4adcdc9d71ee69":{
      "scriptId":"u16"},
    "8211370a502946b29fed2ae66ff80bb7":{
      "scriptId":"u17"},
    "8cd9e873213c40209746b34bf3f47d36":{
      "scriptId":"u18"},
    "0ae058267846440fac432a7bcbf7d5d5":{
      "scriptId":"u19"},
    "a52337cf2fcd4c228d79fcd4cefd70bf":{
      "scriptId":"u20"},
    "a2f05ce2de1544c5a8d9d45927d8c742":{
      "scriptId":"u21"},
    "6fcd5626bb2142fd8fc203adc8e88606":{
      "scriptId":"u22"},
    "95eee486c9b84349a621f82ef8bede95":{
      "scriptId":"u23"},
    "0a0532695e4d4fb3a76ba06e2a543bdd":{
      "scriptId":"u24"},
    "66c9c4c4d2b349abaccf2741ef1e8178":{
      "scriptId":"u25"},
    "77119f2d7165418c9ce58a480abaef89":{
      "scriptId":"u26"},
    "9178f026001149aeab931e5eb1498b95":{
      "scriptId":"u27"},
    "f143577a6d5942a6b9c3278f18b2b38a":{
      "scriptId":"u28"},
    "0c3fa5ad4c83401ea3c035a8aede1781":{
      "scriptId":"u29"},
    "1646b864ec5a4243aff7aded51193927":{
      "scriptId":"u30"},
    "0a4b3fd499324bc5bcfa17717ad8afba":{
      "scriptId":"u31"},
    "2808bbaaf5034266a0883fe462bbf1f4":{
      "scriptId":"u32"},
    "bc947e031861472c967a1cd102b6bdc9":{
      "scriptId":"u33"},
    "efccf223a2414d28a29fa99defc5f1ec":{
      "scriptId":"u34"},
    "bc9d5268f6a34f18994e42a8acda107e":{
      "scriptId":"u35"},
    "b0834e12fe554a63827a6946225817b3":{
      "scriptId":"u36"},
    "93f8856582ef413d8690524c1e738d98":{
      "scriptId":"u37"},
    "ab5ee39678dc447a93aaf850fbc90570":{
      "scriptId":"u38"},
    "bb589a26729c4f988eb40f98086d9be8":{
      "scriptId":"u39"},
    "56d898e2d6e54821a81fefc375b8b5f1":{
      "scriptId":"u40"},
    "d1daaf5691ce4c3db50a2d3c0b0f1902":{
      "scriptId":"u41"},
    "0ff3f1644176442ab4ce63e9c155ccfe":{
      "scriptId":"u42"},
    "0cac109690b74d8598294fb8c1e8a4df":{
      "scriptId":"u43"},
    "56aa3b08f6634d6b87a6a4f8d8a0819d":{
      "scriptId":"u44"},
    "d91bbcd8effa4c92a9849e1a4bef9a41":{
      "scriptId":"u45"},
    "d8f84cd2f62247bca60d6aa2d535081c":{
      "scriptId":"u46"},
    "53a18ccdc63d431894fc7e05f9b6c278":{
      "scriptId":"u47"},
    "4163684343714d6a821aa9a7c2039746":{
      "scriptId":"u48"},
    "68ff689571d947468355d6390cd724a5":{
      "scriptId":"u49"}}});