$axure.loadCurrentPage({
  "url":"contacts.html",
  "generationDate":new Date(1406213758535.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9aa084dcbea24bcd92ec0606ef0564d6",
    "type":"Axure:Page",
    "name":"contacts",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b79967af05cc452ba901e601f4096951",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":28},
            "size":{
              "width":394,
              "height":656},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89664978a2b844c9907299899e5f27f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":28},
                "size":{
                  "width":394,
                  "height":656},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u0.png"}},
{
          "id":"f60656cc91814410882167e79a063136",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":465,
              "y":261},
            "size":{
              "width":379,
              "height":118},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731f51c5de1647789f655c6c4d3a9039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":465,
                  "y":261},
                "size":{
                  "width":379,
                  "height":118},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u2.png"}},
{
          "id":"0d68e60e194f42fe9e370687d52a28d6",
          "label":"quan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":251},
            "size":{
              "width":759,
              "height":125}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move quan with drag x",
                      "objectsToMoves":[{
                          "objectPath":["0d68e60e194f42fe9e370687d52a28d6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move quan to (230,251) linear 500ms",
                      "objectsToMoves":[{
                          "objectPath":["0d68e60e194f42fe9e370687d52a28d6"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"230",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"251",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"378802cad4124d5993ea1649449659b9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a9919b65a950425593a766d466b01736",
                  "label":"",
                  "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":112,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":127},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f71553f61a0b45f893c0e2fb9bf629dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":112,
                          "y":0},
                        "size":{
                          "width":218,
                          "height":127},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/contacts/u5.png"}},
{
                  "id":"e896b1855679451b9d4cb6b55a2b35ac",
                  "label":"",
                  "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":347,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":122},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"141e65a4675346dc98f807c9cc1113aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":347,
                          "y":0},
                        "size":{
                          "width":106,
                          "height":122},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/contacts/u7.png"}},
{
                  "id":"5d40baff167241ca94f76137087c0dde",
                  "label":"",
                  "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":4},
                    "size":{
                      "width":107,
                      "height":106},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea1827f025634dae8365dd52b7b6d05e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":4},
                        "size":{
                          "width":107,
                          "height":106},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/contacts/u9.png"}},
{
                  "id":"580b4de68dfe4c598bea3c804addd19f",
                  "label":"",
                  "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF3F3F3},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":307,
                      "height":121},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67c35230b6ee49d8b0ef03cc116c315c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0d68e60e194f42fe9e370687d52a28d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F3F3},
                        "location":{
                          "x":453,
                          "y":0},
                        "size":{
                          "width":307,
                          "height":121},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/contacts/u11.png"}}]}]},
{
          "id":"035b90e452184aa7adeb9c2ae23735d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":237},
            "size":{
              "width":886,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4e81d68c2546fa85df13b9acd632d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":237},
                "size":{
                  "width":886,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u13.png"}},
{
          "id":"c61fb573cff345a49e1e3dde7d377e6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-24,
              "y":241},
            "size":{
              "width":471,
              "height":148},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a2af96c5424f21aaed52e1c5fb81f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-24,
                  "y":241},
                "size":{
                  "width":471,
                  "height":148},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/contacts/u15.png"}},
{
          "id":"f44ab57a80d94f51aac0bce3fb716cd5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":27},
            "size":{
              "width":10,
              "height":657},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCDCDCD}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/contacts/u17_line.png"}},
{
          "id":"0467ce2775a44be6bd31d25163d964a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":448,
              "y":636},
            "size":{
              "width":63,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5691d742f3a841568e8b944860b0682a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":448,
                  "y":636},
                "size":{
                  "width":63,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df611bd863a74e74a4c4ff3d01c95482",
          "label":"more",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":724,
              "y":509},
            "size":{
              "width":155,
              "height":124},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7755383124c24f3d8649d08f8d81ac6d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"46b360987800484fa7e23a192283c657",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF363636},
                    "size":{
                      "width":110,
                      "height":121},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12bef3f036554e76b6217a4a52d256e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF363636},
                        "size":{
                          "width":110,
                          "height":121},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/contacts/u21.png"}},
{
                  "id":"6d8e853bb1844c549b3f0f3de80d5515",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":52},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc5a0e7fa1684ea09c806d148cbbd31f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":52},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"317aa1cbe0604f6b8ec3934c7dc34446",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":95},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b69dbbcf8224212b45c5cbe121d7729",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":95},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fe4068d03eb74218a5efef069a5e4950",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":110,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/contacts/u27_line.png"}},
{
                  "id":"514291fdc5b84870b327401f648eaa36",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":10},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7dd8fbfc15b4d00a53c8c9c5123b217",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":10},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bdfd279c1f6145bbbb99e2474d252c92",
                  "label":"",
                  "parentDynamicPanel":"df611bd863a74e74a4c4ff3d01c95482",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":110,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/contacts/u27_line.png"}}]}]},
{
          "id":"edc5a655aa2f43e69ee6b825bc8ddcfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":448,
              "y":398},
            "size":{
              "width":391,
              "height":233},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f4d1ae813534f949f348b8e219b4d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":448,
                  "y":398},
                "size":{
                  "width":391,
                  "height":233},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"Open profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b347f8a1f6d647d5a2b649f622013d1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":791,
              "y":636},
            "size":{
              "width":49,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffa89fa659e4ce181015f2ba883e011",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":791,
                  "y":636},
                "size":{
                  "width":49,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle more",
                      "objectsToFades":[{
                          "objectPath":["df611bd863a74e74a4c4ff3d01c95482"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f3507ebd25c4679a0f778f5d8896d99",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":306.5},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/home/u38_end.png",
            "line~":"images/home/u38_line.png"}},
{
          "id":"db8ff56e8755402c88f5fc885dd85488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":922,
              "y":304},
            "size":{
              "width":354,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4b2957c6c94e3ba6ab27eb71eabd03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":922,
                  "y":304},
                "size":{
                  "width":354,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d156843c05a489a8e13c96ebf38153b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":922,
              "y":179},
            "size":{
              "width":478,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d47870ae95a413f93174603bf4c6fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":922,
                  "y":179},
                "size":{
                  "width":478,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9b9f8c610a04b0c9576287e5150d528",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF364E5A,
              "opacity":1},
            "lineSpacing":"25px",
            "location":{
              "x":140,
              "y":28},
            "size":{
              "width":240,
              "height":100},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf0345c55d74d2889942a9cf3ad6925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF364E5A,
                  "opacity":1},
                "lineSpacing":"25px",
                "location":{
                  "x":140,
                  "y":28},
                "size":{
                  "width":240,
                  "height":100},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b79967af05cc452ba901e601f4096951":{
      "scriptId":"u0"},
    "89664978a2b844c9907299899e5f27f0":{
      "scriptId":"u1"},
    "f60656cc91814410882167e79a063136":{
      "scriptId":"u2"},
    "731f51c5de1647789f655c6c4d3a9039":{
      "scriptId":"u3"},
    "0d68e60e194f42fe9e370687d52a28d6":{
      "scriptId":"u4"},
    "a9919b65a950425593a766d466b01736":{
      "scriptId":"u5"},
    "f71553f61a0b45f893c0e2fb9bf629dd":{
      "scriptId":"u6"},
    "e896b1855679451b9d4cb6b55a2b35ac":{
      "scriptId":"u7"},
    "141e65a4675346dc98f807c9cc1113aa":{
      "scriptId":"u8"},
    "5d40baff167241ca94f76137087c0dde":{
      "scriptId":"u9"},
    "ea1827f025634dae8365dd52b7b6d05e":{
      "scriptId":"u10"},
    "580b4de68dfe4c598bea3c804addd19f":{
      "scriptId":"u11"},
    "67c35230b6ee49d8b0ef03cc116c315c":{
      "scriptId":"u12"},
    "035b90e452184aa7adeb9c2ae23735d1":{
      "scriptId":"u13"},
    "6b4e81d68c2546fa85df13b9acd632d0":{
      "scriptId":"u14"},
    "c61fb573cff345a49e1e3dde7d377e6a":{
      "scriptId":"u15"},
    "58a2af96c5424f21aaed52e1c5fb81f1":{
      "scriptId":"u16"},
    "f44ab57a80d94f51aac0bce3fb716cd5":{
      "scriptId":"u17"},
    "0467ce2775a44be6bd31d25163d964a6":{
      "scriptId":"u18"},
    "5691d742f3a841568e8b944860b0682a":{
      "scriptId":"u19"},
    "df611bd863a74e74a4c4ff3d01c95482":{
      "scriptId":"u20"},
    "46b360987800484fa7e23a192283c657":{
      "scriptId":"u21"},
    "12bef3f036554e76b6217a4a52d256e3":{
      "scriptId":"u22"},
    "6d8e853bb1844c549b3f0f3de80d5515":{
      "scriptId":"u23"},
    "cc5a0e7fa1684ea09c806d148cbbd31f":{
      "scriptId":"u24"},
    "317aa1cbe0604f6b8ec3934c7dc34446":{
      "scriptId":"u25"},
    "7b69dbbcf8224212b45c5cbe121d7729":{
      "scriptId":"u26"},
    "fe4068d03eb74218a5efef069a5e4950":{
      "scriptId":"u27"},
    "514291fdc5b84870b327401f648eaa36":{
      "scriptId":"u28"},
    "f7dd8fbfc15b4d00a53c8c9c5123b217":{
      "scriptId":"u29"},
    "bdfd279c1f6145bbbb99e2474d252c92":{
      "scriptId":"u30"},
    "edc5a655aa2f43e69ee6b825bc8ddcfa":{
      "scriptId":"u31"},
    "9f4d1ae813534f949f348b8e219b4d61":{
      "scriptId":"u32"},
    "b347f8a1f6d647d5a2b649f622013d1e":{
      "scriptId":"u33"},
    "8ffa89fa659e4ce181015f2ba883e011":{
      "scriptId":"u34"},
    "2f3507ebd25c4679a0f778f5d8896d99":{
      "scriptId":"u35"},
    "db8ff56e8755402c88f5fc885dd85488":{
      "scriptId":"u36"},
    "8e4b2957c6c94e3ba6ab27eb71eabd03":{
      "scriptId":"u37"},
    "5d156843c05a489a8e13c96ebf38153b":{
      "scriptId":"u38"},
    "1d47870ae95a413f93174603bf4c6fb1":{
      "scriptId":"u39"},
    "c9b9f8c610a04b0c9576287e5150d528":{
      "scriptId":"u40"},
    "0bf0345c55d74d2889942a9cf3ad6925":{
      "scriptId":"u41"}}});