$axure.loadCurrentPage({
  "url":"my_profile.html",
  "generationDate":new Date(1406213758143.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2737cbd388d5438c871648801c0e5960",
    "type":"Axure:Page",
    "name":"My profile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"792c16e9df7a47f997f2ef1e409511d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":29},
            "size":{
              "width":392,
              "height":816},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3924888df5c4b1da93a8bbf61900e5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":29},
                "size":{
                  "width":392,
                  "height":816},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u0.png"}},
{
          "id":"8813c670cfa94f1d97fb25da15ff81c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":798},
            "size":{
              "width":58,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9b71db61e2948f0b767e0aefd1a1b39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":798},
                "size":{
                  "width":58,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open more in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"more.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1864a856a6d41babe036b0d0f061a63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":804},
            "size":{
              "width":50,
              "height":37},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50958239c594914b3e2ae07728987c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":804},
                "size":{
                  "width":50,
                  "height":37},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u4.png"}},
{
          "id":"cae03741f06a47188c4ea6085c99be0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF444444},
            "location":{
              "x":732,
              "y":807},
            "size":{
              "width":46,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41ae9641c6c467f93c904259462e882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF444444},
                "location":{
                  "x":732,
                  "y":807},
                "size":{
                  "width":46,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u6.png"}},
{
          "id":"ba8ec09327c54c5fb67b55037fb2acc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":925,
              "y":664},
            "size":{
              "width":475,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ff518b28f7f4df094f4e7815222e78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":925,
                  "y":664},
                "size":{
                  "width":475,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"926315dd5bad4f3bbc665b5334ba5666",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":755},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/home/u38_end.png",
            "line~":"images/home/u38_line.png"}},
{
          "id":"e4c381fb74774b2998936d839ee029f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":925,
              "y":751},
            "size":{
              "width":395,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7818af8cb624c9c8ab4623c11573d40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":925,
                  "y":751},
                "size":{
                  "width":395,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024d2203efba4ed7ba030014970a0e60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F4F3},
            "location":{
              "x":555,
              "y":717},
            "size":{
              "width":180,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55537eb1a5254421a57d0813911ff7ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F4F3},
                "location":{
                  "x":555,
                  "y":717},
                "size":{
                  "width":180,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u13.png"}},
{
          "id":"e859bab3db234e08a0504ae474ec074f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":578,
              "y":727},
            "size":{
              "width":135,
              "height":47},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a993725312bd405497337ae372ab999a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":578,
                  "y":727},
                "size":{
                  "width":135,
                  "height":47},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u15.png"}},
{
          "id":"c4374fbf6e0b4e2cab5d024a504b6c3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FF3F4F3},
            "location":{
              "x":550,
              "y":717},
            "size":{
              "width":180,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b73599b6e74a6c938c64824f4399a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FF3F4F3},
                "location":{
                  "x":550,
                  "y":717},
                "size":{
                  "width":180,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/my_profile/u17.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "792c16e9df7a47f997f2ef1e409511d3":{
      "scriptId":"u0"},
    "c3924888df5c4b1da93a8bbf61900e5b":{
      "scriptId":"u1"},
    "8813c670cfa94f1d97fb25da15ff81c3":{
      "scriptId":"u2"},
    "a9b71db61e2948f0b767e0aefd1a1b39":{
      "scriptId":"u3"},
    "c1864a856a6d41babe036b0d0f061a63":{
      "scriptId":"u4"},
    "e50958239c594914b3e2ae07728987c2":{
      "scriptId":"u5"},
    "cae03741f06a47188c4ea6085c99be0b":{
      "scriptId":"u6"},
    "c41ae9641c6c467f93c904259462e882":{
      "scriptId":"u7"},
    "ba8ec09327c54c5fb67b55037fb2acc3":{
      "scriptId":"u8"},
    "8ff518b28f7f4df094f4e7815222e78a":{
      "scriptId":"u9"},
    "926315dd5bad4f3bbc665b5334ba5666":{
      "scriptId":"u10"},
    "e4c381fb74774b2998936d839ee029f0":{
      "scriptId":"u11"},
    "b7818af8cb624c9c8ab4623c11573d40":{
      "scriptId":"u12"},
    "024d2203efba4ed7ba030014970a0e60":{
      "scriptId":"u13"},
    "55537eb1a5254421a57d0813911ff7ed":{
      "scriptId":"u14"},
    "e859bab3db234e08a0504ae474ec074f":{
      "scriptId":"u15"},
    "a993725312bd405497337ae372ab999a":{
      "scriptId":"u16"},
    "c4374fbf6e0b4e2cab5d024a504b6c3f":{
      "scriptId":"u17"},
    "89b73599b6e74a6c938c64824f4399a2":{
      "scriptId":"u18"}}});