$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1405930026137.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94024b10d4b34224a4b4899622884074",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
},
      "c":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4538fa4a46b0487984e2040350469958",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":800}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"6eff2fc0c8c441aa820a3d9de4f799c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":800}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"4d5f15e958764e579c38dfdc2801195e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"75d09050e84746c4ae211d66a14867b9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4f11d8b4ec94a93aa60de9774dee3ec",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":300},
                    "cornerRadiusTopLeft":"165"},
                  "adaptiveStyles":{
                    "a":{
},
                    "b":{
},
                    "c":{
}},
                  "objects":[{
                      "id":"9b48f8f9d9474516b64f9e056a5147f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":300},
                        "cornerRadiusTopLeft":"165"},
                      "adaptiveStyles":{
                        "a":{
},
                        "b":{
},
                        "c":{
}}}],
                  "images":{
                    "normal~":"images/home/u3.png"}},
{
                  "id":"ecd527e8d6004dd0b8f6efa34ae505ba",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":210}},
                  "adaptiveStyles":{
                    "a":{
},
                    "b":{
},
                    "c":{
}},
                  "objects":[{
                      "id":"0dd867f857a441008d567e9e7cc4062c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":40},
                        "size":{
                          "width":200,
                          "height":210}},
                      "adaptiveStyles":{
                        "a":{
},
                        "b":{
},
                        "c":{
}}}],
                  "images":{
                    "normal~":"images/home/u5.png"}}]},
{
              "id":"924a9667ede04e27b5eb3e5d58502583",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6e5a859a71e24a659ba46386a543a9e0",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":300},
                    "cornerRadiusTopLeft":"165"},
                  "adaptiveStyles":{
                    "a":{
},
                    "b":{
},
                    "c":{
}},
                  "objects":[{
                      "id":"8267545edb724112b89c7b88b6e449c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":300},
                        "cornerRadiusTopLeft":"165"},
                      "adaptiveStyles":{
                        "a":{
},
                        "b":{
},
                        "c":{
}}}],
                  "images":{
                    "normal~":"images/home/u3.png"}},
{
                  "id":"05b8bca9bad44cfe96fa7ffba12e9e33",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":44,
                      "y":85},
                    "size":{
                      "width":230,
                      "height":128}},
                  "adaptiveStyles":{
                    "a":{
},
                    "b":{
},
                    "c":{
}},
                  "objects":[{
                      "id":"8e107d48f7ba466885a7cd8273c845cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":44,
                          "y":85},
                        "size":{
                          "width":230,
                          "height":128}},
                      "adaptiveStyles":{
                        "a":{
},
                        "b":{
},
                        "c":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"112ee411af5543f39f7c36cf613f95ae",
                  "label":"",
                  "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":228},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
                    "a":{
},
                    "b":{
},
                    "c":{
}},
                  "objects":[{
                      "id":"26f216764ec849bcbdc44d49ac5fb412",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d5f15e958764e579c38dfdc2801195e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":228},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
                        "a":{
},
                        "b":{
},
                        "c":{
}}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open gif more in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"gif_more.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u11.png"}}]}]},
{
          "id":"2ca82a8014d24772a35ef1b054d5ac72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":156},
            "size":{
              "width":530,
              "height":80}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"ca7c3103dbfa422daee183d09e072e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":156},
                "size":{
                  "width":530,
                  "height":80}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fe452dd568b4633956aad5f5ded3201",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":94},
            "size":{
              "width":153,
              "height":37}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"056663bb068f41eeb3f4903f60d3ee20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":94},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b7166a5ceba4893916e442dbe5f25da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":134},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"52cd90a41f954ad99eb64f874a17971d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":134},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c38fcf215f74d45894b4e3f9fb9b9cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":636,
              "y":220},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"aa0409ed4c064a0bb6ccaebbe8f9d5c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":636,
                  "y":220},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"83964e8059464eb39f9833e6c5cb9f4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":364},
            "size":{
              "width":530,
              "height":80}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"f97de9d0fe3c4f6fa5abad004cf4e661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":364},
                "size":{
                  "width":530,
                  "height":80}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49619c723a92422184af139ee00ebeb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":302},
            "size":{
              "width":153,
              "height":37}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"2fa9adcf95224885ba50ff22ae0554c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":302},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21c395fad0c649ec8afdf03fd8ee556c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":342},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"546bb21db2814d07bb4f743e2577925e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":342},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84abf63f7d314c81817b6665c6f8621e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":636,
              "y":428},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"a43f65fc4eef42d0a37d41f9fc14cce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":636,
                  "y":428},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"99090b3040704f79933c4368f083bec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":572},
            "size":{
              "width":530,
              "height":80}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"e412264b09884e7fa6f39ec4292fdf61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":572},
                "size":{
                  "width":530,
                  "height":80}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26c793ee44884960890281ee708a173c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":510},
            "size":{
              "width":153,
              "height":37}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"3fa43640e9fc4bbc8c7d7c9d154e3237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":510},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c29855bcfc4c5b8b738a6dedd13d20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":550},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"6f80d1d6497847bd9d001a0a2c7b1716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":550},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53101289bd5047219af6ce59bf00a998",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":636,
              "y":636},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"9e3bd51e6bde4b27a0ef4248973ce3f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":636,
                  "y":636},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"5f25ce9b73a2463f967c10d272d0e89f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":401,
              "y":764},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"1da5f878043d446d918125ab1780c46d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":401,
                  "y":764},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc49c0f843f045dfaca1029d7b576d7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":964,
              "y":0},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"c0b8dcb8df5a4a398372b91d1a13b48d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":964,
                  "y":0},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u39.png"}},
{
          "id":"1a4ab31f47af41019470750d82910740",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":30,
              "y":13},
            "size":{
              "width":150,
              "height":37}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"233f616d1d9245f6b4b09fdf1e23749b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":13},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9ac8132ed054b5b914f4e0afa63c39d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":55},
            "size":{
              "width":993,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u43_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/home/u43_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/home/u43_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/home/u43_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/home/u43_line.png",
            "start~c":"resources/images/transparent.gif",
            "end~c":"resources/images/transparent.gif",
            "line~c":"images/home/u43_line.png",
            "start~c":"resources/images/transparent.gif",
            "end~c":"resources/images/transparent.gif",
            "line~c":"images/home/u43_line.png"}},
{
          "id":"e0ea618f2c9744dd900453ca3253551e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1070,
              "y":154},
            "size":{
              "width":1024,
              "height":58},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"e5731cdaaf644ac7be447479c9b12e78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1070,
                  "y":154},
                "size":{
                  "width":1024,
                  "height":58},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u44.png"}},
{
          "id":"03533d8ab51346a1b990503d6aa806b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1070,
              "y":87},
            "size":{
              "width":1024,
              "height":58},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
}},
          "objects":[{
              "id":"43d70c62539a4069a187d08a9276f8a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1070,
                  "y":87},
                "size":{
                  "width":1024,
                  "height":58},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
}}}],
          "images":{
            "normal~":"images/home/u44.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4538fa4a46b0487984e2040350469958":{
      "scriptId":"u0"},
    "6eff2fc0c8c441aa820a3d9de4f799c4":{
      "scriptId":"u1"},
    "4d5f15e958764e579c38dfdc2801195e":{
      "scriptId":"u2"},
    "d4f11d8b4ec94a93aa60de9774dee3ec":{
      "scriptId":"u3"},
    "9b48f8f9d9474516b64f9e056a5147f2":{
      "scriptId":"u4"},
    "ecd527e8d6004dd0b8f6efa34ae505ba":{
      "scriptId":"u5"},
    "0dd867f857a441008d567e9e7cc4062c":{
      "scriptId":"u6"},
    "6e5a859a71e24a659ba46386a543a9e0":{
      "scriptId":"u7"},
    "8267545edb724112b89c7b88b6e449c8":{
      "scriptId":"u8"},
    "05b8bca9bad44cfe96fa7ffba12e9e33":{
      "scriptId":"u9"},
    "8e107d48f7ba466885a7cd8273c845cc":{
      "scriptId":"u10"},
    "112ee411af5543f39f7c36cf613f95ae":{
      "scriptId":"u11"},
    "26f216764ec849bcbdc44d49ac5fb412":{
      "scriptId":"u12"},
    "2ca82a8014d24772a35ef1b054d5ac72":{
      "scriptId":"u13"},
    "ca7c3103dbfa422daee183d09e072e51":{
      "scriptId":"u14"},
    "5fe452dd568b4633956aad5f5ded3201":{
      "scriptId":"u15"},
    "056663bb068f41eeb3f4903f60d3ee20":{
      "scriptId":"u16"},
    "2b7166a5ceba4893916e442dbe5f25da":{
      "scriptId":"u17"},
    "52cd90a41f954ad99eb64f874a17971d":{
      "scriptId":"u18"},
    "7c38fcf215f74d45894b4e3f9fb9b9cf":{
      "scriptId":"u19"},
    "aa0409ed4c064a0bb6ccaebbe8f9d5c4":{
      "scriptId":"u20"},
    "83964e8059464eb39f9833e6c5cb9f4b":{
      "scriptId":"u21"},
    "f97de9d0fe3c4f6fa5abad004cf4e661":{
      "scriptId":"u22"},
    "49619c723a92422184af139ee00ebeb6":{
      "scriptId":"u23"},
    "2fa9adcf95224885ba50ff22ae0554c3":{
      "scriptId":"u24"},
    "21c395fad0c649ec8afdf03fd8ee556c":{
      "scriptId":"u25"},
    "546bb21db2814d07bb4f743e2577925e":{
      "scriptId":"u26"},
    "84abf63f7d314c81817b6665c6f8621e":{
      "scriptId":"u27"},
    "a43f65fc4eef42d0a37d41f9fc14cce4":{
      "scriptId":"u28"},
    "99090b3040704f79933c4368f083bec6":{
      "scriptId":"u29"},
    "e412264b09884e7fa6f39ec4292fdf61":{
      "scriptId":"u30"},
    "26c793ee44884960890281ee708a173c":{
      "scriptId":"u31"},
    "3fa43640e9fc4bbc8c7d7c9d154e3237":{
      "scriptId":"u32"},
    "e1c29855bcfc4c5b8b738a6dedd13d20":{
      "scriptId":"u33"},
    "6f80d1d6497847bd9d001a0a2c7b1716":{
      "scriptId":"u34"},
    "53101289bd5047219af6ce59bf00a998":{
      "scriptId":"u35"},
    "9e3bd51e6bde4b27a0ef4248973ce3f7":{
      "scriptId":"u36"},
    "5f25ce9b73a2463f967c10d272d0e89f":{
      "scriptId":"u37"},
    "1da5f878043d446d918125ab1780c46d":{
      "scriptId":"u38"},
    "bc49c0f843f045dfaca1029d7b576d7b":{
      "scriptId":"u39"},
    "c0b8dcb8df5a4a398372b91d1a13b48d":{
      "scriptId":"u40"},
    "1a4ab31f47af41019470750d82910740":{
      "scriptId":"u41"},
    "233f616d1d9245f6b4b09fdf1e23749b":{
      "scriptId":"u42"},
    "f9ac8132ed054b5b914f4e0afa63c39d":{
      "scriptId":"u43"},
    "e0ea618f2c9744dd900453ca3253551e":{
      "scriptId":"u44"},
    "e5731cdaaf644ac7be447479c9b12e78":{
      "scriptId":"u45"},
    "03533d8ab51346a1b990503d6aa806b3":{
      "scriptId":"u46"},
    "43d70c62539a4069a187d08a9276f8a0":{
      "scriptId":"u47"}}});