$axure.loadCurrentPage({
  "url":"我的收藏.html",
  "generationDate":new Date(1406213772246.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"13e8d53909134384b6b20d6b1bc2949d",
    "type":"Axure:Page",
    "name":"我的收藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e61e605f0e944a1cb9040200ca1bb587",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"cc402a50f8214e19a5f3c7f2c9e6c1e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":396,
              "y":64},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c00edae648492bab90e95745c7797c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":396,
                  "y":64},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"950f25a2c6224eb3800b56d9c492ca40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":110},
            "size":{
              "width":306,
              "height":109},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a5134c8b3c452c9d9455482ab1424d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":110},
                "size":{
                  "width":306,
                  "height":109},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u11.png"}},
{
          "id":"50fb09d38bad41d1936158b4e6f378ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":121},
            "size":{
              "width":84,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade06bcf413e41199ff343ef7b73bd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":121},
                "size":{
                  "width":84,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u23.png"}},
{
          "id":"c401584c83b64453955cdef8b80142f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":420,
              "y":121},
            "size":{
              "width":211,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67de3a41553446ed92fa4768d1884555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":420,
                  "y":121},
                "size":{
                  "width":211,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c2378890ee4467d9edd8fdf7cc36e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":496,
              "y":146},
            "size":{
              "width":70,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ae83d9dee446129f776c877c2e2db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":146},
                "size":{
                  "width":70,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e83884a16c814fbe852d8f331e66e3b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":420,
              "y":145},
            "size":{
              "width":104,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e70479b9c6419db1e0d36cf4f789c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":145},
                "size":{
                  "width":104,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1670ee04d54c45db807a9709f7f9bad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":236},
            "size":{
              "width":306,
              "height":109},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9f8ef2e40c46f2bc772fc62d9f3413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":236},
                "size":{
                  "width":306,
                  "height":109},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的收藏/u11.png"}},
{
          "id":"45a25963b33c4854b4bec21afc467471",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":248},
            "size":{
              "width":84,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132194bed42545859063a55d82d95aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":248},
                "size":{
                  "width":84,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u23.png"}},
{
          "id":"d165834537204ff08c9b836f3cf2361a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":420,
              "y":248},
            "size":{
              "width":211,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5cf98bb5be49dcba1ed7233e83b16f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":420,
                  "y":248},
                "size":{
                  "width":211,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"982ccef4296342dab76713f1dcfce32c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9933,
              "opacity":1},
            "location":{
              "x":420,
              "y":272},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29379d177cca471e98d4fd372a281f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9933,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":272},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cbd74e7c0aa44e9a880bcc0bf42070c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":304},
            "size":{
              "width":93,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"81a00f0d198a4d14b45a631eae8e171b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":178},
            "size":{
              "width":93,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"582d01c4e7da42a2a3f0ae2456f3234e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":178},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"b19a591d0c05401c971a868eb1f16be3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":304},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "e61e605f0e944a1cb9040200ca1bb587":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u5"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u6"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u7"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u8"}},
    "cc402a50f8214e19a5f3c7f2c9e6c1e7":{
      "scriptId":"u9"},
    "29c00edae648492bab90e95745c7797c":{
      "scriptId":"u10"},
    "950f25a2c6224eb3800b56d9c492ca40":{
      "scriptId":"u11"},
    "e1a5134c8b3c452c9d9455482ab1424d":{
      "scriptId":"u12"},
    "50fb09d38bad41d1936158b4e6f378ea":{
      "scriptId":"u13"},
    "ade06bcf413e41199ff343ef7b73bd51":{
      "scriptId":"u14"},
    "c401584c83b64453955cdef8b80142f5":{
      "scriptId":"u15"},
    "67de3a41553446ed92fa4768d1884555":{
      "scriptId":"u16"},
    "4c2378890ee4467d9edd8fdf7cc36e82":{
      "scriptId":"u17"},
    "54ae83d9dee446129f776c877c2e2db8":{
      "scriptId":"u18"},
    "e83884a16c814fbe852d8f331e66e3b9":{
      "scriptId":"u19"},
    "d9e70479b9c6419db1e0d36cf4f789c9":{
      "scriptId":"u20"},
    "1670ee04d54c45db807a9709f7f9bad0":{
      "scriptId":"u21"},
    "aa9f8ef2e40c46f2bc772fc62d9f3413":{
      "scriptId":"u22"},
    "45a25963b33c4854b4bec21afc467471":{
      "scriptId":"u23"},
    "132194bed42545859063a55d82d95aed":{
      "scriptId":"u24"},
    "d165834537204ff08c9b836f3cf2361a":{
      "scriptId":"u25"},
    "bc5cf98bb5be49dcba1ed7233e83b16f":{
      "scriptId":"u26"},
    "982ccef4296342dab76713f1dcfce32c":{
      "scriptId":"u27"},
    "29379d177cca471e98d4fd372a281f3d":{
      "scriptId":"u28"},
    "8cbd74e7c0aa44e9a880bcc0bf42070c":{
      "scriptId":"u29"},
    "81a00f0d198a4d14b45a631eae8e171b":{
      "scriptId":"u30"},
    "582d01c4e7da42a2a3f0ae2456f3234e":{
      "scriptId":"u31"},
    "b19a591d0c05401c971a868eb1f16be3":{
      "scriptId":"u32"}}});