$axure.loadCurrentPage({
  "url":"radiobutton.html",
  "generationDate":new Date(1405078988588.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a628f4898484154ad9583b520a1230d",
    "type":"Axure:Page",
    "name":"radiobutton",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d2e7ce18a009472491a00dbe3fa213fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":39,
              "y":53},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0e4ed0436a45e6a8fbf2aa61ec1580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":39,
                  "y":53},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17dc214d4c9447e696b427f036416fe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":16},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca92330a1abe4dd2a6dc48f40f5af975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":16},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baf2649704704351b90f23bdc93ee82d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":109}},
          "adaptiveStyles":{
},
          "masterId":"8e74194050be4c5f975f3549fb9f251e"},
{
          "id":"5035571fe80440c49027c576234af28e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":162},
            "size":{
              "width":612,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1fda15f66ad4ceebba19727ba8d76c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":162},
                "size":{
                  "width":612,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f20b6e762d4645d19134d3d3857035f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":190},
            "size":{
              "width":157,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61db72652ed947448644709b8e0f2b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":190},
                "size":{
                  "width":157,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radiobutton/u11.png"}},
{
          "id":"2b4f452eb7a945f197b6a08f25955a37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":239,
              "y":198},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f46ba1e4aac4284a524bcfe73154fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":239,
                  "y":198},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00d9b381748141adb4b58c036887176a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":239,
              "y":218},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520e00ce4fc346a98e0b1cbb8e210172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":239,
                  "y":218},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8763c2c435a84b6a9988c9a7a3240329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":239,
              "y":237},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056afc9e2e06408da8ee912aaffb1d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":239,
                  "y":237},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6546fab9760451cb802a6eb5dd6d6a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":239,
              "y":257},
            "size":{
              "width":61,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a76660d03b04e06844e6eca15654051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":239,
                  "y":257},
                "size":{
                  "width":61,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22601fabf0214a1cbc1214dd8388a803",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":330}},
          "adaptiveStyles":{
},
          "masterId":"5fa8c7f09ffc420296cab1c99270b697"},
{
          "id":"dec1af6d9e4b4e1e93d7c81eb39e2457",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":256},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13c4925261564da18fcfa14804359323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":256},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radiobutton/u26.png"}}]}},
  "masters":{
    "8e74194050be4c5f975f3549fb9f251e":{
      "packageId":"8e74194050be4c5f975f3549fb9f251e",
      "type":"Axure:Master",
      "name":"定义",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"42964752674241b1a6df857fc323b96f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"02dc9cd588c94598abcd573136338e55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"4a94a4881d034aa3b507f525bde6ad53",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fde41985e9314cfdaf3db7b91a13cd64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "5fa8c7f09ffc420296cab1c99270b697":{
      "packageId":"5fa8c7f09ffc420296cab1c99270b697",
      "type":"Axure:Master",
      "name":"使用模式",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9e19faebee4a4a428a43681ab487303b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0851fdc090044013b55ede3716f24f23",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"0b0ba2f745d947728bd42b98ba191040",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ff0944793794b5caeb31af0dff0d7d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "d2e7ce18a009472491a00dbe3fa213fc":{
      "scriptId":"u0"},
    "cb0e4ed0436a45e6a8fbf2aa61ec1580":{
      "scriptId":"u1"},
    "17dc214d4c9447e696b427f036416fe4":{
      "scriptId":"u2"},
    "ca92330a1abe4dd2a6dc48f40f5af975":{
      "scriptId":"u3"},
    "baf2649704704351b90f23bdc93ee82d":{
      "scriptId":"u4",
      "42964752674241b1a6df857fc323b96f":{
        "scriptId":"u5"},
      "02dc9cd588c94598abcd573136338e55":{
        "scriptId":"u6"},
      "4a94a4881d034aa3b507f525bde6ad53":{
        "scriptId":"u7"},
      "fde41985e9314cfdaf3db7b91a13cd64":{
        "scriptId":"u8"}},
    "5035571fe80440c49027c576234af28e":{
      "scriptId":"u9"},
    "a1fda15f66ad4ceebba19727ba8d76c9":{
      "scriptId":"u10"},
    "f20b6e762d4645d19134d3d3857035f2":{
      "scriptId":"u11"},
    "61db72652ed947448644709b8e0f2b1a":{
      "scriptId":"u12"},
    "2b4f452eb7a945f197b6a08f25955a37":{
      "scriptId":"u13"},
    "2f46ba1e4aac4284a524bcfe73154fe1":{
      "scriptId":"u14"},
    "00d9b381748141adb4b58c036887176a":{
      "scriptId":"u15"},
    "520e00ce4fc346a98e0b1cbb8e210172":{
      "scriptId":"u16"},
    "8763c2c435a84b6a9988c9a7a3240329":{
      "scriptId":"u17"},
    "056afc9e2e06408da8ee912aaffb1d0b":{
      "scriptId":"u18"},
    "b6546fab9760451cb802a6eb5dd6d6a7":{
      "scriptId":"u19"},
    "5a76660d03b04e06844e6eca15654051":{
      "scriptId":"u20"},
    "22601fabf0214a1cbc1214dd8388a803":{
      "scriptId":"u21",
      "9e19faebee4a4a428a43681ab487303b":{
        "scriptId":"u22"},
      "0851fdc090044013b55ede3716f24f23":{
        "scriptId":"u23"},
      "0b0ba2f745d947728bd42b98ba191040":{
        "scriptId":"u24"},
      "3ff0944793794b5caeb31af0dff0d7d0":{
        "scriptId":"u25"}},
    "dec1af6d9e4b4e1e93d7c81eb39e2457":{
      "scriptId":"u26"},
    "13c4925261564da18fcfa14804359323":{
      "scriptId":"u27"}}});