$axure.loadCurrentPage({
  "url":"我的订单.html",
  "generationDate":new Date(1406213771405.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8a1c4d2aa9c248cd936c7c7fb036ae0d",
    "type":"Axure:Page",
    "name":"我的订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"30655f49824b4a159ac8e9e0807f995a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":83},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"61a69cd110a64b90a715dde83e28168b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":446,
              "y":96},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a25a7f3ec0794f9dadff9abdf84cd169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":96},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5724b89127f94342b62a87d6f1e205c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":369,
              "y":140},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105950dc31634d16a9489896d526a99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":140},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b8e313846624cbf9de31d695427d31d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":363,
              "y":153},
            "size":{
              "width":70,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的订单/u13_line.png"}},
{
          "id":"e793b2d794a6427fba142c1044da7be7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":427,
              "y":153},
            "size":{
              "width":10,
              "height":5},
            "rotation":"135",
            "textRotation":"135",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f463af6394d04d3681c4e687e4178715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":427,
                  "y":153},
                "size":{
                  "width":10,
                  "height":5},
                "rotation":"135",
                "textRotation":"135",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u14.png"}},
{
          "id":"416783df92da4d21a7e0ce2eac50c72f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":153},
            "size":{
              "width":70,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的订单/u13_line.png"}},
{
          "id":"55d7a56058de4ffb8ef15357866b3b05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":520,
              "y":153},
            "size":{
              "width":10,
              "height":5},
            "rotation":"135",
            "textRotation":"135",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ecd972795e445399ba306b0911e6504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":520,
                  "y":153},
                "size":{
                  "width":10,
                  "height":5},
                "rotation":"135",
                "textRotation":"135",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u14.png"}},
{
          "id":"2aaedf58ce814d0e915275fd376e7d2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "location":{
              "x":461,
              "y":140},
            "size":{
              "width":70,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"511dcca15ec540cf84cc03d2e85d4ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "location":{
                  "x":461,
                  "y":140},
                "size":{
                  "width":70,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a645a52969c4eb38bd5c1fac55f6bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":173},
            "size":{
              "width":306,
              "height":127},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17ba9dacd394e05be8923bcca0cf55a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":173},
                "size":{
                  "width":306,
                  "height":127},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u21.png"}},
{
          "id":"b96e7cefad2445eea52657f73d7e39fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":204},
            "size":{
              "width":84,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"add6b9b312214c128b7f1f7ca34e7342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":204},
                "size":{
                  "width":84,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u23.png"}},
{
          "id":"cb05350065d4482485f489de847712ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":140},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae361b087994c4b8c1c2947be49fd75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":140},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u25.png"}},
{
          "id":"6d99a346f8844305aa4c4e42a6aaf4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":369,
              "y":182},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fd4614f4cb941178ef1acf9cfb751e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":182},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f151e97ef7340e9aef595ccd971971b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCCC,
              "opacity":1},
            "location":{
              "x":415,
              "y":182},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e740f91085224e8989728e88b3d4e1f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC,
                  "opacity":1},
                "location":{
                  "x":415,
                  "y":182},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9be1d80a07ae4cd29f35113638f08a84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":470,
              "y":205},
            "size":{
              "width":211,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe15c94ca1f4325bbf5cbb1dde4c152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":470,
                  "y":205},
                "size":{
                  "width":211,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1f34e0e67e4d18860f91e51abd9f96",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":260},
            "size":{
              "width":85,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"47bf2a81fcf742d197b12bd85c6ca463",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":567,
              "y":260},
            "size":{
              "width":85,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"85fc7b54269246afbb9a1ad8fcecdae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":470,
              "y":227},
            "size":{
              "width":150,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"224615295ffc40fa8c0dbb23c9474557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":227},
                "size":{
                  "width":150,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e36e13d867b43ae9be4f67f7727c489",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":314},
            "size":{
              "width":306,
              "height":127},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656995f75b674c97927af535101c087b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":314},
                "size":{
                  "width":306,
                  "height":127},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u21.png"}},
{
          "id":"0b9f59db3135481099378ae0fa1410e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":345},
            "size":{
              "width":84,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd04cb9058a4a148346aa2762bc4810",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":345},
                "size":{
                  "width":84,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u23.png"}},
{
          "id":"09eb452cd9164e47b7a73fe742550cd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":369,
              "y":323},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6583aee124e04a3da3d736a0d0cf0f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":323},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d985599bbcb4ed5bef8c0d00a9907e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCCC,
              "opacity":1},
            "location":{
              "x":415,
              "y":323},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b754f0c503487ab1f30760284d46ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC,
                  "opacity":1},
                "location":{
                  "x":415,
                  "y":323},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e11ae019cfdf4ac08a69a333b60fd79b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":470,
              "y":346},
            "size":{
              "width":211,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4600ed1cd4dd41b7921a0a930e426410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":470,
                  "y":346},
                "size":{
                  "width":211,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09feb4bedafe4ecbaece0e152637e05a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":470,
              "y":368},
            "size":{
              "width":150,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcc017864c74965a0713fbf5b71ebbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":368},
                "size":{
                  "width":150,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"035e936cad1d43ccb43602ad1db60e17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":455},
            "size":{
              "width":306,
              "height":127},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98679547df35419b8098afa9c9818a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":455},
                "size":{
                  "width":306,
                  "height":127},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u21.png"}},
{
          "id":"407077db5d5a44f8a13fe4eb82de105a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":486},
            "size":{
              "width":84,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c71181839e946bb86fb0ca8c3c243d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":486},
                "size":{
                  "width":84,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u23.png"}},
{
          "id":"59add82002074c949066bdb15f7b4892",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":369,
              "y":464},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6076be0dcc040108c3d41a432b8caea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":464},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b89848b3aa7342e5a606db9461a0923c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCCC,
              "opacity":1},
            "location":{
              "x":415,
              "y":464},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595c9062082a4bc6bb70a63bfaa3d33d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC,
                  "opacity":1},
                "location":{
                  "x":415,
                  "y":464},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7f5ea5fd9d04c2bb5c283cc9d5ce53d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":470,
              "y":487},
            "size":{
              "width":211,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79e1e737f0a9479ba4085da57f9b4dbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":470,
                  "y":487},
                "size":{
                  "width":211,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"158580839f8245728257433ab0dbb294",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":470,
              "y":509},
            "size":{
              "width":150,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef069e86c2642c79a658a1aaf96e0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":509},
                "size":{
                  "width":150,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0900bad36efc425c918b0318868abeff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":567,
              "y":406},
            "size":{
              "width":85,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"653c730e4b4c43b8a493ccce0912ae79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":567,
              "y":542},
            "size":{
              "width":85,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e21e0abb866410696e1f6e4591f145d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":567,
                  "y":542},
                "size":{
                  "width":85,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u62.png"}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "30655f49824b4a159ac8e9e0807f995a":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u5"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u6"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u7"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u8"}},
    "61a69cd110a64b90a715dde83e28168b":{
      "scriptId":"u9"},
    "a25a7f3ec0794f9dadff9abdf84cd169":{
      "scriptId":"u10"},
    "5724b89127f94342b62a87d6f1e205c6":{
      "scriptId":"u11"},
    "105950dc31634d16a9489896d526a99e":{
      "scriptId":"u12"},
    "4b8e313846624cbf9de31d695427d31d":{
      "scriptId":"u13"},
    "e793b2d794a6427fba142c1044da7be7":{
      "scriptId":"u14"},
    "f463af6394d04d3681c4e687e4178715":{
      "scriptId":"u15"},
    "416783df92da4d21a7e0ce2eac50c72f":{
      "scriptId":"u16"},
    "55d7a56058de4ffb8ef15357866b3b05":{
      "scriptId":"u17"},
    "5ecd972795e445399ba306b0911e6504":{
      "scriptId":"u18"},
    "2aaedf58ce814d0e915275fd376e7d2f":{
      "scriptId":"u19"},
    "511dcca15ec540cf84cc03d2e85d4ae9":{
      "scriptId":"u20"},
    "2a645a52969c4eb38bd5c1fac55f6bb7":{
      "scriptId":"u21"},
    "e17ba9dacd394e05be8923bcca0cf55a":{
      "scriptId":"u22"},
    "b96e7cefad2445eea52657f73d7e39fa":{
      "scriptId":"u23"},
    "add6b9b312214c128b7f1f7ca34e7342":{
      "scriptId":"u24"},
    "cb05350065d4482485f489de847712ad":{
      "scriptId":"u25"},
    "1ae361b087994c4b8c1c2947be49fd75":{
      "scriptId":"u26"},
    "6d99a346f8844305aa4c4e42a6aaf4a0":{
      "scriptId":"u27"},
    "1fd4614f4cb941178ef1acf9cfb751e2":{
      "scriptId":"u28"},
    "0f151e97ef7340e9aef595ccd971971b":{
      "scriptId":"u29"},
    "e740f91085224e8989728e88b3d4e1f1":{
      "scriptId":"u30"},
    "9be1d80a07ae4cd29f35113638f08a84":{
      "scriptId":"u31"},
    "4fe15c94ca1f4325bbf5cbb1dde4c152":{
      "scriptId":"u32"},
    "9c1f34e0e67e4d18860f91e51abd9f96":{
      "scriptId":"u33"},
    "47bf2a81fcf742d197b12bd85c6ca463":{
      "scriptId":"u34"},
    "85fc7b54269246afbb9a1ad8fcecdae3":{
      "scriptId":"u35"},
    "224615295ffc40fa8c0dbb23c9474557":{
      "scriptId":"u36"},
    "5e36e13d867b43ae9be4f67f7727c489":{
      "scriptId":"u37"},
    "656995f75b674c97927af535101c087b":{
      "scriptId":"u38"},
    "0b9f59db3135481099378ae0fa1410e7":{
      "scriptId":"u39"},
    "bfd04cb9058a4a148346aa2762bc4810":{
      "scriptId":"u40"},
    "09eb452cd9164e47b7a73fe742550cd8":{
      "scriptId":"u41"},
    "6583aee124e04a3da3d736a0d0cf0f8b":{
      "scriptId":"u42"},
    "1d985599bbcb4ed5bef8c0d00a9907e9":{
      "scriptId":"u43"},
    "a4b754f0c503487ab1f30760284d46ba":{
      "scriptId":"u44"},
    "e11ae019cfdf4ac08a69a333b60fd79b":{
      "scriptId":"u45"},
    "4600ed1cd4dd41b7921a0a930e426410":{
      "scriptId":"u46"},
    "09feb4bedafe4ecbaece0e152637e05a":{
      "scriptId":"u47"},
    "6dcc017864c74965a0713fbf5b71ebbc":{
      "scriptId":"u48"},
    "035e936cad1d43ccb43602ad1db60e17":{
      "scriptId":"u49"},
    "98679547df35419b8098afa9c9818a1b":{
      "scriptId":"u50"},
    "407077db5d5a44f8a13fe4eb82de105a":{
      "scriptId":"u51"},
    "3c71181839e946bb86fb0ca8c3c243d8":{
      "scriptId":"u52"},
    "59add82002074c949066bdb15f7b4892":{
      "scriptId":"u53"},
    "c6076be0dcc040108c3d41a432b8caea":{
      "scriptId":"u54"},
    "b89848b3aa7342e5a606db9461a0923c":{
      "scriptId":"u55"},
    "595c9062082a4bc6bb70a63bfaa3d33d":{
      "scriptId":"u56"},
    "a7f5ea5fd9d04c2bb5c283cc9d5ce53d":{
      "scriptId":"u57"},
    "79e1e737f0a9479ba4085da57f9b4dbc":{
      "scriptId":"u58"},
    "158580839f8245728257433ab0dbb294":{
      "scriptId":"u59"},
    "5ef069e86c2642c79a658a1aaf96e0ec":{
      "scriptId":"u60"},
    "0900bad36efc425c918b0318868abeff":{
      "scriptId":"u61"},
    "653c730e4b4c43b8a493ccce0912ae79":{
      "scriptId":"u62"},
    "7e21e0abb866410696e1f6e4591f145d":{
      "scriptId":"u63"}}});