$axure.loadCurrentPage({
  "url":"产品详情页_1.html",
  "generationDate":new Date(1406213763078.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4e1fd81c9ae744b383950b15e614b6ed",
    "type":"Axure:Page",
    "name":"产品详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84d61da88c444be2948a7c9bd06fd7d3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"27d5752eed13481bbcdf859c737dde39",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u84_line.png"}},
{
          "id":"ec87080f5cad47aeb33abdd5d11c8c9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":307,
              "y":63},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f858b00227f411e920cd24fc3761a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":63},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3d81c510af54395ae6dec4da1d30ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":100},
            "size":{
              "width":319,
              "height":265},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fca08e15c6146dbb7a9c132d2718d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":100},
                "size":{
                  "width":319,
                  "height":265},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u12.png"}},
{
          "id":"a808e8b143af4ba9b692624e87f14dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":221,
              "y":325},
            "size":{
              "width":169,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25516dd1365d4eddbc7722c157c511f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":221,
                  "y":325},
                "size":{
                  "width":169,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u18.png"}},
{
          "id":"fde1360739314b7d9da779918d43962b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":414,
              "y":325},
            "size":{
              "width":104,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d828f66f43438b9b564c71eeb925a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":414,
                  "y":325},
                "size":{
                  "width":104,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u20.png"}},
{
          "id":"3afd0fc062644d5f8b21077f816ec5a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":431},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e813ca008d549b6b2a0c246894d2ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":431},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u18.png"}},
{
          "id":"2ff414c33f0144b7b95b00a445ce902a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "lineSpacing":"20px",
            "location":{
              "x":221,
              "y":254},
            "size":{
              "width":299,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"876ae08c392840baac1e7ab820718343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "lineSpacing":"20px",
                "location":{
                  "x":221,
                  "y":254},
                "size":{
                  "width":299,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e358a95c63f4421c80da876b9cbe7334",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "location":{
              "x":230,
              "y":443},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"addd42368f994296a1caf8759989b53e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":443},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2f1a6cf60b047fd878b760db35a419b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":435},
            "size":{
              "width":31,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64dabce64164ea39fc56331c5d92c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":435},
                "size":{
                  "width":31,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"648434ec524946b49fc71e19cfdafca7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":449},
            "size":{
              "width":47,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页_1/u26_line.png"}},
{
          "id":"86607cf8a51943918e12dc0f5a90dc02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":112},
            "size":{
              "width":110,
              "height":137},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf7bb79686114d99a872baddf26b0bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":112},
                "size":{
                  "width":110,
                  "height":137},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u27.png"}},
{
          "id":"413335a73c224052bea436310daa5c05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":376},
            "size":{
              "width":297,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc1ddc36a6f543028e5c5c877a5074fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":376},
                "size":{
                  "width":297,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u29.png"}},
{
          "id":"28a89efdee504d63a81294c3cbb836f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":387},
            "size":{
              "width":115,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9f4add456c499c86bff95ed60c7c76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":387},
                "size":{
                  "width":115,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u31.png"}},
{
          "id":"11481dd8e5ee460a87818771ea59c625",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":383},
            "size":{
              "width":31,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1daec4a007564cee8c2fccfc540d724e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":383},
                "size":{
                  "width":31,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"4ae849be707a4749bd4f7ee74f69802d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":348,
              "y":388},
            "size":{
              "width":112,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e178f56bb846dda648405d009335cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":348,
                  "y":388},
                "size":{
                  "width":112,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d99884cecb6541518e3caee0483406c5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":466},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品详情页/u44_line.png"}},
{
          "id":"24767a57c0a149ae93d96b661dcd33e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":476},
            "size":{
              "width":289,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b01534f46d462d91fb3fc6054a31aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":476},
                "size":{
                  "width":289,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u38.png"}},
{
          "id":"9c63fb676f474b78b158e85b05db61d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b027c4eec4f4fbcb87ec92011643637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"787d5c20a6ab43ec924bad72a847a8a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a45e228aca54f09bca1e0ed8be147ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"beb03d02a7664e4287da009b6b34f437",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949cb574499349b2bac1447cfe18b817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"e93485faf3504dd28b109bec6de39d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":221,
              "y":278},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf050f5bfb3d41b1a3558ce0dbb2c281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":278},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"807bd9945694435fa0d5f0823856a87f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":571,
              "y":391},
            "size":{
              "width":210,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60afae0102e64c4f89517835d69483aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":391},
                "size":{
                  "width":210,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaa011cfea404bd3ad74f4d40bb712fa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":393},
            "size":{
              "width":47,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页_1/u26_line.png"}},
{
          "id":"da9c202da75746868c03996a20bf8181",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":571,
              "y":446},
            "size":{
              "width":210,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91847ace324d4478a8d1aff910beae2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":446},
                "size":{
                  "width":210,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83669b57150b475aa7e870e47bc4307a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x4FF2F2F2},
            "location":{
              "x":751,
              "y":51},
            "size":{
              "width":320,
              "height":582},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59ea05f62c5f43a3b3be7d1b5196824d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4FF2F2F2},
                "location":{
                  "x":751,
                  "y":51},
                "size":{
                  "width":320,
                  "height":582},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u53.png"}},
{
          "id":"3d15d22e96284373b3c323c4f4a10f85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF009191},
{
                  "color":0xFF009191},
{
                  "color":0xFF009999},
{
                  "color":0xFF009999}]},
            "location":{
              "x":751,
              "y":52},
            "size":{
              "width":320,
              "height":47},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32356131e2654af2a895694b5d80f18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF009191},
{
                      "color":0xFF009191},
{
                      "color":0xFF009999},
{
                      "color":0xFF009999}]},
                "location":{
                  "x":751,
                  "y":52},
                "size":{
                  "width":320,
                  "height":47},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u46.png"}},
{
          "id":"195bf7fc16da4e1a951cdbb6cb3431de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":59},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3870f4a4b67d4ab6bcaf9f39ef3a20e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":59},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/方案3/u136.png"}},
{
          "id":"a2e795233abe4d57a9e5520515fde36b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":754,
              "y":59},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392698798b2f4ea8a40eaab2949b9a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":754,
                  "y":59},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/方案3/u136.png"}},
{
          "id":"d148111559b6453f8eca9eec6baa7da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":847,
              "y":63},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b3af6ef01744d46aec7149c80ecfdd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":847,
                  "y":63},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27d6970db05c4b62ad99543cbc0f8917",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":752,
              "y":100},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479752eafedb4c0b894def76e42a2898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":752,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"b6889f832d3e4494a2db09baa511d4db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":832,
              "y":100},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214cdefb176a4d989c782133b803b22c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":832,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"8be735221a304fbaa7141064a7879a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":910,
              "y":100},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9ed69485f3b4e6c933e7300a4ef43b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":910,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"1f36e0bb5e6d4fe49aff569412a20d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":990,
              "y":100},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c62e51848b429bb524f6ec0ac6a609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"70cd22a326b445149c3a4dbce994fdc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":150},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc26c2dd581a46beada02b2ee7e478d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":150},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df05d90208a341d485fcd9c6b410067e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":181},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33b07c27c87a46528e14e31a96673a9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":181},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"967a3d3e59ae4d7990e692967ccf0c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":211},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb1a048aa3742628a59aa641b578272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":211},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7955d8d036c5497b976bb0b4e299d2a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":242},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96e074bba695491ea79dca0e0e871ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":242},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7545a27cb0f49699ad2445dd3ba8302",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":272},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816aec7d4baa454c8bb79cdd33c775ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":272},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50b2ac13a9744cd2975f626be91ee389",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":302},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dd67824ad1d48c9b88186c51f0e2441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":302},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d4fd55a3149445b8641848131b812eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":333},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f62e6121b44e13b1edde353b91a388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":333},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a54f321b5136465c94f10d0d627d3afc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":772,
              "y":359},
            "size":{
              "width":266,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783a1722350f4a13a6db1867df4c74df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":772,
                  "y":359},
                "size":{
                  "width":266,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f57c10fc70a4f67982154605d89bfdf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":772,
              "y":395},
            "size":{
              "width":282,
              "height":238},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c954146fdf57410984748e4c675dd41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":772,
                  "y":395},
                "size":{
                  "width":282,
                  "height":238},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u87.png"}},
{
          "id":"4e86dd0a3279416d8f654e6d87ecdd1f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":725,
              "y":526},
            "size":{
              "width":596,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/发起预约音频通话/u61_end.png",
            "line~":"images/产品详情页_1/u89_line.png"}},
{
          "id":"2f01849f088f4ae593fd356e113bb221",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":1091,
              "y":508},
            "size":{
              "width":210,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf4fc48ee404d6cbfbfc3ae5de475e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":1091,
                  "y":508},
                "size":{
                  "width":210,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f7ffd34bc4341deab2f000bf410683a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":221,
              "y":304},
            "size":{
              "width":303,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b91def5c545c42ebafd185517529497c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":304},
                "size":{
                  "width":303,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dae2b18d27344195ad2b32760d7c4f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1070,
              "y":100},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41fb4ee925fd4378a395c6dfdbdfaaed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1070,
                  "y":100},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"db3e9b43e086440db6a45cb84f8d5298",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1143,
              "y":100},
            "size":{
              "width":67,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abfef90250de486da7f1abfa16af36d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1143,
                  "y":100},
                "size":{
                  "width":67,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u96.png"}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "84d61da88c444be2948a7c9bd06fd7d3":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u5"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u6"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u7"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u8"}},
    "27d5752eed13481bbcdf859c737dde39":{
      "scriptId":"u9"},
    "ec87080f5cad47aeb33abdd5d11c8c9e":{
      "scriptId":"u10"},
    "4f858b00227f411e920cd24fc3761a65":{
      "scriptId":"u11"},
    "e3d81c510af54395ae6dec4da1d30ee3":{
      "scriptId":"u12"},
    "0fca08e15c6146dbb7a9c132d2718d73":{
      "scriptId":"u13"},
    "a808e8b143af4ba9b692624e87f14dc0":{
      "scriptId":"u14"},
    "25516dd1365d4eddbc7722c157c511f5":{
      "scriptId":"u15"},
    "fde1360739314b7d9da779918d43962b":{
      "scriptId":"u16"},
    "17d828f66f43438b9b564c71eeb925a8":{
      "scriptId":"u17"},
    "3afd0fc062644d5f8b21077f816ec5a9":{
      "scriptId":"u18"},
    "2e813ca008d549b6b2a0c246894d2ad8":{
      "scriptId":"u19"},
    "2ff414c33f0144b7b95b00a445ce902a":{
      "scriptId":"u20"},
    "876ae08c392840baac1e7ab820718343":{
      "scriptId":"u21"},
    "e358a95c63f4421c80da876b9cbe7334":{
      "scriptId":"u22"},
    "addd42368f994296a1caf8759989b53e":{
      "scriptId":"u23"},
    "e2f1a6cf60b047fd878b760db35a419b":{
      "scriptId":"u24"},
    "a64dabce64164ea39fc56331c5d92c63":{
      "scriptId":"u25"},
    "648434ec524946b49fc71e19cfdafca7":{
      "scriptId":"u26"},
    "86607cf8a51943918e12dc0f5a90dc02":{
      "scriptId":"u27"},
    "cf7bb79686114d99a872baddf26b0bed":{
      "scriptId":"u28"},
    "413335a73c224052bea436310daa5c05":{
      "scriptId":"u29"},
    "fc1ddc36a6f543028e5c5c877a5074fa":{
      "scriptId":"u30"},
    "28a89efdee504d63a81294c3cbb836f7":{
      "scriptId":"u31"},
    "8a9f4add456c499c86bff95ed60c7c76":{
      "scriptId":"u32"},
    "11481dd8e5ee460a87818771ea59c625":{
      "scriptId":"u33"},
    "1daec4a007564cee8c2fccfc540d724e":{
      "scriptId":"u34"},
    "4ae849be707a4749bd4f7ee74f69802d":{
      "scriptId":"u35"},
    "71e178f56bb846dda648405d009335cf":{
      "scriptId":"u36"},
    "d99884cecb6541518e3caee0483406c5":{
      "scriptId":"u37"},
    "24767a57c0a149ae93d96b661dcd33e6":{
      "scriptId":"u38"},
    "71b01534f46d462d91fb3fc6054a31aa":{
      "scriptId":"u39"},
    "9c63fb676f474b78b158e85b05db61d9":{
      "scriptId":"u40"},
    "0b027c4eec4f4fbcb87ec92011643637":{
      "scriptId":"u41"},
    "787d5c20a6ab43ec924bad72a847a8a1":{
      "scriptId":"u42"},
    "2a45e228aca54f09bca1e0ed8be147ac":{
      "scriptId":"u43"},
    "beb03d02a7664e4287da009b6b34f437":{
      "scriptId":"u44"},
    "949cb574499349b2bac1447cfe18b817":{
      "scriptId":"u45"},
    "e93485faf3504dd28b109bec6de39d51":{
      "scriptId":"u46"},
    "bf050f5bfb3d41b1a3558ce0dbb2c281":{
      "scriptId":"u47"},
    "807bd9945694435fa0d5f0823856a87f":{
      "scriptId":"u48"},
    "60afae0102e64c4f89517835d69483aa":{
      "scriptId":"u49"},
    "aaa011cfea404bd3ad74f4d40bb712fa":{
      "scriptId":"u50"},
    "da9c202da75746868c03996a20bf8181":{
      "scriptId":"u51"},
    "91847ace324d4478a8d1aff910beae2c":{
      "scriptId":"u52"},
    "83669b57150b475aa7e870e47bc4307a":{
      "scriptId":"u53"},
    "59ea05f62c5f43a3b3be7d1b5196824d":{
      "scriptId":"u54"},
    "3d15d22e96284373b3c323c4f4a10f85":{
      "scriptId":"u55"},
    "32356131e2654af2a895694b5d80f18d":{
      "scriptId":"u56"},
    "195bf7fc16da4e1a951cdbb6cb3431de":{
      "scriptId":"u57"},
    "3870f4a4b67d4ab6bcaf9f39ef3a20e8":{
      "scriptId":"u58"},
    "a2e795233abe4d57a9e5520515fde36b":{
      "scriptId":"u59"},
    "392698798b2f4ea8a40eaab2949b9a29":{
      "scriptId":"u60"},
    "d148111559b6453f8eca9eec6baa7da3":{
      "scriptId":"u61"},
    "3b3af6ef01744d46aec7149c80ecfdd1":{
      "scriptId":"u62"},
    "27d6970db05c4b62ad99543cbc0f8917":{
      "scriptId":"u63"},
    "479752eafedb4c0b894def76e42a2898":{
      "scriptId":"u64"},
    "b6889f832d3e4494a2db09baa511d4db":{
      "scriptId":"u65"},
    "214cdefb176a4d989c782133b803b22c":{
      "scriptId":"u66"},
    "8be735221a304fbaa7141064a7879a4b":{
      "scriptId":"u67"},
    "b9ed69485f3b4e6c933e7300a4ef43b9":{
      "scriptId":"u68"},
    "1f36e0bb5e6d4fe49aff569412a20d9d":{
      "scriptId":"u69"},
    "50c62e51848b429bb524f6ec0ac6a609":{
      "scriptId":"u70"},
    "70cd22a326b445149c3a4dbce994fdc8":{
      "scriptId":"u71"},
    "cc26c2dd581a46beada02b2ee7e478d5":{
      "scriptId":"u72"},
    "df05d90208a341d485fcd9c6b410067e":{
      "scriptId":"u73"},
    "33b07c27c87a46528e14e31a96673a9d":{
      "scriptId":"u74"},
    "967a3d3e59ae4d7990e692967ccf0c20":{
      "scriptId":"u75"},
    "aeb1a048aa3742628a59aa641b578272":{
      "scriptId":"u76"},
    "7955d8d036c5497b976bb0b4e299d2a0":{
      "scriptId":"u77"},
    "96e074bba695491ea79dca0e0e871ece":{
      "scriptId":"u78"},
    "a7545a27cb0f49699ad2445dd3ba8302":{
      "scriptId":"u79"},
    "816aec7d4baa454c8bb79cdd33c775ab":{
      "scriptId":"u80"},
    "50b2ac13a9744cd2975f626be91ee389":{
      "scriptId":"u81"},
    "9dd67824ad1d48c9b88186c51f0e2441":{
      "scriptId":"u82"},
    "1d4fd55a3149445b8641848131b812eb":{
      "scriptId":"u83"},
    "84f62e6121b44e13b1edde353b91a388":{
      "scriptId":"u84"},
    "a54f321b5136465c94f10d0d627d3afc":{
      "scriptId":"u85"},
    "783a1722350f4a13a6db1867df4c74df":{
      "scriptId":"u86"},
    "5f57c10fc70a4f67982154605d89bfdf":{
      "scriptId":"u87"},
    "c954146fdf57410984748e4c675dd41a":{
      "scriptId":"u88"},
    "4e86dd0a3279416d8f654e6d87ecdd1f":{
      "scriptId":"u89"},
    "2f01849f088f4ae593fd356e113bb221":{
      "scriptId":"u90"},
    "fbf4fc48ee404d6cbfbfc3ae5de475e9":{
      "scriptId":"u91"},
    "1f7ffd34bc4341deab2f000bf410683a":{
      "scriptId":"u92"},
    "b91def5c545c42ebafd185517529497c":{
      "scriptId":"u93"},
    "dae2b18d27344195ad2b32760d7c4f64":{
      "scriptId":"u94"},
    "41fb4ee925fd4378a395c6dfdbdfaaed":{
      "scriptId":"u95"},
    "db3e9b43e086440db6a45cb84f8d5298":{
      "scriptId":"u96"},
    "abfef90250de486da7f1abfa16af36d2":{
      "scriptId":"u97"}}});