$axure.loadCurrentPage({
  "url":"key_board_.html",
  "generationDate":new Date(1406213759470.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f5c218d9dc44a8ead88896d4320da9c",
    "type":"Axure:Page",
    "name":"key board+",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1575deb4425647ad8a6358c49ed60531",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":28},
            "size":{
              "width":394,
              "height":657},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09add4cac1b34c659bc15165710a9ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":28},
                "size":{
                  "width":394,
                  "height":657},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/key_board_/u0.png"}},
{
          "id":"5f951c0577434eb0b58baa5f3098bd50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":488,
              "y":581},
            "size":{
              "width":57,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e61a8aef21694c89ac02462b771a2652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":488,
                  "y":581},
                "size":{
                  "width":57,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"Open message+ in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"message_.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c148bcf35249d684d98575bac16ec1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":725,
              "y":548},
            "size":{
              "width":155,
              "height":88},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b3608f8a382f474284161e0a245fb400",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5d5239f0fd3a4fccbd3324fcbe81bee9",
                  "label":"",
                  "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF363636},
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":110,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6298c1a3e471450d8c7d0e24d1645f22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF363636},
                        "location":{
                          "x":0,
                          "y":43},
                        "size":{
                          "width":110,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/key_board_/u5.png"}},
{
                  "id":"f6fca486f78349d998ac9ac5b6df086c",
                  "label":"",
                  "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":55},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f782b43040394fce8ea5190d67ef45df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":55},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fa669191fd0c47209a381b60cee32ef9",
                  "label":"",
                  "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF363636},
                    "size":{
                      "width":110,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e41413b5f1e64845b14c445d34e61b05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF363636},
                        "size":{
                          "width":110,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/key_board_/u5.png"}},
{
                  "id":"93ec7443f6034f7e858aee3bfaca0a88",
                  "label":"",
                  "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8e9cd93810842ac95ebc8336c017dc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"11c148bcf35249d684d98575bac16ec1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3f3ed9ec23034bcf8e945722f50c82d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":792,
              "y":637},
            "size":{
              "width":49,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f90350b5512b412987c482fede612780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":792,
                  "y":637},
                "size":{
                  "width":49,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle (Dynamic Panel)",
                      "objectsToFades":[{
                          "objectPath":["11c148bcf35249d684d98575bac16ec1"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30992be028904fa5b8891b80efbfb883",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":454,
              "y":638},
            "size":{
              "width":50,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79751444bbe042b7ab947bc1b9ce6b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":454,
                  "y":638},
                "size":{
                  "width":50,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5802b1c01a21402ab35174e656af3eaa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":604.5},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/key_board_/u17_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/key_board_/u17_line.png"}},
{
          "id":"02e3794f3b38425b8fe4991d5f605280",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":192,
              "y":588},
            "size":{
              "width":198,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6bc76cd9df943688d3c357315027fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":192,
                  "y":588},
                "size":{
                  "width":198,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1575deb4425647ad8a6358c49ed60531":{
      "scriptId":"u0"},
    "09add4cac1b34c659bc15165710a9ef4":{
      "scriptId":"u1"},
    "5f951c0577434eb0b58baa5f3098bd50":{
      "scriptId":"u2"},
    "e61a8aef21694c89ac02462b771a2652":{
      "scriptId":"u3"},
    "11c148bcf35249d684d98575bac16ec1":{
      "scriptId":"u4"},
    "5d5239f0fd3a4fccbd3324fcbe81bee9":{
      "scriptId":"u5"},
    "6298c1a3e471450d8c7d0e24d1645f22":{
      "scriptId":"u6"},
    "f6fca486f78349d998ac9ac5b6df086c":{
      "scriptId":"u7"},
    "f782b43040394fce8ea5190d67ef45df":{
      "scriptId":"u8"},
    "fa669191fd0c47209a381b60cee32ef9":{
      "scriptId":"u9"},
    "e41413b5f1e64845b14c445d34e61b05":{
      "scriptId":"u10"},
    "93ec7443f6034f7e858aee3bfaca0a88":{
      "scriptId":"u11"},
    "f8e9cd93810842ac95ebc8336c017dc0":{
      "scriptId":"u12"},
    "3f3ed9ec23034bcf8e945722f50c82d9":{
      "scriptId":"u13"},
    "f90350b5512b412987c482fede612780":{
      "scriptId":"u14"},
    "30992be028904fa5b8891b80efbfb883":{
      "scriptId":"u15"},
    "79751444bbe042b7ab947bc1b9ce6b2b":{
      "scriptId":"u16"},
    "5802b1c01a21402ab35174e656af3eaa":{
      "scriptId":"u17"},
    "02e3794f3b38425b8fe4991d5f605280":{
      "scriptId":"u18"},
    "b6bc76cd9df943688d3c357315027fbd":{
      "scriptId":"u19"}}});