$axure.loadCurrentPage({
  "url":"设计说明.html",
  "generationDate":new Date(1406213756194.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c45e30a066f4d6588e7b38a632ea03f",
    "type":"Axure:Page",
    "name":"设计说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d438293952bb45a2b6b8f899b59e7242",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":165,
              "y":67},
            "size":{
              "width":118,
              "height":362},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a149eac8f15146b9ae2d9f2fd6116afc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":165,
                  "y":67},
                "size":{
                  "width":118,
                  "height":362},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计说明/u0.png"}},
{
          "id":"ecde60555fb9454991eeec75f2cc4c9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":297,
              "y":64},
            "size":{
              "width":803,
              "height":362},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7562f9bdc51b4440b643ec55ae2e2edf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":297,
                  "y":64},
                "size":{
                  "width":803,
                  "height":362},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计说明/u2.png"}},
{
          "id":"003edaa265514c95b428750c7497c692",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9999},
            "location":{
              "x":840,
              "y":480},
            "size":{
              "width":230,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"22"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba66450089404156870ac5793c21332b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9999},
                "location":{
                  "x":840,
                  "y":480},
                "size":{
                  "width":230,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"22"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设计说明/u4.png"}},
{
          "id":"2b593e681f3d4979aa35ca5daccb8d5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":297,
              "y":180},
            "size":{
              "width":783,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14a557a5125440ca0a9944ac32e1d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":297,
                  "y":180},
                "size":{
                  "width":783,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计说明/u6.png"}},
{
          "id":"a2e3bcebcba94b6bb885f09002dad1ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":297,
              "y":169},
            "size":{
              "width":785,
              "height":108},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a416588ec8ab456ca00d6b955824ca34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":297,
                  "y":169},
                "size":{
                  "width":785,
                  "height":108},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d438293952bb45a2b6b8f899b59e7242":{
      "scriptId":"u0"},
    "a149eac8f15146b9ae2d9f2fd6116afc":{
      "scriptId":"u1"},
    "ecde60555fb9454991eeec75f2cc4c9d":{
      "scriptId":"u2"},
    "7562f9bdc51b4440b643ec55ae2e2edf":{
      "scriptId":"u3"},
    "003edaa265514c95b428750c7497c692":{
      "scriptId":"u4"},
    "ba66450089404156870ac5793c21332b":{
      "scriptId":"u5"},
    "2b593e681f3d4979aa35ca5daccb8d5c":{
      "scriptId":"u6"},
    "b14a557a5125440ca0a9944ac32e1d4f":{
      "scriptId":"u7"},
    "a2e3bcebcba94b6bb885f09002dad1ee":{
      "scriptId":"u8"},
    "a416588ec8ab456ca00d6b955824ca34":{
      "scriptId":"u9"}}});