$axure.loadCurrentPage({
  "url":"产品详情页.html",
  "generationDate":new Date(1406213762127.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"29185e9ba07d431f938c9219bc744f0f",
    "type":"Axure:Page",
    "name":"产品详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84d61da88c444be2948a7c9bd06fd7d3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"27d5752eed13481bbcdf859c737dde39",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u84_line.png"}},
{
          "id":"ec87080f5cad47aeb33abdd5d11c8c9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":307,
              "y":63},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504af9dec0484a7195e54fca15f717ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":63},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d29ab44741a47b18f79144b21e78090",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210.999969482422,
              "y":100},
            "size":{
              "width":320,
              "height":160},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de1a631e1e7346279ec3b64597339e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210.999969482422,
                  "y":100},
                "size":{
                  "width":320,
                  "height":160},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u12.png"}},
{
          "id":"8fc372c8d3824475a8db23b0420de942",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":570,
              "y":524},
            "size":{
              "width":297,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f5778be1024abba0646e3a2305a95b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":524},
                "size":{
                  "width":297,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3d81c510af54395ae6dec4da1d30ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":260},
            "size":{
              "width":319,
              "height":330},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fca08e15c6146dbb7a9c132d2718d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":260},
                "size":{
                  "width":319,
                  "height":330},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u16.png"}},
{
          "id":"a808e8b143af4ba9b692624e87f14dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":221,
              "y":314},
            "size":{
              "width":169,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25516dd1365d4eddbc7722c157c511f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":221,
                  "y":314},
                "size":{
                  "width":169,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u18.png"}},
{
          "id":"fde1360739314b7d9da779918d43962b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":414,
              "y":314},
            "size":{
              "width":104,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d828f66f43438b9b564c71eeb925a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":414,
                  "y":314},
                "size":{
                  "width":104,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u20.png"}},
{
          "id":"39c0cdef568946f4be33a9432d08ed34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":356},
            "size":{
              "width":297,
              "height":171},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5028da89a2b14c338e2288b06c266519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":356},
                "size":{
                  "width":297,
                  "height":171},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u22.png"}},
{
          "id":"fb240fcf80ab46008b43ffea89ee7349",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":485,
              "y":361},
            "size":{
              "width":31,
              "height":31},
            "rotation":"90",
            "textRotation":"90",
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7155e47addd49138987cc312f9c8561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":485,
                  "y":361},
                "size":{
                  "width":31,
                  "height":31},
                "rotation":"90",
                "textRotation":"90",
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"3afd0fc062644d5f8b21077f816ec5a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":540},
            "size":{
              "width":297,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e813ca008d549b6b2a0c246894d2ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":540},
                "size":{
                  "width":297,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u26.png"}},
{
          "id":"2ff414c33f0144b7b95b00a445ce902a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "lineSpacing":"20px",
            "location":{
              "x":221,
              "y":266},
            "size":{
              "width":299,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dfa686c0e64beeb61bd198304d9995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "lineSpacing":"20px",
                "location":{
                  "x":221,
                  "y":266},
                "size":{
                  "width":299,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca23fdf7ee9a4d1cb85d83c05fd84341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":230,
              "y":401},
            "size":{
              "width":270,
              "height":120},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7aac5a02784431af7a6b7f5aa9bf2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":230,
                  "y":401},
                "size":{
                  "width":270,
                  "height":120},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c63fb676f474b78b158e85b05db61d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b027c4eec4f4fbcb87ec92011643637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"787d5c20a6ab43ec924bad72a847a8a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a45e228aca54f09bca1e0ed8be147ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"beb03d02a7664e4287da009b6b34f437",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949cb574499349b2bac1447cfe18b817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"36eeecaff5bb4e34ae3d4f07d9b04d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "location":{
              "x":230,
              "y":369},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62372229b8b4915954b79315af8ee0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":369},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e358a95c63f4421c80da876b9cbe7334",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "location":{
              "x":230,
              "y":552},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7760de08fb924ccbbca18c4ec22f41c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":552},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2f1a6cf60b047fd878b760db35a419b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":544},
            "size":{
              "width":31,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64dabce64164ea39fc56331c5d92c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":544},
                "size":{
                  "width":31,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"b2709c9358044ac2a8735797e8a51a9f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":390},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品详情页/u44_line.png"}},
{
          "id":"648434ec524946b49fc71e19cfdafca7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":349,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页/u45_line.png"}},
{
          "id":"478f8797e1904df98d2a0d0d6aa27093",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":370},
            "size":{
              "width":57,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页/u46_line.png"}},
{
          "id":"6340202918374effb012c061a0969bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":577,
              "y":368},
            "size":{
              "width":297,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c58d9941e146dc942527d0a705e29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":368},
                "size":{
                  "width":297,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "84d61da88c444be2948a7c9bd06fd7d3":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u5"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u6"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u7"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u8"}},
    "27d5752eed13481bbcdf859c737dde39":{
      "scriptId":"u9"},
    "ec87080f5cad47aeb33abdd5d11c8c9e":{
      "scriptId":"u10"},
    "504af9dec0484a7195e54fca15f717ec":{
      "scriptId":"u11"},
    "9d29ab44741a47b18f79144b21e78090":{
      "scriptId":"u12"},
    "de1a631e1e7346279ec3b64597339e32":{
      "scriptId":"u13"},
    "8fc372c8d3824475a8db23b0420de942":{
      "scriptId":"u14"},
    "e2f5778be1024abba0646e3a2305a95b":{
      "scriptId":"u15"},
    "e3d81c510af54395ae6dec4da1d30ee3":{
      "scriptId":"u16"},
    "0fca08e15c6146dbb7a9c132d2718d73":{
      "scriptId":"u17"},
    "a808e8b143af4ba9b692624e87f14dc0":{
      "scriptId":"u18"},
    "25516dd1365d4eddbc7722c157c511f5":{
      "scriptId":"u19"},
    "fde1360739314b7d9da779918d43962b":{
      "scriptId":"u20"},
    "17d828f66f43438b9b564c71eeb925a8":{
      "scriptId":"u21"},
    "39c0cdef568946f4be33a9432d08ed34":{
      "scriptId":"u22"},
    "5028da89a2b14c338e2288b06c266519":{
      "scriptId":"u23"},
    "fb240fcf80ab46008b43ffea89ee7349":{
      "scriptId":"u24"},
    "d7155e47addd49138987cc312f9c8561":{
      "scriptId":"u25"},
    "3afd0fc062644d5f8b21077f816ec5a9":{
      "scriptId":"u26"},
    "2e813ca008d549b6b2a0c246894d2ad8":{
      "scriptId":"u27"},
    "2ff414c33f0144b7b95b00a445ce902a":{
      "scriptId":"u28"},
    "90dfa686c0e64beeb61bd198304d9995":{
      "scriptId":"u29"},
    "ca23fdf7ee9a4d1cb85d83c05fd84341":{
      "scriptId":"u30"},
    "5a7aac5a02784431af7a6b7f5aa9bf2f":{
      "scriptId":"u31"},
    "9c63fb676f474b78b158e85b05db61d9":{
      "scriptId":"u32"},
    "0b027c4eec4f4fbcb87ec92011643637":{
      "scriptId":"u33"},
    "787d5c20a6ab43ec924bad72a847a8a1":{
      "scriptId":"u34"},
    "2a45e228aca54f09bca1e0ed8be147ac":{
      "scriptId":"u35"},
    "beb03d02a7664e4287da009b6b34f437":{
      "scriptId":"u36"},
    "949cb574499349b2bac1447cfe18b817":{
      "scriptId":"u37"},
    "36eeecaff5bb4e34ae3d4f07d9b04d92":{
      "scriptId":"u38"},
    "f62372229b8b4915954b79315af8ee0b":{
      "scriptId":"u39"},
    "e358a95c63f4421c80da876b9cbe7334":{
      "scriptId":"u40"},
    "7760de08fb924ccbbca18c4ec22f41c8":{
      "scriptId":"u41"},
    "e2f1a6cf60b047fd878b760db35a419b":{
      "scriptId":"u42"},
    "a64dabce64164ea39fc56331c5d92c63":{
      "scriptId":"u43"},
    "b2709c9358044ac2a8735797e8a51a9f":{
      "scriptId":"u44"},
    "648434ec524946b49fc71e19cfdafca7":{
      "scriptId":"u45"},
    "478f8797e1904df98d2a0d0d6aa27093":{
      "scriptId":"u46"},
    "6340202918374effb012c061a0969bc7":{
      "scriptId":"u47"},
    "c9c58d9941e146dc942527d0a705e29e":{
      "scriptId":"u48"}}});