$axure.loadCurrentPage({
  "url":"商品详情_1.html",
  "generationDate":new Date(1406213767168.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"62f02613b8d8498ea06496e3ccf8076a",
    "type":"Axure:Page",
    "name":"商品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c4cd65e95c514afba07095c27911ab83",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"7b193ba28bd24e2bb810e1ba302e6d98",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u84_line.png"}},
{
          "id":"edf17f6afffa450c90ec0ae378f0da42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":307,
              "y":63},
            "size":{
              "width":128,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78774ff5362441e190cd5846fb5f950e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":63},
                "size":{
                  "width":128,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3924a3fd6a44bcc8e6ff834d5a2a472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":100},
            "size":{
              "width":319,
              "height":287},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf5f73a051e44c6b688de5a905a5037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":100},
                "size":{
                  "width":319,
                  "height":287},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u12.png"}},
{
          "id":"43d53a81eed34a58b512109bd282605b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":221,
              "y":348},
            "size":{
              "width":169,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c9e4a94800c40d0946a239a7a0efa4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":221,
                  "y":348},
                "size":{
                  "width":169,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u18.png"}},
{
          "id":"af2514ce9aef4b769f47ff54ac69d5cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":414,
              "y":348},
            "size":{
              "width":104,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d37df845f52d4447915aaa9a4b55c49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":414,
                  "y":348},
                "size":{
                  "width":104,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u20.png"}},
{
          "id":"03d9f043c7ec41c5afead99555c1e67e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":451},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"174339db1d8447e8b1f3b3e9089aee93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":451},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u18.png"}},
{
          "id":"5dbc6be79adc457c8bdeae328814c0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "lineSpacing":"20px",
            "location":{
              "x":221,
              "y":266},
            "size":{
              "width":299,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74676ba42c024ff8a88f3825fc28056a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "lineSpacing":"20px",
                "location":{
                  "x":221,
                  "y":266},
                "size":{
                  "width":299,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"797fea1ae8574b43b5d920c4088e0e77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "location":{
              "x":230,
              "y":463},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a03508a08234d04977d5984c083f746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":463},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a21fec6d6bba4023a62ecde799b0fa2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":455},
            "size":{
              "width":31,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aab4209e434483fbbdb217e5ed7481e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":455},
                "size":{
                  "width":31,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"0d89e508c00847c2947b5ad3148e0dba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":465},
            "size":{
              "width":47,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页_1/u26_line.png"}},
{
          "id":"ef0e4fa715304824b371f062844d3c1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":112},
            "size":{
              "width":110,
              "height":137},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61cc8a20c7a04fe196720f14e592f87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":112},
                "size":{
                  "width":110,
                  "height":137},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u27.png"}},
{
          "id":"1d8e62e9c0c14274b833d36face6f774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":396},
            "size":{
              "width":297,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22eb1b75e6d41ac83fc594cde5aac27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":396},
                "size":{
                  "width":297,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u29.png"}},
{
          "id":"4c94e7f700ed42ad8a328635093d2157",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":407},
            "size":{
              "width":115,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f67a307aca4db388eb14a91f0706e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":407},
                "size":{
                  "width":115,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u31.png"}},
{
          "id":"d132cabc48ec45feb56c7ae953f468f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":403},
            "size":{
              "width":31,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49f06bb85784440dac146cef725debc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":403},
                "size":{
                  "width":31,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u24.png"}},
{
          "id":"7aa6bc7980fb45ebb6638114a7f05e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":348,
              "y":408},
            "size":{
              "width":112,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3149530521ad4341abf62265148cc001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":348,
                  "y":408},
                "size":{
                  "width":112,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ba39fe9151448ca521d632952c27bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":486},
            "size":{
              "width":280,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品详情页/u44_line.png"}},
{
          "id":"191699a2b92f4657af115f790f081c3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":496},
            "size":{
              "width":289,
              "height":39},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b4573ebe5e4682a375d3c16df0c193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":496},
                "size":{
                  "width":289,
                  "height":39},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页_1/u38.png"}},
{
          "id":"e57c11abb4584fa19dccb41916567953",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"577a2d40ada44125998c9c38d82bc1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"17881f473fd74deb8eaf1647f79eec12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b59df2b9a944a79a245b7ef8c72381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"8c3e79c6623f46959f98490d18e851cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e6f6ac6a1145cd96793a49eca9b359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"e16a31ed3c48475abd35d2292a1e5f5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":221,
              "y":288},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01418ca1f3fe406d9cfd915c3e100db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":288},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5176a6af1e4bba988d71064cf9218d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":571,
              "y":412},
            "size":{
              "width":210,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"683d7fa726184e8bb68c891b465412b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":412},
                "size":{
                  "width":210,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df479f9a554a4387846e9a3b5758a263",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":414},
            "size":{
              "width":47,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/产品详情页/u45_end.png",
            "line~":"images/产品详情页_1/u26_line.png"}},
{
          "id":"e63f9199a8174f2586d2e8059f9811e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":571,
              "y":462},
            "size":{
              "width":210,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d030f8937139444092f3b1956df660a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":462},
                "size":{
                  "width":210,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60403679eebd443aaa93739d9a18c1c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":107},
            "size":{
              "width":135,
              "height":142},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"389de07b98e845bead259cfb5f399f54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":107},
                "size":{
                  "width":135,
                  "height":142},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u53.png"}},
{
          "id":"cc1602b25bdf4062b77d5a9b7261d9a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":107},
            "size":{
              "width":44,
              "height":139},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d947f880f94d2181fe6216cb3655b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":107},
                "size":{
                  "width":44,
                  "height":139},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u55.png"}},
{
          "id":"bed13fbbb33b45dc84d774c9a188c877",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xB2FFFFFF},
            "location":{
              "x":468,
              "y":107},
            "size":{
              "width":61,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46ad439407143dfb5143c9adff6750e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xB2FFFFFF},
                "location":{
                  "x":468,
                  "y":107},
                "size":{
                  "width":61,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u57.png"}},
{
          "id":"9967b9d30289493c89d541204536c18e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":346,
              "y":251},
            "size":{
              "width":8,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12d1b921719443079f029d9632cad6db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":346,
                  "y":251},
                "size":{
                  "width":8,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u59.png"}},
{
          "id":"4a10d0a424134f13a7f4adecc276afac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":251},
            "size":{
              "width":8,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c9e408590b48d28932e633ace62ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":251},
                "size":{
                  "width":8,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u61.png"}},
{
          "id":"862576cfabf7442fad6c082cef858680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":251},
            "size":{
              "width":8,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1a1b2faf504e62b7267322961fc934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":251},
                "size":{
                  "width":8,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情_1/u61.png"}},
{
          "id":"a67dc87165bf4942b89c67911247615b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":308},
            "size":{
              "width":308,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1072d69a4a4e4bba8ff1a2bc2c9d3510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":308},
                "size":{
                  "width":308,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b69f83749a41f79ecb475f132efd61",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":311},
            "size":{
              "width":129,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品详情_1/u67_line.png"}},
{
          "id":"a84d0e8b57a446708e87217b93224939",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":532},
            "size":{
              "width":366,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f29c3855dd4a4aadd4c7761e200f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":532},
                "size":{
                  "width":366,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u82.png"}},
{
          "id":"bfe7cddbce2a4a098fb0eb7346d66614",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u84_line.png"}},
{
          "id":"b9bc572d382c444493b54c5f8044816c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":221,
              "y":330},
            "size":{
              "width":303,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e270402a0cf1497d9c19a5a770766cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":330},
                "size":{
                  "width":303,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "c4cd65e95c514afba07095c27911ab83":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u5"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u6"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u7"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u8"}},
    "7b193ba28bd24e2bb810e1ba302e6d98":{
      "scriptId":"u9"},
    "edf17f6afffa450c90ec0ae378f0da42":{
      "scriptId":"u10"},
    "78774ff5362441e190cd5846fb5f950e":{
      "scriptId":"u11"},
    "d3924a3fd6a44bcc8e6ff834d5a2a472":{
      "scriptId":"u12"},
    "3bf5f73a051e44c6b688de5a905a5037":{
      "scriptId":"u13"},
    "43d53a81eed34a58b512109bd282605b":{
      "scriptId":"u14"},
    "5c9e4a94800c40d0946a239a7a0efa4c":{
      "scriptId":"u15"},
    "af2514ce9aef4b769f47ff54ac69d5cf":{
      "scriptId":"u16"},
    "d37df845f52d4447915aaa9a4b55c49e":{
      "scriptId":"u17"},
    "03d9f043c7ec41c5afead99555c1e67e":{
      "scriptId":"u18"},
    "174339db1d8447e8b1f3b3e9089aee93":{
      "scriptId":"u19"},
    "5dbc6be79adc457c8bdeae328814c0d6":{
      "scriptId":"u20"},
    "74676ba42c024ff8a88f3825fc28056a":{
      "scriptId":"u21"},
    "797fea1ae8574b43b5d920c4088e0e77":{
      "scriptId":"u22"},
    "5a03508a08234d04977d5984c083f746":{
      "scriptId":"u23"},
    "a21fec6d6bba4023a62ecde799b0fa2c":{
      "scriptId":"u24"},
    "8aab4209e434483fbbdb217e5ed7481e":{
      "scriptId":"u25"},
    "0d89e508c00847c2947b5ad3148e0dba":{
      "scriptId":"u26"},
    "ef0e4fa715304824b371f062844d3c1a":{
      "scriptId":"u27"},
    "61cc8a20c7a04fe196720f14e592f87f":{
      "scriptId":"u28"},
    "1d8e62e9c0c14274b833d36face6f774":{
      "scriptId":"u29"},
    "f22eb1b75e6d41ac83fc594cde5aac27":{
      "scriptId":"u30"},
    "4c94e7f700ed42ad8a328635093d2157":{
      "scriptId":"u31"},
    "f4f67a307aca4db388eb14a91f0706e1":{
      "scriptId":"u32"},
    "d132cabc48ec45feb56c7ae953f468f0":{
      "scriptId":"u33"},
    "49f06bb85784440dac146cef725debc8":{
      "scriptId":"u34"},
    "7aa6bc7980fb45ebb6638114a7f05e57":{
      "scriptId":"u35"},
    "3149530521ad4341abf62265148cc001":{
      "scriptId":"u36"},
    "19ba39fe9151448ca521d632952c27bf":{
      "scriptId":"u37"},
    "191699a2b92f4657af115f790f081c3c":{
      "scriptId":"u38"},
    "e3b4573ebe5e4682a375d3c16df0c193":{
      "scriptId":"u39"},
    "e57c11abb4584fa19dccb41916567953":{
      "scriptId":"u40"},
    "577a2d40ada44125998c9c38d82bc1e4":{
      "scriptId":"u41"},
    "17881f473fd74deb8eaf1647f79eec12":{
      "scriptId":"u42"},
    "58b59df2b9a944a79a245b7ef8c72381":{
      "scriptId":"u43"},
    "8c3e79c6623f46959f98490d18e851cb":{
      "scriptId":"u44"},
    "16e6f6ac6a1145cd96793a49eca9b359":{
      "scriptId":"u45"},
    "e16a31ed3c48475abd35d2292a1e5f5d":{
      "scriptId":"u46"},
    "01418ca1f3fe406d9cfd915c3e100db3":{
      "scriptId":"u47"},
    "1f5176a6af1e4bba988d71064cf9218d":{
      "scriptId":"u48"},
    "683d7fa726184e8bb68c891b465412b2":{
      "scriptId":"u49"},
    "df479f9a554a4387846e9a3b5758a263":{
      "scriptId":"u50"},
    "e63f9199a8174f2586d2e8059f9811e7":{
      "scriptId":"u51"},
    "d030f8937139444092f3b1956df660a9":{
      "scriptId":"u52"},
    "60403679eebd443aaa93739d9a18c1c7":{
      "scriptId":"u53"},
    "389de07b98e845bead259cfb5f399f54":{
      "scriptId":"u54"},
    "cc1602b25bdf4062b77d5a9b7261d9a8":{
      "scriptId":"u55"},
    "b1d947f880f94d2181fe6216cb3655b2":{
      "scriptId":"u56"},
    "bed13fbbb33b45dc84d774c9a188c877":{
      "scriptId":"u57"},
    "e46ad439407143dfb5143c9adff6750e":{
      "scriptId":"u58"},
    "9967b9d30289493c89d541204536c18e":{
      "scriptId":"u59"},
    "12d1b921719443079f029d9632cad6db":{
      "scriptId":"u60"},
    "4a10d0a424134f13a7f4adecc276afac":{
      "scriptId":"u61"},
    "37c9e408590b48d28932e633ace62ad6":{
      "scriptId":"u62"},
    "862576cfabf7442fad6c082cef858680":{
      "scriptId":"u63"},
    "5d1a1b2faf504e62b7267322961fc934":{
      "scriptId":"u64"},
    "a67dc87165bf4942b89c67911247615b":{
      "scriptId":"u65"},
    "1072d69a4a4e4bba8ff1a2bc2c9d3510":{
      "scriptId":"u66"},
    "82b69f83749a41f79ecb475f132efd61":{
      "scriptId":"u67"},
    "a84d0e8b57a446708e87217b93224939":{
      "scriptId":"u68"},
    "93f29c3855dd4a4aadd4c7761e200f65":{
      "scriptId":"u69"},
    "bfe7cddbce2a4a098fb0eb7346d66614":{
      "scriptId":"u70"},
    "b9bc572d382c444493b54c5f8044816c":{
      "scriptId":"u71"},
    "e270402a0cf1497d9c19a5a770766cc0":{
      "scriptId":"u72"}}});