$axure.loadCurrentPage({
  "url":"排序.html",
  "generationDate":new Date(1405078989224.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f3955dd1ae2046adaacda96532362257",
    "type":"Axure:Page",
    "name":"排序",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"87598b0b48784ec18d5ee6ceedba37ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":39,
              "y":53},
            "size":{
              "width":92,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c8b10f9f66491088da4df73be7fb58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":39,
                  "y":53},
                "size":{
                  "width":92,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d1b42f2d81a4cc19ba3a896066b74cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":16},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70a9db3c22e34f7189ec503503737871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":16},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051fae6aa89145fb9ed66ae685e51bc0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":109}},
          "adaptiveStyles":{
},
          "masterId":"8e74194050be4c5f975f3549fb9f251e"},
{
          "id":"3674f61590dd4890a583aa53c1963cd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":58,
              "y":159},
            "size":{
              "width":512,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3044f13b53a49fd96f80bb410962c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":58,
                  "y":159},
                "size":{
                  "width":512,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28b56a6f9a8e489b9d963b3d38371ed4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":221}},
          "adaptiveStyles":{
},
          "masterId":"6579d6f101fc4ce2bc579dd08a5b52c7"},
{
          "id":"bb3ed690c82947febc7e86ef32fc5857",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":274},
            "size":{
              "width":592,
              "height":6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42cdeed1e55d4f3aab8935398ea65555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":274},
                "size":{
                  "width":592,
                  "height":6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3be7a81f7d4d4fb1ae1e60e45697ff54",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":420}},
          "adaptiveStyles":{
},
          "masterId":"5fa8c7f09ffc420296cab1c99270b697"},
{
          "id":"3a6394e92a74432fb761bb3f3f552b5f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":480},
            "size":{
              "width":1149,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be9308c6fe54beabb841b887c0188fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":349,
                  "y":50},
                "size":{
                  "width":800,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"291db941adbb4e5b96f8bc7cfd4653c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":349,
                      "y":50},
                    "size":{
                      "width":800,
                      "height":200},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u30.png"}},
{
              "id":"483189d162b34314b71686ce8a24fd6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":349,
                  "y":0},
                "size":{
                  "width":800,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"753792bd8dda45d0bf1fae7df54e70d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF9F9F9},
                    "location":{
                      "x":349,
                      "y":0},
                    "size":{
                      "width":800,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/筛选/u29.png"}},
{
              "id":"3b24c10dbe82430ab7591aee0bd6b7d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":349,
                  "y":250},
                "size":{
                  "width":800,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39e0ba4964c94bb59f6be5e7be5afa51",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":349,
                      "y":250},
                    "size":{
                      "width":800,
                      "height":200},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u30.png"}},
{
              "id":"840a8dd258d7425b9151e015e164544b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "size":{
                  "width":349,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac364f7b025144e68c16e3f521e522f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF9F9F9},
                    "size":{
                      "width":349,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/筛选/u27.png"}},
{
              "id":"2b0f096e806b41e88fd321513558bff3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":349,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6221d14e908442d2bf12d5497d82bd41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":349,
                      "height":200},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u28.png"}},
{
              "id":"6a5018c64cc240e5b38ea84bb15180b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":250},
                "size":{
                  "width":349,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e06ee7eb70e246fead549e6ca3475c63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":250},
                    "size":{
                      "width":349,
                      "height":200},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u28.png"}},
{
              "id":"a5964778344d4974885d638d28cb729e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":450},
                "size":{
                  "width":349,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94a3fab2c11c46dfa994980e5f009271",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":450},
                    "size":{
                      "width":349,
                      "height":300},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u36.png"}},
{
              "id":"913f8d6f7fb149dc9f72a8f4e7e913e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":349,
                  "y":450},
                "size":{
                  "width":800,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1adb3a33ab24454aa58cb9cff4f7fa9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":349,
                      "y":450},
                    "size":{
                      "width":800,
                      "height":300},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/排序/u38.png"}}]},
{
          "id":"8360b651f11648d9a69a4933eda706bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "lineSpacing":"20px",
            "location":{
              "x":194,
              "y":610},
            "size":{
              "width":146,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b224cb9174d4605a9017b133e8d27d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "lineSpacing":"20px",
                "location":{
                  "x":194,
                  "y":610},
                "size":{
                  "width":146,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c98725a0e374b41802cb70e6b51047a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "lineSpacing":"20px",
            "location":{
              "x":194,
              "y":817},
            "size":{
              "width":157,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0067987cc1f347cb9b8247a5862eb22e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "lineSpacing":"20px",
                "location":{
                  "x":194,
                  "y":817},
                "size":{
                  "width":157,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d332359764674f5f8b56d366e85ee97c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":760},
            "size":{
              "width":205,
              "height":30},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eef59a654d54b16b701c9fbd3d7f1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":760},
                "size":{
                  "width":205,
                  "height":30},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u44.png"}},
{
          "id":"7e7c742674d640a8a4b71573c02ae604",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":814},
            "size":{
              "width":199,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4369e54e36d14c1ea2030c758c8f71ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":445,
                  "y":814},
                "size":{
                  "width":199,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u46.png"}},
{
          "id":"acb3673cc4f54a9ab862b41081899449",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":875},
            "size":{
              "width":206,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295e3e58b77f440f85f19ec157f78d56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":875},
                "size":{
                  "width":206,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u48.png"}},
{
          "id":"cf12b1e435bc455f8b3a54bedbb706fb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":790},
            "size":{
              "width":10,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/排序/u50_end.png",
            "line~":"images/排序/u50_line.png"}},
{
          "id":"6b3b18c6a69546b8acde7e163da706c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":611,
              "y":793},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce35ab3672d4081885e12b80673daaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":611,
                  "y":793},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9d41d0315c640ff8367783303c56bde",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":850},
            "size":{
              "width":10,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/排序/u50_end.png",
            "line~":"images/排序/u53_line.png"}},
{
          "id":"f1367f63f1da40e9ab19532444af4356",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":611,
              "y":855},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f029f4e7b178462280daa67d9e10b68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":611,
                  "y":855},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4d3a60a2a904061ba7ab76dd2b691ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":654,
              "y":887},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13230b243fe4c1a9e8e973a52936af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":654,
                  "y":887},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b45e01ec0a6c4fb38d02c8961e27eed4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":654,
              "y":824},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214ccd0127184ed2ba98ff27501f7319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":654,
                  "y":824},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cf7d36b837d445b9f343915804de898",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":433,
              "y":566},
            "size":{
              "width":209,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1618e4b54f74ae1a33ffea9fa49d11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":433,
                  "y":566},
                "size":{
                  "width":209,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u60.png"}},
{
          "id":"f4b1fbf77afc444ca72a98bd40e62927",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":433,
              "y":642},
            "size":{
              "width":231,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf63ba20e87343688c2bd04707a2811d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":433,
                  "y":642},
                "size":{
                  "width":231,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u62.png"}},
{
          "id":"b54c1a4df27a45be98119cd22ae31b87",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":546,
              "y":613},
            "size":{
              "width":10,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/排序/u50_end.png",
            "line~":"images/排序/u50_line.png"}},
{
          "id":"0baccdb02f5646109674ebef18023536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":557,
              "y":616},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9afec59d0e1446fbe2e0610d1e864f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":557,
                  "y":616},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6608c6e098ac4b9085e0a9c298386d15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":674,
              "y":658},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6357eeda66ab473c951fc6f0bcc754d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":674,
                  "y":658},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b330a55d9b47d4b04ff25709340087",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":1292}},
          "adaptiveStyles":{
},
          "masterId":"f0ff36126d564710a144aacaf86cb211"},
{
          "id":"e0e8c0a02dbe40379dc37e7d4a861861",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":1342},
            "size":{
              "width":512,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d4ebc18ec94f2aa1bf84e1a864dff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":1342},
                "size":{
                  "width":512,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04570d99568741a78cd0ab530232b688",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":394,
              "y":1577},
            "size":{
              "width":338,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c59f1e0ac94a74b0cef5c07d67f566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":394,
                  "y":1577},
                "size":{
                  "width":338,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6461ebbec259493c9c2a4419338fbec9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":1599},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/分类/u87_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/排序/u78_line.png"}},
{
          "id":"d33f74b6b03346f5a1d9f4e0b5211507",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":1437},
            "size":{
              "width":313,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f79c84b037d4b9eb0143bfa7636c6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":1437},
                "size":{
                  "width":313,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u79.png"}},
{
          "id":"cf3e6c0ae2b74eb6bb80f6c16141a394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":96,
              "y":1385},
            "size":{
              "width":165,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f579ac647fb242a99e0aebaaedc0e7b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":1385},
                "size":{
                  "width":165,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"874be5f6a52c4eaf92a3a3bb729a1712",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":1407},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/分类/u87_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/排序/u78_line.png"}},
{
          "id":"470c17c1aad146859344cdfa61bcfde1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":1629},
            "size":{
              "width":745,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e340e086d0914edea3294f1a79048347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":1629},
                "size":{
                  "width":745,
                  "height":246}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u84.png"}},
{
          "id":"e383254e3ab648299784b44229586225",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":851,
              "y":1625},
            "size":{
              "width":89,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db0405688db4a6fab551a7b5fe95abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":851,
                  "y":1625},
                "size":{
                  "width":89,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u86.png"}},
{
          "id":"b08d559983e6469aae7ca239e523ac22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":970,
              "y":1636},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c47eb8c45b40958c9b948ef46a74b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":970,
                  "y":1636},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f228c56ab543b68ec3c8adbd68ea69",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":933,
              "y":1639},
            "size":{
              "width":33,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/筛选/u95_end.png",
            "line~":"images/排序/u90_line.png"}},
{
          "id":"d9dc9e764b4d4b6fbd0f231e2fd808d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":851,
              "y":1674},
            "size":{
              "width":89,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a7f8b145084a39874d92e1021949be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":851,
                  "y":1674},
                "size":{
                  "width":89,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u91.png"}},
{
          "id":"31786541d7a5489b8cca569f0b13fa5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":970,
              "y":1688},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d01efec8b68f4507a9e3f06cbed4e79a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":970,
                  "y":1688},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1465e9569bb14a03b7ba79c23bbea95d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":933,
              "y":1690},
            "size":{
              "width":33,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/筛选/u95_end.png",
            "line~":"images/排序/u90_line.png"}},
{
          "id":"55633062cc6e40d28a084a3213cd844c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":1929},
            "size":{
              "width":512,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b177e8994e24c9eaa8aa8d2aeb778bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":1929},
                "size":{
                  "width":512,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71c2625cc729490ab3a17714a1cbaaf0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":2100},
            "size":{
              "width":313,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95e4b3a66a4b4842abf66f7c65c2b09d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":2100},
                "size":{
                  "width":313,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u79.png"}},
{
          "id":"69cf0daa063842c98cb234bf0c815550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":438,
              "y":540},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc282967ce154d169ab92216d08f1daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":540},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6d8f1f344eb471a92ffbf729d981bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":1985},
            "size":{
              "width":532,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"630272c4696f48ea8be96816888f81e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":1985},
                "size":{
                  "width":532,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c055dcc22bc4db0ba71c9da59f534cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":2024},
            "size":{
              "width":277,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b0d0fb600e4c64aa85b0c5b581f0f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":2024},
                "size":{
                  "width":277,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u104.png"}},
{
          "id":"a9769b086fe84aebbce4e3f2699ab5e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":2176},
            "size":{
              "width":290,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47cae5ce9e884e3b9155a406965de4fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":2176},
                "size":{
                  "width":290,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u106.png"}},
{
          "id":"ac4f6ff505ff4de79092ab7dcc05b9f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":2250},
            "size":{
              "width":305,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d43188917f40d9b14a8fbd49fa7283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":2250},
                "size":{
                  "width":305,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u108.png"}},
{
          "id":"053b6aba7e7c4ec1b672bdd6a577bf34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":960},
            "size":{
              "width":245,
              "height":239}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df1196643b4f467399079dda5f49edac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":960},
                "size":{
                  "width":245,
                  "height":239}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排序/u110.png"}},
{
          "id":"4845c83d8ffa4e96b3808557d59b1973",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "lineSpacing":"20px",
            "location":{
              "x":174,
              "y":1080},
            "size":{
              "width":157,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"199fc6b298d9453598ec66c9f1a7eed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "lineSpacing":"20px",
                "location":{
                  "x":174,
                  "y":1080},
                "size":{
                  "width":157,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddc9d0c82a6d426eac3dbd4eed96a232",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":693,
              "y":984},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16a7d345bd974af0a193eebdaef2099e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":693,
                  "y":984},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "8e74194050be4c5f975f3549fb9f251e":{
      "packageId":"8e74194050be4c5f975f3549fb9f251e",
      "type":"Axure:Master",
      "name":"定义",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"42964752674241b1a6df857fc323b96f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"02dc9cd588c94598abcd573136338e55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"4a94a4881d034aa3b507f525bde6ad53",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fde41985e9314cfdaf3db7b91a13cd64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "6579d6f101fc4ce2bc579dd08a5b52c7":{
      "packageId":"6579d6f101fc4ce2bc579dd08a5b52c7",
      "type":"Axure:Master",
      "name":"使用场景",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1d2e4fc6b3d4cafb1f11e29b9503a43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c209a08dda864b84b2825bd8e7969888",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"0a16bd7717cb411b91adf56391e7c608",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46c32ccae2bf43508fa69e5bc8b95f91",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "5fa8c7f09ffc420296cab1c99270b697":{
      "packageId":"5fa8c7f09ffc420296cab1c99270b697",
      "type":"Axure:Master",
      "name":"使用模式",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9e19faebee4a4a428a43681ab487303b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0851fdc090044013b55ede3716f24f23",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"0b0ba2f745d947728bd42b98ba191040",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ff0944793794b5caeb31af0dff0d7d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "f0ff36126d564710a144aacaf86cb211":{
      "packageId":"f0ff36126d564710a144aacaf86cb211",
      "type":"Axure:Master",
      "name":"交互规范",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3d8f4152fcab451bbdbf4428f36212ad",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"432f2e8bb09c446c92749293ae8d2850",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"1ee15f2cc6fd4a319c760f0c91b2f192",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"604d027b51f0487ca6fd8ef765793cf6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "87598b0b48784ec18d5ee6ceedba37ef":{
      "scriptId":"u0"},
    "09c8b10f9f66491088da4df73be7fb58":{
      "scriptId":"u1"},
    "7d1b42f2d81a4cc19ba3a896066b74cd":{
      "scriptId":"u2"},
    "70a9db3c22e34f7189ec503503737871":{
      "scriptId":"u3"},
    "051fae6aa89145fb9ed66ae685e51bc0":{
      "scriptId":"u4",
      "42964752674241b1a6df857fc323b96f":{
        "scriptId":"u5"},
      "02dc9cd588c94598abcd573136338e55":{
        "scriptId":"u6"},
      "4a94a4881d034aa3b507f525bde6ad53":{
        "scriptId":"u7"},
      "fde41985e9314cfdaf3db7b91a13cd64":{
        "scriptId":"u8"}},
    "3674f61590dd4890a583aa53c1963cd8":{
      "scriptId":"u9"},
    "f3044f13b53a49fd96f80bb410962c56":{
      "scriptId":"u10"},
    "28b56a6f9a8e489b9d963b3d38371ed4":{
      "scriptId":"u11",
      "f1d2e4fc6b3d4cafb1f11e29b9503a43":{
        "scriptId":"u12"},
      "c209a08dda864b84b2825bd8e7969888":{
        "scriptId":"u13"},
      "0a16bd7717cb411b91adf56391e7c608":{
        "scriptId":"u14"},
      "46c32ccae2bf43508fa69e5bc8b95f91":{
        "scriptId":"u15"}},
    "bb3ed690c82947febc7e86ef32fc5857":{
      "scriptId":"u16"},
    "42cdeed1e55d4f3aab8935398ea65555":{
      "scriptId":"u17"},
    "3be7a81f7d4d4fb1ae1e60e45697ff54":{
      "scriptId":"u18",
      "9e19faebee4a4a428a43681ab487303b":{
        "scriptId":"u19"},
      "0851fdc090044013b55ede3716f24f23":{
        "scriptId":"u20"},
      "0b0ba2f745d947728bd42b98ba191040":{
        "scriptId":"u21"},
      "3ff0944793794b5caeb31af0dff0d7d0":{
        "scriptId":"u22"}},
    "3a6394e92a74432fb761bb3f3f552b5f":{
      "scriptId":"u23"},
    "840a8dd258d7425b9151e015e164544b":{
      "scriptId":"u24"},
    "ac364f7b025144e68c16e3f521e522f3":{
      "scriptId":"u25"},
    "483189d162b34314b71686ce8a24fd6e":{
      "scriptId":"u26"},
    "753792bd8dda45d0bf1fae7df54e70d4":{
      "scriptId":"u27"},
    "2b0f096e806b41e88fd321513558bff3":{
      "scriptId":"u28"},
    "6221d14e908442d2bf12d5497d82bd41":{
      "scriptId":"u29"},
    "3be9308c6fe54beabb841b887c0188fd":{
      "scriptId":"u30"},
    "291db941adbb4e5b96f8bc7cfd4653c7":{
      "scriptId":"u31"},
    "6a5018c64cc240e5b38ea84bb15180b6":{
      "scriptId":"u32"},
    "e06ee7eb70e246fead549e6ca3475c63":{
      "scriptId":"u33"},
    "3b24c10dbe82430ab7591aee0bd6b7d5":{
      "scriptId":"u34"},
    "39e0ba4964c94bb59f6be5e7be5afa51":{
      "scriptId":"u35"},
    "a5964778344d4974885d638d28cb729e":{
      "scriptId":"u36"},
    "94a3fab2c11c46dfa994980e5f009271":{
      "scriptId":"u37"},
    "913f8d6f7fb149dc9f72a8f4e7e913e3":{
      "scriptId":"u38"},
    "e1adb3a33ab24454aa58cb9cff4f7fa9":{
      "scriptId":"u39"},
    "8360b651f11648d9a69a4933eda706bb":{
      "scriptId":"u40"},
    "9b224cb9174d4605a9017b133e8d27d7":{
      "scriptId":"u41"},
    "7c98725a0e374b41802cb70e6b51047a":{
      "scriptId":"u42"},
    "0067987cc1f347cb9b8247a5862eb22e":{
      "scriptId":"u43"},
    "d332359764674f5f8b56d366e85ee97c":{
      "scriptId":"u44"},
    "3eef59a654d54b16b701c9fbd3d7f1ac":{
      "scriptId":"u45"},
    "7e7c742674d640a8a4b71573c02ae604":{
      "scriptId":"u46"},
    "4369e54e36d14c1ea2030c758c8f71ac":{
      "scriptId":"u47"},
    "acb3673cc4f54a9ab862b41081899449":{
      "scriptId":"u48"},
    "295e3e58b77f440f85f19ec157f78d56":{
      "scriptId":"u49"},
    "cf12b1e435bc455f8b3a54bedbb706fb":{
      "scriptId":"u50"},
    "6b3b18c6a69546b8acde7e163da706c3":{
      "scriptId":"u51"},
    "6ce35ab3672d4081885e12b80673daaa":{
      "scriptId":"u52"},
    "f9d41d0315c640ff8367783303c56bde":{
      "scriptId":"u53"},
    "f1367f63f1da40e9ab19532444af4356":{
      "scriptId":"u54"},
    "f029f4e7b178462280daa67d9e10b68c":{
      "scriptId":"u55"},
    "c4d3a60a2a904061ba7ab76dd2b691ca":{
      "scriptId":"u56"},
    "f13230b243fe4c1a9e8e973a52936af0":{
      "scriptId":"u57"},
    "b45e01ec0a6c4fb38d02c8961e27eed4":{
      "scriptId":"u58"},
    "214ccd0127184ed2ba98ff27501f7319":{
      "scriptId":"u59"},
    "2cf7d36b837d445b9f343915804de898":{
      "scriptId":"u60"},
    "e1618e4b54f74ae1a33ffea9fa49d11a":{
      "scriptId":"u61"},
    "f4b1fbf77afc444ca72a98bd40e62927":{
      "scriptId":"u62"},
    "cf63ba20e87343688c2bd04707a2811d":{
      "scriptId":"u63"},
    "b54c1a4df27a45be98119cd22ae31b87":{
      "scriptId":"u64"},
    "0baccdb02f5646109674ebef18023536":{
      "scriptId":"u65"},
    "b9afec59d0e1446fbe2e0610d1e864f1":{
      "scriptId":"u66"},
    "6608c6e098ac4b9085e0a9c298386d15":{
      "scriptId":"u67"},
    "6357eeda66ab473c951fc6f0bcc754d0":{
      "scriptId":"u68"},
    "27b330a55d9b47d4b04ff25709340087":{
      "scriptId":"u69",
      "3d8f4152fcab451bbdbf4428f36212ad":{
        "scriptId":"u70"},
      "432f2e8bb09c446c92749293ae8d2850":{
        "scriptId":"u71"},
      "1ee15f2cc6fd4a319c760f0c91b2f192":{
        "scriptId":"u72"},
      "604d027b51f0487ca6fd8ef765793cf6":{
        "scriptId":"u73"}},
    "e0e8c0a02dbe40379dc37e7d4a861861":{
      "scriptId":"u74"},
    "73d4ebc18ec94f2aa1bf84e1a864dff3":{
      "scriptId":"u75"},
    "04570d99568741a78cd0ab530232b688":{
      "scriptId":"u76"},
    "d4c59f1e0ac94a74b0cef5c07d67f566":{
      "scriptId":"u77"},
    "6461ebbec259493c9c2a4419338fbec9":{
      "scriptId":"u78"},
    "d33f74b6b03346f5a1d9f4e0b5211507":{
      "scriptId":"u79"},
    "7f79c84b037d4b9eb0143bfa7636c6b3":{
      "scriptId":"u80"},
    "cf3e6c0ae2b74eb6bb80f6c16141a394":{
      "scriptId":"u81"},
    "f579ac647fb242a99e0aebaaedc0e7b7":{
      "scriptId":"u82"},
    "874be5f6a52c4eaf92a3a3bb729a1712":{
      "scriptId":"u83"},
    "470c17c1aad146859344cdfa61bcfde1":{
      "scriptId":"u84"},
    "e340e086d0914edea3294f1a79048347":{
      "scriptId":"u85"},
    "e383254e3ab648299784b44229586225":{
      "scriptId":"u86"},
    "2db0405688db4a6fab551a7b5fe95abf":{
      "scriptId":"u87"},
    "b08d559983e6469aae7ca239e523ac22":{
      "scriptId":"u88"},
    "a0c47eb8c45b40958c9b948ef46a74b8":{
      "scriptId":"u89"},
    "50f228c56ab543b68ec3c8adbd68ea69":{
      "scriptId":"u90"},
    "d9dc9e764b4d4b6fbd0f231e2fd808d9":{
      "scriptId":"u91"},
    "30a7f8b145084a39874d92e1021949be":{
      "scriptId":"u92"},
    "31786541d7a5489b8cca569f0b13fa5e":{
      "scriptId":"u93"},
    "d01efec8b68f4507a9e3f06cbed4e79a":{
      "scriptId":"u94"},
    "1465e9569bb14a03b7ba79c23bbea95d":{
      "scriptId":"u95"},
    "55633062cc6e40d28a084a3213cd844c":{
      "scriptId":"u96"},
    "2b177e8994e24c9eaa8aa8d2aeb778bc":{
      "scriptId":"u97"},
    "71c2625cc729490ab3a17714a1cbaaf0":{
      "scriptId":"u98"},
    "95e4b3a66a4b4842abf66f7c65c2b09d":{
      "scriptId":"u99"},
    "69cf0daa063842c98cb234bf0c815550":{
      "scriptId":"u100"},
    "dc282967ce154d169ab92216d08f1daf":{
      "scriptId":"u101"},
    "c6d8f1f344eb471a92ffbf729d981bb9":{
      "scriptId":"u102"},
    "630272c4696f48ea8be96816888f81e0":{
      "scriptId":"u103"},
    "1c055dcc22bc4db0ba71c9da59f534cd":{
      "scriptId":"u104"},
    "62b0d0fb600e4c64aa85b0c5b581f0f0":{
      "scriptId":"u105"},
    "a9769b086fe84aebbce4e3f2699ab5e6":{
      "scriptId":"u106"},
    "47cae5ce9e884e3b9155a406965de4fe":{
      "scriptId":"u107"},
    "ac4f6ff505ff4de79092ab7dcc05b9f5":{
      "scriptId":"u108"},
    "15d43188917f40d9b14a8fbd49fa7283":{
      "scriptId":"u109"},
    "053b6aba7e7c4ec1b672bdd6a577bf34":{
      "scriptId":"u110"},
    "df1196643b4f467399079dda5f49edac":{
      "scriptId":"u111"},
    "4845c83d8ffa4e96b3808557d59b1973":{
      "scriptId":"u112"},
    "199fc6b298d9453598ec66c9f1a7eed1":{
      "scriptId":"u113"},
    "ddc9d0c82a6d426eac3dbd4eed96a232":{
      "scriptId":"u114"},
    "16a7d345bd974af0a193eebdaef2099e":{
      "scriptId":"u115"}}});