$axure.loadCurrentPage({
  "url":"新手引导.html",
  "generationDate":new Date(1406213753703.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"899217edbbb145618e397b14b0a3d8ea",
    "type":"Axure:Page",
    "name":"新手引导",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d30c628d60f8461089275ba1fefca66a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":70,
              "y":100},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c8c4a2650dc4e8ea9155c24ec47b4ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":70,
                  "y":100},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u0.png"}},
{
          "id":"bc233401b5eb49df9affa9ae93d66383",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":455,
              "y":100},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae726f28afed4c4e854e1f557af85141",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":455,
                  "y":100},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u0.png"}},
{
          "id":"a59135272f284fa495e22d127fb66d0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":839,
              "y":100},
            "size":{
              "width":320,
              "height":480},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a82fcf1d364aea9bc29b27d4c8a972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":839,
                  "y":100},
                "size":{
                  "width":320,
                  "height":480},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u4.png"}},
{
          "id":"2d9fd22ba1c344cdaaec3140a294dfcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":70,
              "y":74},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3573898f0a45c7a6c5b7eb4426e245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":74},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edd4aed1ceac4c6283cb6356c7dc2bf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":144,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6870268f2f406f8357c94baea34f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":144,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u8.png"}},
{
          "id":"a5687d7c1be24cb8a34668f0ffafe145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e08a28cd4c3c4762b0d303af7bc89adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":188,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"5b2323e4f20c49d099c0d3013c7685c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e347a6bce55f4a3ca7499dd53dd398f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"5c30ec47e0cc410c8b8b8911e5bb0c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":264,
              "y":514},
            "size":{
              "width":52,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c885aecb872d4132ad493fdbf6dd2aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":264,
                  "y":514},
                "size":{
                  "width":52,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u14.png"}},
{
          "id":"4eb2ba6787c74ead84bbab74d504b589",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":529,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"226175f0d32f460d830bb9e9ca6b3bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":529,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"5494c6c896484a2487f0c9c89f8956c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":573,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71394f2d94f94cb5b343e45f17c62333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":573,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u8.png"}},
{
          "id":"5b3933f54c64453e80950ef31e035a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc6ad5990a6043c488ca8654c115ba5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"02775e1e713c4c3f8ca0f2043894d49e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":649,
              "y":514},
            "size":{
              "width":52,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cfa5b6155e241f1a76265ab4ebb9070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":649,
                  "y":514},
                "size":{
                  "width":52,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u14.png"}},
{
          "id":"ce38b5bba97f43518adadcbd48a48eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":913,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c4529e1dd14dcdaca6bfbf31b12491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":913,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"0e793cbb9eb745c79ebb8253aa24a5b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":957,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1068d1ebc6b4adbb585b0a0897de0a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":957,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u10.png"}},
{
          "id":"3336c7f4bf9f47238a6598f894a18eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":1001,
              "y":518},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b645ba18bf7492286c2cf371f282164",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":1001,
                  "y":518},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u8.png"}},
{
          "id":"706eeec96eb745d2b65a51e6b769b47b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":1033,
              "y":514},
            "size":{
              "width":52,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4841f64c8fee49e8a2606563b28d28f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":1033,
                  "y":514},
                "size":{
                  "width":52,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新手引导/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d30c628d60f8461089275ba1fefca66a":{
      "scriptId":"u0"},
    "8c8c4a2650dc4e8ea9155c24ec47b4ca":{
      "scriptId":"u1"},
    "bc233401b5eb49df9affa9ae93d66383":{
      "scriptId":"u2"},
    "ae726f28afed4c4e854e1f557af85141":{
      "scriptId":"u3"},
    "a59135272f284fa495e22d127fb66d0c":{
      "scriptId":"u4"},
    "72a82fcf1d364aea9bc29b27d4c8a972":{
      "scriptId":"u5"},
    "2d9fd22ba1c344cdaaec3140a294dfcd":{
      "scriptId":"u6"},
    "9b3573898f0a45c7a6c5b7eb4426e245":{
      "scriptId":"u7"},
    "edd4aed1ceac4c6283cb6356c7dc2bf7":{
      "scriptId":"u8"},
    "8b6870268f2f406f8357c94baea34f42":{
      "scriptId":"u9"},
    "a5687d7c1be24cb8a34668f0ffafe145":{
      "scriptId":"u10"},
    "e08a28cd4c3c4762b0d303af7bc89adc":{
      "scriptId":"u11"},
    "5b2323e4f20c49d099c0d3013c7685c9":{
      "scriptId":"u12"},
    "e347a6bce55f4a3ca7499dd53dd398f9":{
      "scriptId":"u13"},
    "5c30ec47e0cc410c8b8b8911e5bb0c17":{
      "scriptId":"u14"},
    "c885aecb872d4132ad493fdbf6dd2aa7":{
      "scriptId":"u15"},
    "4eb2ba6787c74ead84bbab74d504b589":{
      "scriptId":"u16"},
    "226175f0d32f460d830bb9e9ca6b3bdc":{
      "scriptId":"u17"},
    "5494c6c896484a2487f0c9c89f8956c4":{
      "scriptId":"u18"},
    "71394f2d94f94cb5b343e45f17c62333":{
      "scriptId":"u19"},
    "5b3933f54c64453e80950ef31e035a63":{
      "scriptId":"u20"},
    "fc6ad5990a6043c488ca8654c115ba5f":{
      "scriptId":"u21"},
    "02775e1e713c4c3f8ca0f2043894d49e":{
      "scriptId":"u22"},
    "7cfa5b6155e241f1a76265ab4ebb9070":{
      "scriptId":"u23"},
    "ce38b5bba97f43518adadcbd48a48eb7":{
      "scriptId":"u24"},
    "a9c4529e1dd14dcdaca6bfbf31b12491":{
      "scriptId":"u25"},
    "0e793cbb9eb745c79ebb8253aa24a5b8":{
      "scriptId":"u26"},
    "d1068d1ebc6b4adbb585b0a0897de0a0":{
      "scriptId":"u27"},
    "3336c7f4bf9f47238a6598f894a18eb4":{
      "scriptId":"u28"},
    "2b645ba18bf7492286c2cf371f282164":{
      "scriptId":"u29"},
    "706eeec96eb745d2b65a51e6b769b47b":{
      "scriptId":"u30"},
    "4841f64c8fee49e8a2606563b28d28f0":{
      "scriptId":"u31"}}});