$axure.loadCurrentPage({
  "url":"项目背景及目标.html",
  "generationDate":new Date(1405078988357.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b142fc8e18264c01af1ca8d4ae266163",
    "type":"Axure:Page",
    "name":"项目背景及目标",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2d7b9b5afec429baa2118897c813411",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "size":{
              "width":1340,
              "height":1122},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf2e27370e44aff8be3dc2b972f96f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":1340,
                  "height":1122},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目背景及目标/u0.png"}},
{
          "id":"34be4639c1e54ac2bf6570d1281ca6cd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":71},
            "size":{
              "width":1256,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/项目背景及目标/u2_line.png"}},
{
          "id":"d88dd38d34d74a058ff1f53809539dc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":1167,
              "y":1020},
            "size":{
              "width":133,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ecd3c1af4174f5a8d7a37a517f09107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":1167,
                  "y":1020},
                "size":{
                  "width":133,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目背景及目标/u3.png"}},
{
          "id":"471602c7511d441f9a659c02ab9a359b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":32,
              "y":12},
            "size":{
              "width":162,
              "height":42},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb3d7e35fcbc4f8da4dcb02229356483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":32,
                  "y":12},
                "size":{
                  "width":162,
                  "height":42},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目背景及目标/u5.png"}},
{
          "id":"35cc124f5eb14e87bfe02207903c9a2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF60CDCE,
              "opacity":1},
            "location":{
              "x":204,
              "y":17},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb0a602e43944bfe8de84a3fddf7b9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF60CDCE,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":17},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f2d7b9b5afec429baa2118897c813411":{
      "scriptId":"u0"},
    "bdf2e27370e44aff8be3dc2b972f96f8":{
      "scriptId":"u1"},
    "34be4639c1e54ac2bf6570d1281ca6cd":{
      "scriptId":"u2"},
    "d88dd38d34d74a058ff1f53809539dc8":{
      "scriptId":"u3"},
    "3ecd3c1af4174f5a8d7a37a517f09107":{
      "scriptId":"u4"},
    "471602c7511d441f9a659c02ab9a359b":{
      "scriptId":"u5"},
    "fb3d7e35fcbc4f8da4dcb02229356483":{
      "scriptId":"u6"},
    "35cc124f5eb14e87bfe02207903c9a2f":{
      "scriptId":"u7"},
    "eb0a602e43944bfe8de84a3fddf7b9e5":{
      "scriptId":"u8"}}});