$axure.loadCurrentPage({
  "url":"封面.html",
  "generationDate":new Date(1405078988245.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"643b259dc0c6415591e1301b246da5b6",
    "type":"Axure:Page",
    "name":"封面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c14d9263611b462e90bb50588a771997",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "size":{
              "width":1344,
              "height":950}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d540c197c2e14a33b2bfd682b272e956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "size":{
                  "width":1344,
                  "height":950}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/封面/u0.png"}},
{
          "id":"53f678c0ee414904a68e523af5462f61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":514,
              "y":127},
            "size":{
              "width":453,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cb40b19ae814729866250d3e07723c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":514,
                  "y":127},
                "size":{
                  "width":453,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fff90263bf6c423b93e704ae7705ab01",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":511,
              "y":202},
            "size":{
              "width":860,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb90efc9758b4f1abfc41839e38df0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":511,
                  "y":202},
                "size":{
                  "width":860,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c14d9263611b462e90bb50588a771997":{
      "scriptId":"u0"},
    "d540c197c2e14a33b2bfd682b272e956":{
      "scriptId":"u1"},
    "53f678c0ee414904a68e523af5462f61":{
      "scriptId":"u2"},
    "5cb40b19ae814729866250d3e07723c5":{
      "scriptId":"u3"},
    "fff90263bf6c423b93e704ae7705ab01":{
      "scriptId":"u4"},
    "bb90efc9758b4f1abfc41839e38df0f2":{
      "scriptId":"u5"}}});