$axure.loadCurrentPage({
  "url":"金融.html",
  "generationDate":new Date(1406213761836.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"becaf0659034474daa991b047eb2e025",
    "type":"Axure:Page",
    "name":"金融",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f3ee1ee56844fd18f0903145be6a5bb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"7c1904ce4caa4b5890380b2241f12554"},
{
          "id":"24b0a055cdc749908597df2fe3958c36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":222,
              "y":239},
            "size":{
              "width":300,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81800be9e3e141babe809b1e7e95d4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":222,
                  "y":239},
                "size":{
                  "width":300,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u15.png"}},
{
          "id":"49d051c226d44f079feb57053e7a270c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":263},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e706231997eb4978a8630a9357f21f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":263},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u17.png"}},
{
          "id":"b606dea0775f4996bca165f061be4a9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CC33},
            "location":{
              "x":383,
              "y":315},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"962a98cbc3b34b84a1bc9d83ca8d8f7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CC33},
                "location":{
                  "x":383,
                  "y":315},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u19.png"}},
{
          "id":"e139b1da4840415f8ca3bfb9f014b924",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CC33},
            "location":{
              "x":317,
              "y":315},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b88caa3ff774157951e6ff90432cc1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CC33},
                "location":{
                  "x":317,
                  "y":315},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u19.png"}},
{
          "id":"48530d4abf2b47db81758a21a08337d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF99CC33},
            "location":{
              "x":449,
              "y":315},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f72546d8a0541f1970f46fa7e72e2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CC33},
                "location":{
                  "x":449,
                  "y":315},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u19.png"}},
{
          "id":"138e89b481464d9c81bd8b71a56cf0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":317,
              "y":273},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF99CCFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8af3bf217e4af2aec719885b21389e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":317,
                  "y":273},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u25.png"}},
{
          "id":"bd48a2187a524819882658bd02fdced1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCCC},
            "location":{
              "x":383,
              "y":273},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF99CCFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57a27349e5c455da1889e764a0297d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC},
                "location":{
                  "x":383,
                  "y":273},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u25.png"}},
{
          "id":"01a8371183d5485494a8b839ee99bd63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Regular', '幼圆'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009999,
              "opacity":1},
            "location":{
              "x":239,
              "y":275},
            "size":{
              "width":84,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ced33b041c044e3ac8d767e456c255b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Regular', '幼圆'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009999,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":275},
                "size":{
                  "width":84,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20c8a97a396346ddb0f74b1a1d93bd51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Regular', '幼圆'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999900,
              "opacity":1},
            "location":{
              "x":239,
              "y":317},
            "size":{
              "width":84,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b3df7407d8418e981458a209f2567b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Regular', '幼圆'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999900,
                  "opacity":1},
                "location":{
                  "x":239,
                  "y":317},
                "size":{
                  "width":84,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efaf7c4cfba044909f5621760b261b7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":299},
            "size":{
              "width":259,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u33_line.png"}},
{
          "id":"fea9d90b248c4637858d173de113c1e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "location":{
              "x":238,
              "y":244},
            "size":{
              "width":150,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e99a201c85d04019957b33a1122df8ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "location":{
                  "x":238,
                  "y":244},
                "size":{
                  "width":150,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"995a604d077e49138454a082bb481d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":211,
              "y":131},
            "size":{
              "width":320,
              "height":99},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08fec0c8dd64017a1f28bc8384823b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":211,
                  "y":131},
                "size":{
                  "width":320,
                  "height":99},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u36.png"}},
{
          "id":"b0437b594cc146309cb8fa2262f2f390",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":132},
            "size":{
              "width":270,
              "height":96},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ebfa47001e43bf9ef5dde690935949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":132},
                "size":{
                  "width":270,
                  "height":96},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u38.png"}},
{
          "id":"6a4176097c05429f957554d00a6b9e06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xDBBCBCBC},
            "location":{
              "x":212,
              "y":194},
            "size":{
              "width":82,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9a4a42083e4495cbdade03fdde6e469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xDBBCBCBC},
                "location":{
                  "x":212,
                  "y":194},
                "size":{
                  "width":82,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u40.png"}},
{
          "id":"51cc96feb83a43c4b143ce5116e7f598",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":131},
            "size":{
              "width":43,
              "height":99},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0549bdd3d61a4c32af4f13da98804e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":131},
                "size":{
                  "width":43,
                  "height":99},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u42.png"}},
{
          "id":"4d2cdd7d445a41e087953df2342470d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7A333333},
            "location":{
              "x":489,
              "y":131},
            "size":{
              "width":42,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760da23c917941dfb2a23653bd0ce907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7A333333},
                "location":{
                  "x":489,
                  "y":131},
                "size":{
                  "width":42,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u44.png"}},
{
          "id":"1037f08822e048ec98e314d4ed8556ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xC4FFFFFF},
            "location":{
              "x":390,
              "y":207},
            "size":{
              "width":90,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6649d75ea0db453da2f90df294be00c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xC4FFFFFF},
                "location":{
                  "x":390,
                  "y":207},
                "size":{
                  "width":90,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u46.png"}},
{
          "id":"4595cafd41e0407eb6c6b1a1abaa1163",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":221,
              "y":403},
            "size":{
              "width":300,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7fea183e71468a970b43babdf657a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":221,
                  "y":403},
                "size":{
                  "width":300,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u15.png"}},
{
          "id":"054bff23c44a4236b43bf66938962821",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":428},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91529b1e312c498299ad4c20c7a6eb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":428},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u50.png"}},
{
          "id":"7132107c524b497abfec97e8519e12dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "location":{
              "x":236,
              "y":408},
            "size":{
              "width":150,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c348d7829f54301bcf946b0408f8db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "location":{
                  "x":236,
                  "y":408},
                "size":{
                  "width":150,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9df750b5ac664eba93a5d367d01bbb4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":236,
              "y":443},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2e74506ab24e889dedfce637c0145d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":236,
                  "y":443},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb5e56d9a9064d20b1642d31a6abae93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":433},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"002853883e1047eabc71a0bbb15c8a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":433},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"e4181cd9ae184fee8a582d52705c7cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":353},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d74f4a3bf36a47358a3ef4eade814171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":353},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u50.png"}},
{
          "id":"696aba12ed9a4f2f92cf63ec3cf9366e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":234,
              "y":362},
            "size":{
              "width":106,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2030d97c9ab9498a817fa4e881ebd867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":362},
                "size":{
                  "width":106,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c07b21c148464e91ad446f7ea9bb39ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":357},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd29b3e130884763b329297f58d97f2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":357},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"b7983219b94e4926a9225908374976f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":468},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b3cb471e904d9b9d1c1226b676ff3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":468},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u50.png"}},
{
          "id":"bf0fd5c9bb964887911c2f84f6170ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":236,
              "y":483},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5dfd1ae3e16494f88481bde8bde7cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":236,
                  "y":483},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07c855332e4047c0bb514bc3aec0d719",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":473},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a57b88221df642d1bb3b1dc5ae000db2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":473},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"f17664cf487c4035bef83c79f3dd2313",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":508},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f833318ba1574cabba439bea87d24b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":508},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u50.png"}},
{
          "id":"b6fc59bdf7234866b07171f659fc9339",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":236,
              "y":523},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1b98f2bee9849bc968938a1e49c2e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":236,
                  "y":523},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f48546acf6974dbab270550bd618f032",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":513},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aca2e150ebb4a15a0969a5618b1b98e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":513},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"ee00294a9386495b80ba975b66cd468f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83732d45b5174ab7b5f4f6bb72752b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"5ce819d2cbca43f78d42d845726f131e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"435e14bdbbb849838ffb0acd981d95cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"5643c06198b04a0e9e64627f31329e20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23553e5155bc4f788feba3e7da450380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"fd7c676790e143b3b8c23fde0ea9aec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":532},
            "size":{
              "width":366,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93b6b7a50ac41c98fe0c3c52dae389d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":532},
                "size":{
                  "width":366,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u82.png"}},
{
          "id":"71d25ef6f5054bcabbcf5a79b2d45a5d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":526},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融/u84_line.png"}},
{
          "id":"882a2333b8b645daa900071321686b44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":266,
              "y":68},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bec811fde5e45b78ad753ca2ae92ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":266,
                  "y":68},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32426772b521428e9de481be1ee25ad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":211,
              "y":100},
            "size":{
              "width":422,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044f5b60b77f4a0080f616c97a1c51c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":211,
                  "y":100},
                "size":{
                  "width":422,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u200.png"}},
{
          "id":"b859df9e1087406aab72b391013ad662",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":124},
            "size":{
              "width":49,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机客户端-首页/u202_line.png"}},
{
          "id":"f49fbab08f4844659b8225e94889e3cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":213,
              "y":108},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"101b7da3ca40438fb8c70a90720776d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":213,
                  "y":108},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01b7e0e5f65e436bb797edc3f903ffb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCCC,
              "opacity":1},
            "location":{
              "x":282,
              "y":108},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b078f93a69be4e0daf290e81a39778c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCCC,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":108},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad26e191d653431fa4f81a337769d024",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":108},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e66a78507a24b45aae118a17a45153a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":108},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d8375dcda7846fd90bf360d2813b5d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":419,
              "y":108},
            "size":{
              "width":65,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef49b87e128d4bb39a4540f8b6238429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":108},
                "size":{
                  "width":65,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02f19913422449678f2a28d1b9578f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":494,
              "y":108},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6c5ec4775a4c0abf54967331ede38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":108},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02a4f4288c9c43a6ab4cef7e2eb150ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":563,
              "y":108},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2677f206ba545618c6fd6f0c05c63a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":563,
                  "y":108},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7616b2417804c53a2487b91e98f1ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":82},
            "size":{
              "width":110,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d46b01c4ddf9453d94d7b3c30184679a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":82},
                "size":{
                  "width":110,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u288.png"}}]}},
  "masters":{
    "7c1904ce4caa4b5890380b2241f12554":{
      "packageId":"7c1904ce4caa4b5890380b2241f12554",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFBFBFB},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFBFBFB},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"c6ba21344436449d8cdb71dea55810ad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":291,
                "y":14},
              "size":{
                "width":32,
                "height":23},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c18977bb9a54a6f9f8c52410e4be0c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":291,
                    "y":14},
                  "size":{
                    "width":32,
                    "height":23},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u48.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":8},
              "size":{
                "width":34,
                "height":34},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":8},
                  "size":{
                    "width":34,
                    "height":34},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u50.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":8},
              "size":{
                "width":34,
                "height":34},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":8},
                  "size":{
                    "width":34,
                    "height":34},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u50.png"}},
{
            "id":"5f1e48413d0e4df7a484372fb98a2963",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":33,
                "y":10},
              "size":{
                "width":30,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"79062460918a46d8b2195c5ce5074dd4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":33,
                    "y":10},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u54.png"}},
{
            "id":"26729e08301a4bc3a5717e73f92192cb",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":291,
                "y":14},
              "size":{
                "width":32,
                "height":23},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa504518274a4cdb93177503024602cb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":291,
                    "y":14},
                  "size":{
                    "width":32,
                    "height":23},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u48.png"}}]}}},
  "objectPaths":{
    "7f3ee1ee56844fd18f0903145be6a5bb":{
      "scriptId":"u0",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u1"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u2"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u3"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u4"},
      "c6ba21344436449d8cdb71dea55810ad":{
        "scriptId":"u5"},
      "0c18977bb9a54a6f9f8c52410e4be0c0":{
        "scriptId":"u6"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u7"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u8"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u9"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u10"},
      "5f1e48413d0e4df7a484372fb98a2963":{
        "scriptId":"u11"},
      "79062460918a46d8b2195c5ce5074dd4":{
        "scriptId":"u12"},
      "26729e08301a4bc3a5717e73f92192cb":{
        "scriptId":"u13"},
      "aa504518274a4cdb93177503024602cb":{
        "scriptId":"u14"}},
    "24b0a055cdc749908597df2fe3958c36":{
      "scriptId":"u15"},
    "81800be9e3e141babe809b1e7e95d4a2":{
      "scriptId":"u16"},
    "49d051c226d44f079feb57053e7a270c":{
      "scriptId":"u17"},
    "e706231997eb4978a8630a9357f21f39":{
      "scriptId":"u18"},
    "b606dea0775f4996bca165f061be4a9d":{
      "scriptId":"u19"},
    "962a98cbc3b34b84a1bc9d83ca8d8f7c":{
      "scriptId":"u20"},
    "e139b1da4840415f8ca3bfb9f014b924":{
      "scriptId":"u21"},
    "2b88caa3ff774157951e6ff90432cc1e":{
      "scriptId":"u22"},
    "48530d4abf2b47db81758a21a08337d1":{
      "scriptId":"u23"},
    "3f72546d8a0541f1970f46fa7e72e2c5":{
      "scriptId":"u24"},
    "138e89b481464d9c81bd8b71a56cf0be":{
      "scriptId":"u25"},
    "dd8af3bf217e4af2aec719885b21389e":{
      "scriptId":"u26"},
    "bd48a2187a524819882658bd02fdced1":{
      "scriptId":"u27"},
    "c57a27349e5c455da1889e764a0297d8":{
      "scriptId":"u28"},
    "01a8371183d5485494a8b839ee99bd63":{
      "scriptId":"u29"},
    "3ced33b041c044e3ac8d767e456c255b":{
      "scriptId":"u30"},
    "20c8a97a396346ddb0f74b1a1d93bd51":{
      "scriptId":"u31"},
    "31b3df7407d8418e981458a209f2567b":{
      "scriptId":"u32"},
    "efaf7c4cfba044909f5621760b261b7e":{
      "scriptId":"u33"},
    "fea9d90b248c4637858d173de113c1e6":{
      "scriptId":"u34"},
    "e99a201c85d04019957b33a1122df8ab":{
      "scriptId":"u35"},
    "995a604d077e49138454a082bb481d02":{
      "scriptId":"u36"},
    "f08fec0c8dd64017a1f28bc8384823b2":{
      "scriptId":"u37"},
    "b0437b594cc146309cb8fa2262f2f390":{
      "scriptId":"u38"},
    "85ebfa47001e43bf9ef5dde690935949":{
      "scriptId":"u39"},
    "6a4176097c05429f957554d00a6b9e06":{
      "scriptId":"u40"},
    "b9a4a42083e4495cbdade03fdde6e469":{
      "scriptId":"u41"},
    "51cc96feb83a43c4b143ce5116e7f598":{
      "scriptId":"u42"},
    "0549bdd3d61a4c32af4f13da98804e68":{
      "scriptId":"u43"},
    "4d2cdd7d445a41e087953df2342470d6":{
      "scriptId":"u44"},
    "760da23c917941dfb2a23653bd0ce907":{
      "scriptId":"u45"},
    "1037f08822e048ec98e314d4ed8556ba":{
      "scriptId":"u46"},
    "6649d75ea0db453da2f90df294be00c9":{
      "scriptId":"u47"},
    "4595cafd41e0407eb6c6b1a1abaa1163":{
      "scriptId":"u48"},
    "8d7fea183e71468a970b43babdf657a1":{
      "scriptId":"u49"},
    "054bff23c44a4236b43bf66938962821":{
      "scriptId":"u50"},
    "91529b1e312c498299ad4c20c7a6eb85":{
      "scriptId":"u51"},
    "7132107c524b497abfec97e8519e12dc":{
      "scriptId":"u52"},
    "2c348d7829f54301bcf946b0408f8db3":{
      "scriptId":"u53"},
    "9df750b5ac664eba93a5d367d01bbb4d":{
      "scriptId":"u54"},
    "0f2e74506ab24e889dedfce637c0145d":{
      "scriptId":"u55"},
    "eb5e56d9a9064d20b1642d31a6abae93":{
      "scriptId":"u56"},
    "002853883e1047eabc71a0bbb15c8a2c":{
      "scriptId":"u57"},
    "e4181cd9ae184fee8a582d52705c7cbd":{
      "scriptId":"u58"},
    "d74f4a3bf36a47358a3ef4eade814171":{
      "scriptId":"u59"},
    "696aba12ed9a4f2f92cf63ec3cf9366e":{
      "scriptId":"u60"},
    "2030d97c9ab9498a817fa4e881ebd867":{
      "scriptId":"u61"},
    "c07b21c148464e91ad446f7ea9bb39ca":{
      "scriptId":"u62"},
    "bd29b3e130884763b329297f58d97f2c":{
      "scriptId":"u63"},
    "b7983219b94e4926a9225908374976f7":{
      "scriptId":"u64"},
    "d4b3cb471e904d9b9d1c1226b676ff3f":{
      "scriptId":"u65"},
    "bf0fd5c9bb964887911c2f84f6170ed8":{
      "scriptId":"u66"},
    "a5dfd1ae3e16494f88481bde8bde7cbf":{
      "scriptId":"u67"},
    "07c855332e4047c0bb514bc3aec0d719":{
      "scriptId":"u68"},
    "a57b88221df642d1bb3b1dc5ae000db2":{
      "scriptId":"u69"},
    "f17664cf487c4035bef83c79f3dd2313":{
      "scriptId":"u70"},
    "f833318ba1574cabba439bea87d24b8e":{
      "scriptId":"u71"},
    "b6fc59bdf7234866b07171f659fc9339":{
      "scriptId":"u72"},
    "c1b98f2bee9849bc968938a1e49c2e67":{
      "scriptId":"u73"},
    "f48546acf6974dbab270550bd618f032":{
      "scriptId":"u74"},
    "3aca2e150ebb4a15a0969a5618b1b98e":{
      "scriptId":"u75"},
    "ee00294a9386495b80ba975b66cd468f":{
      "scriptId":"u76"},
    "83732d45b5174ab7b5f4f6bb72752b4a":{
      "scriptId":"u77"},
    "5ce819d2cbca43f78d42d845726f131e":{
      "scriptId":"u78"},
    "435e14bdbbb849838ffb0acd981d95cd":{
      "scriptId":"u79"},
    "5643c06198b04a0e9e64627f31329e20":{
      "scriptId":"u80"},
    "23553e5155bc4f788feba3e7da450380":{
      "scriptId":"u81"},
    "fd7c676790e143b3b8c23fde0ea9aec7":{
      "scriptId":"u82"},
    "f93b6b7a50ac41c98fe0c3c52dae389d":{
      "scriptId":"u83"},
    "71d25ef6f5054bcabbcf5a79b2d45a5d":{
      "scriptId":"u84"},
    "882a2333b8b645daa900071321686b44":{
      "scriptId":"u85"},
    "4bec811fde5e45b78ad753ca2ae92ad6":{
      "scriptId":"u86"},
    "32426772b521428e9de481be1ee25ad5":{
      "scriptId":"u87"},
    "044f5b60b77f4a0080f616c97a1c51c0":{
      "scriptId":"u88"},
    "b859df9e1087406aab72b391013ad662":{
      "scriptId":"u89"},
    "f49fbab08f4844659b8225e94889e3cc":{
      "scriptId":"u90"},
    "101b7da3ca40438fb8c70a90720776d7":{
      "scriptId":"u91"},
    "01b7e0e5f65e436bb797edc3f903ffb7":{
      "scriptId":"u92"},
    "b078f93a69be4e0daf290e81a39778c3":{
      "scriptId":"u93"},
    "ad26e191d653431fa4f81a337769d024":{
      "scriptId":"u94"},
    "2e66a78507a24b45aae118a17a45153a":{
      "scriptId":"u95"},
    "9d8375dcda7846fd90bf360d2813b5d8":{
      "scriptId":"u96"},
    "ef49b87e128d4bb39a4540f8b6238429":{
      "scriptId":"u97"},
    "02f19913422449678f2a28d1b9578f00":{
      "scriptId":"u98"},
    "9d6c5ec4775a4c0abf54967331ede38f":{
      "scriptId":"u99"},
    "02a4f4288c9c43a6ab4cef7e2eb150ee":{
      "scriptId":"u100"},
    "a2677f206ba545618c6fd6f0c05c63a4":{
      "scriptId":"u101"},
    "c7616b2417804c53a2487b91e98f1ab3":{
      "scriptId":"u102"},
    "d46b01c4ddf9453d94d7b3c30184679a":{
      "scriptId":"u103"}}});