$axure.loadCurrentPage({
  "url":"键盘.html",
  "generationDate":new Date(1406213751341.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3309067a31984aa7a43157b5129eb8ff",
    "type":"Axure:Page",
    "name":"键盘",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e8d8416a9d9473eb87e6efb9bd2d64b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"a865755f66154dee8e7e6c9753e330c1"},
{
          "id":"f0dec60429544a0ebbf5dfea84097db2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":100,
              "y":73},
            "size":{
              "width":395,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02cb930fd4224a9491aaf933e93880ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":73},
                "size":{
                  "width":395,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"939ecdc554414241b2b950bd813bc9ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":107,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77c1849c1114c39ab0eb8243fae44cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":107,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"6dc7fb6b46fb4bbca2cd1bcd071908ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":197,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdea92f63c574e9e824bc9dc9bb49a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":197,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"d788e5c5f87b46b6bf506d33db6c474b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":365,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53bc0bf76912433f8edfc00c4c907703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":365,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"d3a307c16f544f24b1e807c7cdb19699",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":160},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/通话记录/u319_line.png"}},
{
          "id":"6aad6e2849ef45939fee7f9980f8e160",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":258},
            "size":{
              "width":320,
              "height":322},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba685425e91e4e478f7ba17bcc03a0b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":258},
                "size":{
                  "width":320,
                  "height":322},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u31.png"}},
{
          "id":"52f6175d2484465399ee85c2ba35aff2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":259},
            "size":{
              "width":124,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e5d491929a4825826925d6005379b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":259},
                "size":{
                  "width":124,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u181.png"}},
{
          "id":"59ac82ca193f48d5b701f1581072a3c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":389},
            "size":{
              "width":124,
              "height":63},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9153a07b612542a18d69405b03048d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":389},
                "size":{
                  "width":124,
                  "height":63},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u183.png"}},
{
          "id":"1158bba25a854288895fa914e929aaba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":99,
              "y":167},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a60ea35dea9047af93325a73d24c97ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":99,
                  "y":167},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u37.png"}},
{
          "id":"5662111595414a4b859812f492920c31",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":100},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"a865755f66154dee8e7e6c9753e330c1"},
{
          "id":"acf893910c4d48c8813296c6b573b142",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":258},
            "size":{
              "width":320,
              "height":322},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04dd57fe30684f168c498050b40d9002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":258},
                "size":{
                  "width":320,
                  "height":322},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u31.png"}},
{
          "id":"2152e22a1a074d15bf0d97342c868082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":503,
              "y":167},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8c8ad7a052485a8712d5b2de7f68ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":503,
                  "y":167},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u37.png"}},
{
          "id":"fe4df97f627041bc83c146d1d3aa35b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":644,
              "y":183},
            "size":{
              "width":75,
              "height":42},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bb56c18e4d46d8925b6ec5818beb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":644,
                  "y":183},
                "size":{
                  "width":75,
                  "height":42},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7842258e7f3e439596fc15abb540d155",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":223},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb86b5054b694b44b3626ce17425a5f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":503,
                  "y":223},
                "size":{
                  "width":320,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u67.png"}},
{
          "id":"14270f2f9fe74dbc8ae68d7a05fbf3a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":227},
            "size":{
              "width":33,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ec120685e242d5bf5622b50cca1594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":227},
                "size":{
                  "width":33,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u69.png"}},
{
          "id":"f76b5e34b8ed47d38de5e5c17efe4d1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":228},
            "size":{
              "width":129,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12415c80d7c4a9ba7d46a0db8aae93d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":228},
                "size":{
                  "width":129,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u71.png"}},
{
          "id":"6ab1b3ca5ba348deb51b71f861851435",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":555,
              "y":244},
            "size":{
              "width":129,
              "height":11},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e0e012cf71d4a6d9d19ecb7fc6caf9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":555,
                  "y":244},
                "size":{
                  "width":129,
                  "height":11},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u73.png"}},
{
          "id":"7327605daea543e0b03703ae0a8d7f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4BC2A8},
            "location":{
              "x":801,
              "y":236},
            "size":{
              "width":12,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70bdc7228e074d9cab5ce6ee583177fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4BC2A8},
                "location":{
                  "x":801,
                  "y":236},
                "size":{
                  "width":12,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u81.png"}},
{
          "id":"6f1b8f3d4c64405e8fede13e3c5322aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4BC2A8,
              "opacity":1},
            "location":{
              "x":785,
              "y":230},
            "size":{
              "width":14,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8c162d1cef495193ce1bc10ecf0658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4BC2A8,
                  "opacity":1},
                "location":{
                  "x":785,
                  "y":230},
                "size":{
                  "width":14,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28036dbfb0ab46ef82f27fe18c6d19e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":858,
              "y":235},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44002c06c2ee4ba8a0815dc57cd5d6bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":858,
                  "y":235},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd206ef0d82a42e2a5f7d199d48fa768",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":630},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"a865755f66154dee8e7e6c9753e330c1"},
{
          "id":"e0aa01653666418e9b12f3cd95bf2d80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":511,
              "y":657},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1adea9dde894b41adb18023d4f8e0e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":511,
                  "y":657},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"006de551f04d4618b01ba5b4bff7f5dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":599,
              "y":657},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77c8f7f945c84298aa0e51ca48b79fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":599,
                  "y":657},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"1c37c78ac67f45ab9e229ad81e36b566",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":769,
              "y":657},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b21988ca2a84492a87b0c32eaf838a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":769,
                  "y":657},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"a9b3ccd98670463faed33b546f67a7e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":663,
              "y":690},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/通话记录/u319_line.png"}},
{
          "id":"3349652686d64098ad7c3b921951e162",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":788},
            "size":{
              "width":320,
              "height":322},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a984d50f4a5940a9bb48eb2437f3db0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":788},
                "size":{
                  "width":320,
                  "height":322},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u31.png"}},
{
          "id":"0bf335a862a04c6da37d5050e8216e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":503,
              "y":697},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd4872d7fc7422b91a1a08cfaae4002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":503,
                  "y":697},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u37.png"}},
{
          "id":"a6cfdfe725624222aacb4fb32f2b40eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":644,
              "y":713},
            "size":{
              "width":75,
              "height":42},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173dbf11eef545c2a3ca494642094662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":644,
                  "y":713},
                "size":{
                  "width":75,
                  "height":42},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13b82c0c99724c7a809b7f67b9318b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4BC2A8},
            "location":{
              "x":503,
              "y":753},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48c85943a6b4fdd841b2848521c2d72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4BC2A8},
                "location":{
                  "x":503,
                  "y":753},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u116.png"}},
{
          "id":"750565ff9d244e8d981d5cdfa1e20737",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":756},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca053dcc79ad47d99f41abb82a47abdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":756},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u118.png"}},
{
          "id":"0c92b5b95f5d49da9449fe5de2fc12ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":602,
              "y":756},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbe74d40fcc24a7caa17d2a93ab96cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":602,
                  "y":756},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u118.png"}},
{
          "id":"f79d5276764349078f53b4d86136ae87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":638,
              "y":762},
            "size":{
              "width":143,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e7949d5caf6482b8f9192d6473a1285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":762},
                "size":{
                  "width":143,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53afe9e2293541ffa9369720a03f2c2e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":238},
            "size":{
              "width":26,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/发起预约音频通话/u61_end.png",
            "line~":"images/键盘/u124_line.png"}},
{
          "id":"e7080af1feaf4c3382cbf7719cea3374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F333333},
            "location":{
              "x":1022,
              "y":121},
            "size":{
              "width":321,
              "height":459}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17fce1016c0345f9a08b67dae8d328ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F333333},
                "location":{
                  "x":1022,
                  "y":121},
                "size":{
                  "width":321,
                  "height":459}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u119.png"}},
{
          "id":"85cb24953a5d44b0a48bd461bb7f60b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFAFAF9},
            "location":{
              "x":1038,
              "y":138},
            "size":{
              "width":291,
              "height":368}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5604d3ce1846d3843ef8d8b042b045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFAFAF9},
                "location":{
                  "x":1038,
                  "y":138},
                "size":{
                  "width":291,
                  "height":368}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u127.png"}},
{
          "id":"c16100f8f1ff4038b5c160f4c507e449",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1049,
              "y":175},
            "size":{
              "width":208,
              "height":116},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f24130e73f449f8ec762d2689c4193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1049,
                  "y":175},
                "size":{
                  "width":208,
                  "height":116},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通话记录/u147.png"}},
{
          "id":"a0108a4a7a5843e4bdf1701d4f2a0857",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1257,
              "y":175},
            "size":{
              "width":63,
              "height":116},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"322995fbe8d74cd8937185b7493c3878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1257,
                  "y":175},
                "size":{
                  "width":63,
                  "height":116},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通话记录/u149.png"}},
{
          "id":"8fc4f61a84bc48f0a70600a67ea7a8eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1049,
              "y":295},
            "size":{
              "width":144,
              "height":110},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3080c3372f644aeaec4ee7045fe82e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1049,
                  "y":295},
                "size":{
                  "width":144,
                  "height":110},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通话记录/u151.png"}},
{
          "id":"2725dce06e98411fa022edb8c586bfcb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1193,
              "y":295},
            "size":{
              "width":127,
              "height":110},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f44093494a4a2d80f4e8e0484d1ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1193,
                  "y":295},
                "size":{
                  "width":127,
                  "height":110},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通话记录/u153.png"}},
{
          "id":"4e6c68cb6b30461cb67a2bc4ab1f3da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1038,
              "y":472},
            "size":{
              "width":291,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8cf4bcd5d494f7c8eeb1049428e015c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1038,
                  "y":472},
                "size":{
                  "width":291,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u137.png"}},
{
          "id":"18d07f5aa42042b2a447268281e9117d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":285},
            "size":{
              "width":270,
              "height":10},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edfa83187620410c8e86365d9356c4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":285},
                "size":{
                  "width":270,
                  "height":10},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通话记录/u173.png"}},
{
          "id":"f47c022d00234fba8af30db3220137cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4BC2A8},
            "location":{
              "x":1039,
              "y":138},
            "size":{
              "width":290,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d58fdb28acb486a9c9151cb1c50516a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4BC2A8},
                "location":{
                  "x":1039,
                  "y":138},
                "size":{
                  "width":290,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u141.png"}},
{
          "id":"dd814f507ba341d282a7970b639cdb4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":514,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5faadd9ca58c47f2bf3fbece55108425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":514,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"b5a56d100dc3472a86aeeadd78ef8783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":604,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978ff74612f140c89c18c2a24f78d8d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":604,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"38534fe4ea72423cb63cba8b961bfd15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FE8E7E2},
            "location":{
              "x":772,
              "y":127},
            "size":{
              "width":50,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165e1d1ebb6849d4ae2d4a10d7a0d6dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FE8E7E2},
                "location":{
                  "x":772,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起预约音频通话/u243.png"}},
{
          "id":"1997a694f2bc446bbc8bf14989096ff7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":663,
              "y":160},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/通话记录/u319_line.png"}},
{
          "id":"ded0077ddd2444a796c9cffe66a28566",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":100,
              "y":600},
            "size":{
              "width":320,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7d6549e20e4c099a4a3347ba020d56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":600},
                "size":{
                  "width":320,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99bf02ad2ee34bd6ac15a5461f1c0dfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1C3143},
            "location":{
              "x":314,
              "y":516},
            "size":{
              "width":105,
              "height":63},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bd8e0ae8f2143e5940ade7a3eff842d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C3143},
                "location":{
                  "x":314,
                  "y":516},
                "size":{
                  "width":105,
                  "height":63},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u152.png"}},
{
          "id":"2f8b3ec5382243d39a0224326321fc18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":530},
            "size":{
              "width":51,
              "height":34},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ced5cf9e2294a119ae4554d25d18f07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":530},
                "size":{
                  "width":51,
                  "height":34},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u154.png"}},
{
          "id":"ee398465d1ac445ebf77de38e6a8c9bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1C3143},
            "location":{
              "x":206,
              "y":516},
            "size":{
              "width":107,
              "height":63},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"291bc438fc264f1d862d997e9005f825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C3143},
                "location":{
                  "x":206,
                  "y":516},
                "size":{
                  "width":107,
                  "height":63},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u156.png"}},
{
          "id":"7e3f387f8f574503b81ad3a2000af395",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1C3143},
            "location":{
              "x":100,
              "y":516},
            "size":{
              "width":105,
              "height":63},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a4ad15f82b4c979f44fad71d0723bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C3143},
                "location":{
                  "x":100,
                  "y":516},
                "size":{
                  "width":105,
                  "height":63},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u152.png"}},
{
          "id":"958cccc91db2492e989b2d8555223cb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":522},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471b75dccd5e4006aaa498618161a057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":522},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u705.png"}},
{
          "id":"f1841dbc1ace4efdb64f0e9c840a6b0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":522},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88078ff2f87348feb6e16c175de3599d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":522},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u705.png"}},
{
          "id":"9f4aceb941a646ae9fc039e9e625a9e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":522},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c719213237354bd5b132d6d3115a0543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":522},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u709.png"}},
{
          "id":"4d2ccc251fca4161a16b1987f4dfedc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":522},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b80efd4b354d79839899df9bda2c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":522},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起即时通话/u709.png"}},
{
          "id":"70ee602b433b4e41a8c0e27b740ab793",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":514},
            "size":{
              "width":321,
              "height":66},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"048c51758d164d1280ea185b8c4c0279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":514},
                "size":{
                  "width":321,
                  "height":66},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u168.png"}},
{
          "id":"9600cfbdeb874c09ab475595a4b10fc3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":1044},
            "size":{
              "width":321,
              "height":66},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f48cf70b0354d22b48e552bd1d7c0fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":1044},
                "size":{
                  "width":321,
                  "height":66},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/键盘/u168.png"}}]}},
  "masters":{
    "a865755f66154dee8e7e6c9753e330c1":{
      "packageId":"a865755f66154dee8e7e6c9753e330c1",
      "type":"Axure:Master",
      "name":"back ground",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5941aae518cb4c43b78ae2f9f2a187ba",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFAFAF9},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eefe1eb107924d27a417efc4e71afec0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFAFAF9},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u0.png",
              "normal~":"images/登录/u0.png",
              "normal~":"images/登录/u0.png"}},
{
            "id":"729151b4e14b4d5a80f7f2f3b91a5113",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":321,
                "height":22},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"afab24f4666e48d89960af8f7c7f6e41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":321,
                    "height":22},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u2.png",
              "normal~":"images/登录/u2.png",
              "normal~":"images/登录/u2.png"}},
{
            "id":"d02ec7b02ba5481b96e26750a53657f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE8E7E2},
              "location":{
                "x":0,
                "y":22},
              "size":{
                "width":320,
                "height":44},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac1d404488064979afafa7a859663c5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE8E7E2},
                  "location":{
                    "x":0,
                    "y":22},
                  "size":{
                    "width":320,
                    "height":44},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u78.png",
              "normal~":"images/注册/u78.png",
              "normal~":"images/注册/u78.png"}},
{
            "id":"7544cf4b87704d14afd0889ed892fdd0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":23,
                "y":30},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2eb3f2d7834448cfab5bcf58c60ba048",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":23,
                    "y":30},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/发起预约音频通话/u227.png",
              "normal~":"images/发起预约音频通话/u227.png",
              "normal~":"images/发起预约音频通话/u227.png"}},
{
            "id":"2fd91fd729ac416a92a4fb3a5a776bd9",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":75,
                "y":34},
              "size":{
                "width":10,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png"}},
{
            "id":"f09d3ecf281a4a98a4e3f62e41dbda36",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":106,
                "y":28},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e269719dc367487e91e039ed922eafb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":106,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/发起预约音频通话/u230.png",
              "normal~":"images/发起预约音频通话/u230.png",
              "normal~":"images/发起预约音频通话/u230.png"}},
{
            "id":"1a296f563d074117b9aa3d487fc135fc",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":155,
                "y":34},
              "size":{
                "width":10,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png"}},
{
            "id":"27ba96cce52e4d7db4f81ea3df109e98",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFF2F2F2},
{
                    "color":0xFFF2F2F2},
{
                    "color":0xFFD7D7D7},
{
                    "color":0xFFD7D7D7}]},
              "location":{
                "x":0,
                "y":67},
              "size":{
                "width":320,
                "height":1},
              "borderFill":{
                "fillType":"solid",
                "color":0x7FFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"34dbb5bd3bb24073bab9d267774bbb90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFF2F2F2},
{
                        "color":0xFFF2F2F2},
{
                        "color":0xFFD7D7D7},
{
                        "color":0xFFD7D7D7}]},
                  "location":{
                    "x":0,
                    "y":67},
                  "size":{
                    "width":320,
                    "height":1},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x7FFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u80.png",
              "normal~":"images/注册/u80.png",
              "normal~":"images/注册/u80.png"}},
{
            "id":"878c60dbec5f4ad88c2dbfdf742a3499",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":234,
                "y":34},
              "size":{
                "width":10,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/发起预约音频通话/u229_line.png"}},
{
            "id":"93476c03dd584ff2862684fa6a2d9d77",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":265,
                "y":30},
              "size":{
                "width":28,
                "height":28},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8bdd6ec163d4486959d1f3c75e31c28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":265,
                    "y":30},
                  "size":{
                    "width":28,
                    "height":28},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/发起预约音频通话/u236.png",
              "normal~":"images/发起预约音频通话/u236.png",
              "normal~":"images/发起预约音频通话/u236.png"}},
{
            "id":"dec52cb8114f4d80a378669ee8fd1abf",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":186,
                "y":28},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f98b052ace3475b9dda8b4f41d800fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":186,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/发起预约音频通话/u238.png",
              "normal~":"images/发起预约音频通话/u238.png",
              "normal~":"images/发起预约音频通话/u238.png"}},
{
            "id":"2c5bc93e287e4c529e7c54f858ebb9db",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":39,
                "y":29},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90",
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad753399440b469a804c54767913b57e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":39,
                    "y":29},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90",
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/发起预约音频通话/u240.png",
              "normal~":"images/发起预约音频通话/u240.png",
              "normal~":"images/发起预约音频通话/u240.png"}}]}}},
  "objectPaths":{
    "1e8d8416a9d9473eb87e6efb9bd2d64b":{
      "scriptId":"u0",
      "5941aae518cb4c43b78ae2f9f2a187ba":{
        "scriptId":"u1"},
      "eefe1eb107924d27a417efc4e71afec0":{
        "scriptId":"u2"},
      "729151b4e14b4d5a80f7f2f3b91a5113":{
        "scriptId":"u3"},
      "afab24f4666e48d89960af8f7c7f6e41":{
        "scriptId":"u4"},
      "d02ec7b02ba5481b96e26750a53657f6":{
        "scriptId":"u5"},
      "ac1d404488064979afafa7a859663c5d":{
        "scriptId":"u6"},
      "7544cf4b87704d14afd0889ed892fdd0":{
        "scriptId":"u7"},
      "2eb3f2d7834448cfab5bcf58c60ba048":{
        "scriptId":"u8"},
      "2fd91fd729ac416a92a4fb3a5a776bd9":{
        "scriptId":"u9"},
      "f09d3ecf281a4a98a4e3f62e41dbda36":{
        "scriptId":"u10"},
      "e269719dc367487e91e039ed922eafb0":{
        "scriptId":"u11"},
      "1a296f563d074117b9aa3d487fc135fc":{
        "scriptId":"u12"},
      "27ba96cce52e4d7db4f81ea3df109e98":{
        "scriptId":"u13"},
      "34dbb5bd3bb24073bab9d267774bbb90":{
        "scriptId":"u14"},
      "878c60dbec5f4ad88c2dbfdf742a3499":{
        "scriptId":"u15"},
      "93476c03dd584ff2862684fa6a2d9d77":{
        "scriptId":"u16"},
      "d8bdd6ec163d4486959d1f3c75e31c28":{
        "scriptId":"u17"},
      "dec52cb8114f4d80a378669ee8fd1abf":{
        "scriptId":"u18"},
      "7f98b052ace3475b9dda8b4f41d800fe":{
        "scriptId":"u19"},
      "2c5bc93e287e4c529e7c54f858ebb9db":{
        "scriptId":"u20"},
      "ad753399440b469a804c54767913b57e":{
        "scriptId":"u21"}},
    "f0dec60429544a0ebbf5dfea84097db2":{
      "scriptId":"u22"},
    "02cb930fd4224a9491aaf933e93880ed":{
      "scriptId":"u23"},
    "939ecdc554414241b2b950bd813bc9ca":{
      "scriptId":"u24"},
    "d77c1849c1114c39ab0eb8243fae44cc":{
      "scriptId":"u25"},
    "6dc7fb6b46fb4bbca2cd1bcd071908ee":{
      "scriptId":"u26"},
    "cdea92f63c574e9e824bc9dc9bb49a72":{
      "scriptId":"u27"},
    "d788e5c5f87b46b6bf506d33db6c474b":{
      "scriptId":"u28"},
    "53bc0bf76912433f8edfc00c4c907703":{
      "scriptId":"u29"},
    "d3a307c16f544f24b1e807c7cdb19699":{
      "scriptId":"u30"},
    "6aad6e2849ef45939fee7f9980f8e160":{
      "scriptId":"u31"},
    "ba685425e91e4e478f7ba17bcc03a0b0":{
      "scriptId":"u32"},
    "52f6175d2484465399ee85c2ba35aff2":{
      "scriptId":"u33"},
    "67e5d491929a4825826925d6005379b5":{
      "scriptId":"u34"},
    "59ac82ca193f48d5b701f1581072a3c2":{
      "scriptId":"u35"},
    "9153a07b612542a18d69405b03048d5d":{
      "scriptId":"u36"},
    "1158bba25a854288895fa914e929aaba":{
      "scriptId":"u37"},
    "a60ea35dea9047af93325a73d24c97ee":{
      "scriptId":"u38"},
    "5662111595414a4b859812f492920c31":{
      "scriptId":"u39",
      "5941aae518cb4c43b78ae2f9f2a187ba":{
        "scriptId":"u40"},
      "eefe1eb107924d27a417efc4e71afec0":{
        "scriptId":"u41"},
      "729151b4e14b4d5a80f7f2f3b91a5113":{
        "scriptId":"u42"},
      "afab24f4666e48d89960af8f7c7f6e41":{
        "scriptId":"u43"},
      "d02ec7b02ba5481b96e26750a53657f6":{
        "scriptId":"u44"},
      "ac1d404488064979afafa7a859663c5d":{
        "scriptId":"u45"},
      "7544cf4b87704d14afd0889ed892fdd0":{
        "scriptId":"u46"},
      "2eb3f2d7834448cfab5bcf58c60ba048":{
        "scriptId":"u47"},
      "2fd91fd729ac416a92a4fb3a5a776bd9":{
        "scriptId":"u48"},
      "f09d3ecf281a4a98a4e3f62e41dbda36":{
        "scriptId":"u49"},
      "e269719dc367487e91e039ed922eafb0":{
        "scriptId":"u50"},
      "1a296f563d074117b9aa3d487fc135fc":{
        "scriptId":"u51"},
      "27ba96cce52e4d7db4f81ea3df109e98":{
        "scriptId":"u52"},
      "34dbb5bd3bb24073bab9d267774bbb90":{
        "scriptId":"u53"},
      "878c60dbec5f4ad88c2dbfdf742a3499":{
        "scriptId":"u54"},
      "93476c03dd584ff2862684fa6a2d9d77":{
        "scriptId":"u55"},
      "d8bdd6ec163d4486959d1f3c75e31c28":{
        "scriptId":"u56"},
      "dec52cb8114f4d80a378669ee8fd1abf":{
        "scriptId":"u57"},
      "7f98b052ace3475b9dda8b4f41d800fe":{
        "scriptId":"u58"},
      "2c5bc93e287e4c529e7c54f858ebb9db":{
        "scriptId":"u59"},
      "ad753399440b469a804c54767913b57e":{
        "scriptId":"u60"}},
    "acf893910c4d48c8813296c6b573b142":{
      "scriptId":"u61"},
    "04dd57fe30684f168c498050b40d9002":{
      "scriptId":"u62"},
    "2152e22a1a074d15bf0d97342c868082":{
      "scriptId":"u63"},
    "ec8c8ad7a052485a8712d5b2de7f68ab":{
      "scriptId":"u64"},
    "fe4df97f627041bc83c146d1d3aa35b2":{
      "scriptId":"u65"},
    "23bb56c18e4d46d8925b6ec5818beb09":{
      "scriptId":"u66"},
    "7842258e7f3e439596fc15abb540d155":{
      "scriptId":"u67"},
    "eb86b5054b694b44b3626ce17425a5f6":{
      "scriptId":"u68"},
    "14270f2f9fe74dbc8ae68d7a05fbf3a4":{
      "scriptId":"u69"},
    "88ec120685e242d5bf5622b50cca1594":{
      "scriptId":"u70"},
    "f76b5e34b8ed47d38de5e5c17efe4d1b":{
      "scriptId":"u71"},
    "e12415c80d7c4a9ba7d46a0db8aae93d":{
      "scriptId":"u72"},
    "6ab1b3ca5ba348deb51b71f861851435":{
      "scriptId":"u73"},
    "1e0e012cf71d4a6d9d19ecb7fc6caf9f":{
      "scriptId":"u74"},
    "7327605daea543e0b03703ae0a8d7f04":{
      "scriptId":"u75"},
    "70bdc7228e074d9cab5ce6ee583177fc":{
      "scriptId":"u76"},
    "6f1b8f3d4c64405e8fede13e3c5322aa":{
      "scriptId":"u77"},
    "1c8c162d1cef495193ce1bc10ecf0658":{
      "scriptId":"u78"},
    "28036dbfb0ab46ef82f27fe18c6d19e8":{
      "scriptId":"u79"},
    "44002c06c2ee4ba8a0815dc57cd5d6bc":{
      "scriptId":"u80"},
    "dd206ef0d82a42e2a5f7d199d48fa768":{
      "scriptId":"u81",
      "5941aae518cb4c43b78ae2f9f2a187ba":{
        "scriptId":"u82"},
      "eefe1eb107924d27a417efc4e71afec0":{
        "scriptId":"u83"},
      "729151b4e14b4d5a80f7f2f3b91a5113":{
        "scriptId":"u84"},
      "afab24f4666e48d89960af8f7c7f6e41":{
        "scriptId":"u85"},
      "d02ec7b02ba5481b96e26750a53657f6":{
        "scriptId":"u86"},
      "ac1d404488064979afafa7a859663c5d":{
        "scriptId":"u87"},
      "7544cf4b87704d14afd0889ed892fdd0":{
        "scriptId":"u88"},
      "2eb3f2d7834448cfab5bcf58c60ba048":{
        "scriptId":"u89"},
      "2fd91fd729ac416a92a4fb3a5a776bd9":{
        "scriptId":"u90"},
      "f09d3ecf281a4a98a4e3f62e41dbda36":{
        "scriptId":"u91"},
      "e269719dc367487e91e039ed922eafb0":{
        "scriptId":"u92"},
      "1a296f563d074117b9aa3d487fc135fc":{
        "scriptId":"u93"},
      "27ba96cce52e4d7db4f81ea3df109e98":{
        "scriptId":"u94"},
      "34dbb5bd3bb24073bab9d267774bbb90":{
        "scriptId":"u95"},
      "878c60dbec5f4ad88c2dbfdf742a3499":{
        "scriptId":"u96"},
      "93476c03dd584ff2862684fa6a2d9d77":{
        "scriptId":"u97"},
      "d8bdd6ec163d4486959d1f3c75e31c28":{
        "scriptId":"u98"},
      "dec52cb8114f4d80a378669ee8fd1abf":{
        "scriptId":"u99"},
      "7f98b052ace3475b9dda8b4f41d800fe":{
        "scriptId":"u100"},
      "2c5bc93e287e4c529e7c54f858ebb9db":{
        "scriptId":"u101"},
      "ad753399440b469a804c54767913b57e":{
        "scriptId":"u102"}},
    "e0aa01653666418e9b12f3cd95bf2d80":{
      "scriptId":"u103"},
    "f1adea9dde894b41adb18023d4f8e0e0":{
      "scriptId":"u104"},
    "006de551f04d4618b01ba5b4bff7f5dd":{
      "scriptId":"u105"},
    "77c8f7f945c84298aa0e51ca48b79fda":{
      "scriptId":"u106"},
    "1c37c78ac67f45ab9e229ad81e36b566":{
      "scriptId":"u107"},
    "5b21988ca2a84492a87b0c32eaf838a6":{
      "scriptId":"u108"},
    "a9b3ccd98670463faed33b546f67a7e5":{
      "scriptId":"u109"},
    "3349652686d64098ad7c3b921951e162":{
      "scriptId":"u110"},
    "a984d50f4a5940a9bb48eb2437f3db0c":{
      "scriptId":"u111"},
    "0bf335a862a04c6da37d5050e8216e16":{
      "scriptId":"u112"},
    "5cd4872d7fc7422b91a1a08cfaae4002":{
      "scriptId":"u113"},
    "a6cfdfe725624222aacb4fb32f2b40eb":{
      "scriptId":"u114"},
    "173dbf11eef545c2a3ca494642094662":{
      "scriptId":"u115"},
    "13b82c0c99724c7a809b7f67b9318b55":{
      "scriptId":"u116"},
    "c48c85943a6b4fdd841b2848521c2d72":{
      "scriptId":"u117"},
    "750565ff9d244e8d981d5cdfa1e20737":{
      "scriptId":"u118"},
    "ca053dcc79ad47d99f41abb82a47abdf":{
      "scriptId":"u119"},
    "0c92b5b95f5d49da9449fe5de2fc12ff":{
      "scriptId":"u120"},
    "dbe74d40fcc24a7caa17d2a93ab96cc1":{
      "scriptId":"u121"},
    "f79d5276764349078f53b4d86136ae87":{
      "scriptId":"u122"},
    "0e7949d5caf6482b8f9192d6473a1285":{
      "scriptId":"u123"},
    "53afe9e2293541ffa9369720a03f2c2e":{
      "scriptId":"u124"},
    "e7080af1feaf4c3382cbf7719cea3374":{
      "scriptId":"u125"},
    "17fce1016c0345f9a08b67dae8d328ab":{
      "scriptId":"u126"},
    "85cb24953a5d44b0a48bd461bb7f60b8":{
      "scriptId":"u127"},
    "4f5604d3ce1846d3843ef8d8b042b045":{
      "scriptId":"u128"},
    "c16100f8f1ff4038b5c160f4c507e449":{
      "scriptId":"u129"},
    "f1f24130e73f449f8ec762d2689c4193":{
      "scriptId":"u130"},
    "a0108a4a7a5843e4bdf1701d4f2a0857":{
      "scriptId":"u131"},
    "322995fbe8d74cd8937185b7493c3878":{
      "scriptId":"u132"},
    "8fc4f61a84bc48f0a70600a67ea7a8eb":{
      "scriptId":"u133"},
    "b3080c3372f644aeaec4ee7045fe82e7":{
      "scriptId":"u134"},
    "2725dce06e98411fa022edb8c586bfcb":{
      "scriptId":"u135"},
    "75f44093494a4a2d80f4e8e0484d1ed1":{
      "scriptId":"u136"},
    "4e6c68cb6b30461cb67a2bc4ab1f3da5":{
      "scriptId":"u137"},
    "d8cf4bcd5d494f7c8eeb1049428e015c":{
      "scriptId":"u138"},
    "18d07f5aa42042b2a447268281e9117d":{
      "scriptId":"u139"},
    "edfa83187620410c8e86365d9356c4e3":{
      "scriptId":"u140"},
    "f47c022d00234fba8af30db3220137cf":{
      "scriptId":"u141"},
    "1d58fdb28acb486a9c9151cb1c50516a":{
      "scriptId":"u142"},
    "dd814f507ba341d282a7970b639cdb4a":{
      "scriptId":"u143"},
    "5faadd9ca58c47f2bf3fbece55108425":{
      "scriptId":"u144"},
    "b5a56d100dc3472a86aeeadd78ef8783":{
      "scriptId":"u145"},
    "978ff74612f140c89c18c2a24f78d8d8":{
      "scriptId":"u146"},
    "38534fe4ea72423cb63cba8b961bfd15":{
      "scriptId":"u147"},
    "165e1d1ebb6849d4ae2d4a10d7a0d6dc":{
      "scriptId":"u148"},
    "1997a694f2bc446bbc8bf14989096ff7":{
      "scriptId":"u149"},
    "ded0077ddd2444a796c9cffe66a28566":{
      "scriptId":"u150"},
    "ef7d6549e20e4c099a4a3347ba020d56":{
      "scriptId":"u151"},
    "99bf02ad2ee34bd6ac15a5461f1c0dfc":{
      "scriptId":"u152"},
    "8bd8e0ae8f2143e5940ade7a3eff842d":{
      "scriptId":"u153"},
    "2f8b3ec5382243d39a0224326321fc18":{
      "scriptId":"u154"},
    "5ced5cf9e2294a119ae4554d25d18f07":{
      "scriptId":"u155"},
    "ee398465d1ac445ebf77de38e6a8c9bd":{
      "scriptId":"u156"},
    "291bc438fc264f1d862d997e9005f825":{
      "scriptId":"u157"},
    "7e3f387f8f574503b81ad3a2000af395":{
      "scriptId":"u158"},
    "f9a4ad15f82b4c979f44fad71d0723bd":{
      "scriptId":"u159"},
    "958cccc91db2492e989b2d8555223cb3":{
      "scriptId":"u160"},
    "471b75dccd5e4006aaa498618161a057":{
      "scriptId":"u161"},
    "f1841dbc1ace4efdb64f0e9c840a6b0f":{
      "scriptId":"u162"},
    "88078ff2f87348feb6e16c175de3599d":{
      "scriptId":"u163"},
    "9f4aceb941a646ae9fc039e9e625a9e4":{
      "scriptId":"u164"},
    "c719213237354bd5b132d6d3115a0543":{
      "scriptId":"u165"},
    "4d2ccc251fca4161a16b1987f4dfedc5":{
      "scriptId":"u166"},
    "09b80efd4b354d79839899df9bda2c07":{
      "scriptId":"u167"},
    "70ee602b433b4e41a8c0e27b740ab793":{
      "scriptId":"u168"},
    "048c51758d164d1280ea185b8c4c0279":{
      "scriptId":"u169"},
    "9600cfbdeb874c09ab475595a4b10fc3":{
      "scriptId":"u170"},
    "2f48cf70b0354d22b48e552bd1d7c0fe":{
      "scriptId":"u171"}}});