$axure.loadCurrentPage({
  "url":"chat.html",
  "generationDate":new Date(1406213760142.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2f26524b319467fad6c20c961563b80",
    "type":"Axure:Page",
    "name":"chat",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8a711d7bd3142b3a4dfda7296caf96c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":29},
            "size":{
              "width":394,
              "height":547},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0413dc4b7c474306a649d1c8f8567bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":29},
                "size":{
                  "width":394,
                  "height":547},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/chat/u0.png"}},
{
          "id":"f6df12143f614116b5fc06a835b42349",
          "label":"富文本",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":576},
            "size":{
              "width":393,
              "height":351}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0218396b4bf24d79931532c0fed6181c",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"61f870e4f80143deb7c281e2fb25e6a9",
                  "label":"",
                  "parentDynamicPanel":"f6df12143f614116b5fc06a835b42349",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":391,
                      "height":353},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59bf898d197542f4b128bea081d204b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6df12143f614116b5fc06a835b42349",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":391,
                          "height":353},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/chat/u3.png"}},
{
                  "id":"042dfc41a0474f28886a570e1b0eba24",
                  "label":"",
                  "parentDynamicPanel":"f6df12143f614116b5fc06a835b42349",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":55,
                      "y":0},
                    "size":{
                      "width":45,
                      "height":57},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f194b9a0ebc43bb900e9a9adb375670",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6df12143f614116b5fc06a835b42349",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":55,
                          "y":0},
                        "size":{
                          "width":45,
                          "height":57},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"Move 富文本 to (448,286) linear 350ms",
                              "objectsToMoves":[{
                                  "objectPath":["f6df12143f614116b5fc06a835b42349"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"448",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"286",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":350}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a2b09d370daa4572b3288f2415db549a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":677},
            "size":{
              "width":411,
              "height":263},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c458bac826a44b2a84c616ce23db46e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":441,
                  "y":677},
                "size":{
                  "width":411,
                  "height":263},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/chat/u7.png"}},
{
          "id":"0829aeabef2a4fd993c6be1cc235a54f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":637},
            "size":{
              "width":394,
              "height":47},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a33213bc4ae433c9237355c1d80fcfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":637},
                "size":{
                  "width":394,
                  "height":47},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/chat/u9.png"}},
{
          "id":"bd9d5377778d47d9a66f1b98b1326e71",
          "label":"more",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":708,
              "y":547},
            "size":{
              "width":130,
              "height":86},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e2d1f3eee6974962a5abdfb60b1bf5c0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a4ab6cfc923f48bda53510520335322a",
                  "label":"",
                  "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFD1D1D1,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF444444},
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":130,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d515f33a042f4e139c74871046d37792",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFD1D1D1,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF444444},
                        "location":{
                          "x":0,
                          "y":43},
                        "size":{
                          "width":130,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/profile/u7.png"}},
{
                  "id":"ae3b800ca569459cbbe0c36c87f746c3",
                  "label":"",
                  "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFD1D1D1,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF444444},
                    "size":{
                      "width":130,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"481893888f894f42945041a2226c4bfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFD1D1D1,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF444444},
                        "size":{
                          "width":130,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/profile/u7.png"}},
{
                  "id":"83e35014607c4aa3a690d0d34668295f",
                  "label":"",
                  "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":130,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/profile/u11_line.png"}},
{
                  "id":"a1cccbaee53845f1b6581da1ef931ab1",
                  "label":"",
                  "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":13,
                      "y":56},
                    "size":{
                      "width":150,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2892d6529f8487487276838a04a5cc7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC,
                          "opacity":1},
                        "location":{
                          "x":13,
                          "y":56},
                        "size":{
                          "width":150,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"719925187b6a48d4bbb08ec73c7321bd",
                  "label":"",
                  "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFD1D1D1,
                      "opacity":1},
                    "location":{
                      "x":13,
                      "y":11},
                    "size":{
                      "width":150,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"222e9d5614624fd8aa77656c3b8e684c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bd9d5377778d47d9a66f1b98b1326e71",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFD1D1D1,
                          "opacity":1},
                        "location":{
                          "x":13,
                          "y":11},
                        "size":{
                          "width":150,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"64b56817257a4165bacb785951965eb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":637},
            "size":{
              "width":61,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d00f65cf0c3d45fe9f64c295603259eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":637},
                "size":{
                  "width":61,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open messages in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"messages.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb7561dbffdb4d62a188311537d5d707",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":790,
              "y":638},
            "size":{
              "width":51,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e03cca42d0f4bb9b5d3a8629123245c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":790,
                  "y":638},
                "size":{
                  "width":51,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle more",
                      "objectsToFades":[{
                          "objectPath":["bd9d5377778d47d9a66f1b98b1326e71"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8a711d7bd3142b3a4dfda7296caf96c":{
      "scriptId":"u0"},
    "0413dc4b7c474306a649d1c8f8567bfa":{
      "scriptId":"u1"},
    "f6df12143f614116b5fc06a835b42349":{
      "scriptId":"u2"},
    "61f870e4f80143deb7c281e2fb25e6a9":{
      "scriptId":"u3"},
    "59bf898d197542f4b128bea081d204b6":{
      "scriptId":"u4"},
    "042dfc41a0474f28886a570e1b0eba24":{
      "scriptId":"u5"},
    "9f194b9a0ebc43bb900e9a9adb375670":{
      "scriptId":"u6"},
    "a2b09d370daa4572b3288f2415db549a":{
      "scriptId":"u7"},
    "7c458bac826a44b2a84c616ce23db46e":{
      "scriptId":"u8"},
    "0829aeabef2a4fd993c6be1cc235a54f":{
      "scriptId":"u9"},
    "4a33213bc4ae433c9237355c1d80fcfe":{
      "scriptId":"u10"},
    "bd9d5377778d47d9a66f1b98b1326e71":{
      "scriptId":"u11"},
    "a4ab6cfc923f48bda53510520335322a":{
      "scriptId":"u12"},
    "d515f33a042f4e139c74871046d37792":{
      "scriptId":"u13"},
    "ae3b800ca569459cbbe0c36c87f746c3":{
      "scriptId":"u14"},
    "481893888f894f42945041a2226c4bfa":{
      "scriptId":"u15"},
    "83e35014607c4aa3a690d0d34668295f":{
      "scriptId":"u16"},
    "a1cccbaee53845f1b6581da1ef931ab1":{
      "scriptId":"u17"},
    "f2892d6529f8487487276838a04a5cc7":{
      "scriptId":"u18"},
    "719925187b6a48d4bbb08ec73c7321bd":{
      "scriptId":"u19"},
    "222e9d5614624fd8aa77656c3b8e684c":{
      "scriptId":"u20"},
    "64b56817257a4165bacb785951965eb6":{
      "scriptId":"u21"},
    "d00f65cf0c3d45fe9f64c295603259eb":{
      "scriptId":"u22"},
    "fb7561dbffdb4d62a188311537d5d707":{
      "scriptId":"u23"},
    "7e03cca42d0f4bb9b5d3a8629123245c":{
      "scriptId":"u24"}}});