$axure.loadCurrentPage({
  "url":"profile.html",
  "generationDate":new Date(1406213759960.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b27cf1cd01634db7ae3c2d54021cabcd",
    "type":"Axure:Page",
    "name":"profile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"edcb3197596840bea376a8366276b463",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":28},
            "size":{
              "width":394,
              "height":1149},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0965ffb6936046569cbd96d2f30941ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":28},
                "size":{
                  "width":394,
                  "height":1149},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/profile/u0.png"}},
{
          "id":"845ec2dd1d964f9a98f53b3f5161e226",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":1121},
            "size":{
              "width":50,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f2f5f3db044531b953dcbf8b1fb838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":1121},
                "size":{
                  "width":50,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open contacts in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"contacts.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2f72d6622684e62b2225f6cea856352",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF444444},
            "location":{
              "x":600,
              "y":1129},
            "size":{
              "width":180,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51da838aa8c04e4594f2a263cd824ebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF444444},
                "location":{
                  "x":600,
                  "y":1129},
                "size":{
                  "width":180,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/profile/u4.png"}},
{
          "id":"4459f67c9ecf4340a2aba3f82fd3aa32",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":708,
              "y":1034},
            "size":{
              "width":130,
              "height":86},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"70bda25110be4176be7fac77b6251c03",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"93c6f7719c034c209ce0470e729e30c9",
                  "label":"",
                  "parentDynamicPanel":"4459f67c9ecf4340a2aba3f82fd3aa32",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFD1D1D1,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF444444},
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":130,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89b8776d9f6448a4b5276677c7dbe40b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4459f67c9ecf4340a2aba3f82fd3aa32",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFD1D1D1,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF444444},
                        "location":{
                          "x":0,
                          "y":43},
                        "size":{
                          "width":130,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/profile/u7.png"}},
{
                  "id":"a96338706059437ea1aff27f29ce86a2",
                  "label":"",
                  "parentDynamicPanel":"4459f67c9ecf4340a2aba3f82fd3aa32",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFD1D1D1,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF444444},
                    "size":{
                      "width":130,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05cd1592ae1245fc9d9068c44b98e43a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4459f67c9ecf4340a2aba3f82fd3aa32",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFD1D1D1,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF444444},
                        "size":{
                          "width":130,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/profile/u7.png"}},
{
                  "id":"44e07d7763304c8ca75a154ba28d03c1",
                  "label":"",
                  "parentDynamicPanel":"4459f67c9ecf4340a2aba3f82fd3aa32",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":37},
                    "size":{
                      "width":130,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/profile/u11_line.png"}}]}]},
{
          "id":"747e8c9da9954e87b367ea6df9f75b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":791,
              "y":1120},
            "size":{
              "width":50,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f730a0fc534043b18d5daea0aeac70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":791,
                  "y":1120},
                "size":{
                  "width":50,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle (Dynamic Panel)",
                      "objectsToFades":[{
                          "objectPath":["4459f67c9ecf4340a2aba3f82fd3aa32"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1feb31de61a4405cb09f77e18aedcf74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF364E5A,
              "opacity":1},
            "lineSpacing":"25px",
            "location":{
              "x":139,
              "y":29},
            "size":{
              "width":240,
              "height":125},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1902c8f9ef184f5a936ad7bdab61a31e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF364E5A,
                  "opacity":1},
                "lineSpacing":"25px",
                "location":{
                  "x":139,
                  "y":29},
                "size":{
                  "width":240,
                  "height":125},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "edcb3197596840bea376a8366276b463":{
      "scriptId":"u0"},
    "0965ffb6936046569cbd96d2f30941ab":{
      "scriptId":"u1"},
    "845ec2dd1d964f9a98f53b3f5161e226":{
      "scriptId":"u2"},
    "b0f2f5f3db044531b953dcbf8b1fb838":{
      "scriptId":"u3"},
    "b2f72d6622684e62b2225f6cea856352":{
      "scriptId":"u4"},
    "51da838aa8c04e4594f2a263cd824ebf":{
      "scriptId":"u5"},
    "4459f67c9ecf4340a2aba3f82fd3aa32":{
      "scriptId":"u6"},
    "93c6f7719c034c209ce0470e729e30c9":{
      "scriptId":"u7"},
    "89b8776d9f6448a4b5276677c7dbe40b":{
      "scriptId":"u8"},
    "a96338706059437ea1aff27f29ce86a2":{
      "scriptId":"u9"},
    "05cd1592ae1245fc9d9068c44b98e43a":{
      "scriptId":"u10"},
    "44e07d7763304c8ca75a154ba28d03c1":{
      "scriptId":"u11"},
    "747e8c9da9954e87b367ea6df9f75b29":{
      "scriptId":"u12"},
    "39f730a0fc534043b18d5daea0aeac70":{
      "scriptId":"u13"},
    "1feb31de61a4405cb09f77e18aedcf74":{
      "scriptId":"u14"},
    "1902c8f9ef184f5a936ad7bdab61a31e":{
      "scriptId":"u15"}}});