$axure.loadCurrentPage({
  "url":"x.html",
  "generationDate":new Date(1405078989812.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6d165a37ccd342d6b31ea2d9d5e08148",
    "type":"Axure:Page",
    "name":"X",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46d644aca9ee4d01a204c9c1d389f62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":40},
            "size":{
              "width":237,
              "height":437},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF93CC65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d255e8741745fba515cf81fe6758f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":40},
                "size":{
                  "width":237,
                  "height":437},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF93CC65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u0.png"}},
{
          "id":"81de7202721a45ac968dff79e0528c3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":45},
            "size":{
              "width":215,
              "height":291},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9dae35ff95949c8a053094b22925460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":45},
                "size":{
                  "width":215,
                  "height":291},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u2.png"}},
{
          "id":"17bc026554084078af0fcfe3fca44426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":329,
              "y":353},
            "size":{
              "width":80,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e269ce9b40f74d1aa28505f8684f9cfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":329,
                  "y":353},
                "size":{
                  "width":80,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u4.png"}},
{
          "id":"0eda80c14baf4533948bde31fee9b9f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":190,
              "y":348},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d35708013c744bb69cd87f4b8053e7d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":348},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4c771cb02c415c8e8bee0239c157ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":400},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/x/u8_line.png"}},
{
          "id":"a74c7288f17f40de9f7d47cf1b5ea1c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":197,
              "y":378},
            "size":{
              "width":95,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8880bab66069475ba583844a383cf5fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":197,
                  "y":378},
                "size":{
                  "width":95,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"530480d93c9b43e48da3f47cd69289cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":329,
              "y":424},
            "size":{
              "width":80,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73fa735fbce544f885cde62456fbccbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":329,
                  "y":424},
                "size":{
                  "width":80,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u4.png"}},
{
          "id":"9ce4d3618e724517bcceb82822f35f6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":190,
              "y":417},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6befa79c4f4cca9ca30eae69cbb55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":417},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb684f3fa44449a98577c6f36a634b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":197,
              "y":446},
            "size":{
              "width":123,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea57362074c4f93be6dff5ee29d9165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":197,
                  "y":446},
                "size":{
                  "width":123,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e52a08e3b034e9cbe56b861a498149a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":449},
            "size":{
              "width":21,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/x/u17_start.png",
            "end~":"images/x/u17_end.png",
            "line~":"images/x/u17_line.png"}},
{
          "id":"76869120f0f14645b4de7fe6b011ed5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":40},
            "size":{
              "width":237,
              "height":495},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF93CC65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d28ca6c514a450398d25e9c1e3596fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":40},
                "size":{
                  "width":237,
                  "height":495},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF93CC65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u18.png"}},
{
          "id":"1c6daa28bef3416499b5c634c20dcb3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":45},
            "size":{
              "width":215,
              "height":291},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"455d03a95b5548cc95433403c483a4f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":771,
                  "y":45},
                "size":{
                  "width":215,
                  "height":291},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u2.png"}},
{
          "id":"b56b0936f7f9419e87c82449ad91d01e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":771,
              "y":390},
            "size":{
              "width":215,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6737311c0c74e6da77efd805dfdbb5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":771,
                  "y":390},
                "size":{
                  "width":215,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u22.png"}},
{
          "id":"df9248d994ce436dae3cb10b6ecc0139",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":767,
              "y":348},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a739bf1e769043289592ab6b2df0668b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":767,
                  "y":348},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e8852f96c3e417287ff2d1cf637a42b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":774,
              "y":431},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/x/u8_line.png"}},
{
          "id":"ed95567b4caa471bbaa014c6f3cdad8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":889,
              "y":356},
            "size":{
              "width":95,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"427ff4373fbe4d1f9ed44d0c6636dc0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":889,
                  "y":356},
                "size":{
                  "width":95,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72a0ddd096534b96b33980651bf386c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":771,
              "y":489},
            "size":{
              "width":215,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d4b7be2762e4f5998e0ac38262b0be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":771,
                  "y":489},
                "size":{
                  "width":215,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u22.png"}},
{
          "id":"d7e58ede4d3a455183842b076c5e0ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":767,
              "y":446},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aec7f008f1c14e43a1807af517a8382d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":767,
                  "y":446},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab9b01082ff84fa097ef7ed6161f2bea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":917,
              "y":446},
            "size":{
              "width":163,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"203cc827ea7346ea9fc36b09ebcc6e80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":917,
                  "y":446},
                "size":{
                  "width":163,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecc6ed37e8924bf394f3adf98cd3e0fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":473,
              "y":40},
            "size":{
              "width":237,
              "height":450},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF93CC65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fbc8fb1e1643b1824ef06258a00f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":473,
                  "y":40},
                "size":{
                  "width":237,
                  "height":450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF93CC65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u35.png"}},
{
          "id":"9891b97696054361b5b44e2fdadbd1db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":45},
            "size":{
              "width":215,
              "height":291},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8bcaf077f7c4d7995291d7ea68fe4ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":45},
                "size":{
                  "width":215,
                  "height":291},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u2.png"}},
{
          "id":"493f527d4460473094c8beb08de90224",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":637,
              "y":353},
            "size":{
              "width":62,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3106f0fbd6e24f699d3d82cfb783a7a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":637,
                  "y":353},
                "size":{
                  "width":62,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u39.png"}},
{
          "id":"c66394a0070a4bf8b6b157dd1d7bbf97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":480,
              "y":348},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0ef5c27e71640d8a13c26b3ba57fba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":348},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd993d2680f84606958b6afcd7aa87ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":407},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/x/u8_line.png"}},
{
          "id":"e58591c6e60b44749b02ade5efba72cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":522,
              "y":382},
            "size":{
              "width":95,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd36042212474ef29dc3ac418af89c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":522,
                  "y":382},
                "size":{
                  "width":95,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d460acbf2ae466189c2aeb8845f5092",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF24C4E},
            "location":{
              "x":637,
              "y":432},
            "size":{
              "width":62,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a21f453e4294623ae477accaa596066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E},
                "location":{
                  "x":637,
                  "y":432},
                "size":{
                  "width":62,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u39.png"}},
{
          "id":"ca079a64a52b424b8ec0929a05b6e8f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF24C4E,
              "opacity":1},
            "location":{
              "x":480,
              "y":425},
            "size":{
              "width":150,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fbe86992e2640bb95953075fb3949d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF24C4E,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":425},
                "size":{
                  "width":150,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c631857e8460464d8f081227301f7c4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":520,
              "y":459},
            "size":{
              "width":123,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38b79fe89614609aa80f4ea6389ee7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":459},
                "size":{
                  "width":123,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20370a0a79f042468fd7fb2047d407a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":462},
            "size":{
              "width":15,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/x/u52_start.png",
            "end~":"images/x/u52_end.png",
            "line~":"images/x/u52_line.png"}},
{
          "id":"e40bcaa72fd147d0a3a16b7f4123403d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF5EA9FF},
            "location":{
              "x":487,
              "y":381},
            "size":{
              "width":30,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18fb93ee5d074e7cb007d59beaadf76e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5EA9FF},
                "location":{
                  "x":487,
                  "y":381},
                "size":{
                  "width":30,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u53.png"}},
{
          "id":"223cc925ca1241a5ae80e2840f6ccfb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF5EA9FF},
            "location":{
              "x":487,
              "y":458},
            "size":{
              "width":30,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70acd8e9589c43e497f46642778d2ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5EA9FF},
                "location":{
                  "x":487,
                  "y":458},
                "size":{
                  "width":30,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/x/u53.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "46d644aca9ee4d01a204c9c1d389f62f":{
      "scriptId":"u0"},
    "06d255e8741745fba515cf81fe6758f3":{
      "scriptId":"u1"},
    "81de7202721a45ac968dff79e0528c3a":{
      "scriptId":"u2"},
    "b9dae35ff95949c8a053094b22925460":{
      "scriptId":"u3"},
    "17bc026554084078af0fcfe3fca44426":{
      "scriptId":"u4"},
    "e269ce9b40f74d1aa28505f8684f9cfe":{
      "scriptId":"u5"},
    "0eda80c14baf4533948bde31fee9b9f3":{
      "scriptId":"u6"},
    "d35708013c744bb69cd87f4b8053e7d8":{
      "scriptId":"u7"},
    "8e4c771cb02c415c8e8bee0239c157ec":{
      "scriptId":"u8"},
    "a74c7288f17f40de9f7d47cf1b5ea1c3":{
      "scriptId":"u9"},
    "8880bab66069475ba583844a383cf5fe":{
      "scriptId":"u10"},
    "530480d93c9b43e48da3f47cd69289cd":{
      "scriptId":"u11"},
    "73fa735fbce544f885cde62456fbccbd":{
      "scriptId":"u12"},
    "9ce4d3618e724517bcceb82822f35f6e":{
      "scriptId":"u13"},
    "fe6befa79c4f4cca9ca30eae69cbb55e":{
      "scriptId":"u14"},
    "cb684f3fa44449a98577c6f36a634b5e":{
      "scriptId":"u15"},
    "eea57362074c4f93be6dff5ee29d9165":{
      "scriptId":"u16"},
    "7e52a08e3b034e9cbe56b861a498149a":{
      "scriptId":"u17"},
    "76869120f0f14645b4de7fe6b011ed5b":{
      "scriptId":"u18"},
    "2d28ca6c514a450398d25e9c1e3596fd":{
      "scriptId":"u19"},
    "1c6daa28bef3416499b5c634c20dcb3d":{
      "scriptId":"u20"},
    "455d03a95b5548cc95433403c483a4f0":{
      "scriptId":"u21"},
    "b56b0936f7f9419e87c82449ad91d01e":{
      "scriptId":"u22"},
    "f6737311c0c74e6da77efd805dfdbb5e":{
      "scriptId":"u23"},
    "df9248d994ce436dae3cb10b6ecc0139":{
      "scriptId":"u24"},
    "a739bf1e769043289592ab6b2df0668b":{
      "scriptId":"u25"},
    "8e8852f96c3e417287ff2d1cf637a42b":{
      "scriptId":"u26"},
    "ed95567b4caa471bbaa014c6f3cdad8c":{
      "scriptId":"u27"},
    "427ff4373fbe4d1f9ed44d0c6636dc0b":{
      "scriptId":"u28"},
    "72a0ddd096534b96b33980651bf386c7":{
      "scriptId":"u29"},
    "3d4b7be2762e4f5998e0ac38262b0be4":{
      "scriptId":"u30"},
    "d7e58ede4d3a455183842b076c5e0ac3":{
      "scriptId":"u31"},
    "aec7f008f1c14e43a1807af517a8382d":{
      "scriptId":"u32"},
    "ab9b01082ff84fa097ef7ed6161f2bea":{
      "scriptId":"u33"},
    "203cc827ea7346ea9fc36b09ebcc6e80":{
      "scriptId":"u34"},
    "ecc6ed37e8924bf394f3adf98cd3e0fc":{
      "scriptId":"u35"},
    "57fbc8fb1e1643b1824ef06258a00f9d":{
      "scriptId":"u36"},
    "9891b97696054361b5b44e2fdadbd1db":{
      "scriptId":"u37"},
    "b8bcaf077f7c4d7995291d7ea68fe4ec":{
      "scriptId":"u38"},
    "493f527d4460473094c8beb08de90224":{
      "scriptId":"u39"},
    "3106f0fbd6e24f699d3d82cfb783a7a6":{
      "scriptId":"u40"},
    "c66394a0070a4bf8b6b157dd1d7bbf97":{
      "scriptId":"u41"},
    "c0ef5c27e71640d8a13c26b3ba57fba6":{
      "scriptId":"u42"},
    "dd993d2680f84606958b6afcd7aa87ee":{
      "scriptId":"u43"},
    "e58591c6e60b44749b02ade5efba72cf":{
      "scriptId":"u44"},
    "fd36042212474ef29dc3ac418af89c01":{
      "scriptId":"u45"},
    "9d460acbf2ae466189c2aeb8845f5092":{
      "scriptId":"u46"},
    "5a21f453e4294623ae477accaa596066":{
      "scriptId":"u47"},
    "ca079a64a52b424b8ec0929a05b6e8f8":{
      "scriptId":"u48"},
    "2fbe86992e2640bb95953075fb3949d7":{
      "scriptId":"u49"},
    "c631857e8460464d8f081227301f7c4c":{
      "scriptId":"u50"},
    "d38b79fe89614609aa80f4ea6389ee7b":{
      "scriptId":"u51"},
    "20370a0a79f042468fd7fb2047d407a8":{
      "scriptId":"u52"},
    "e40bcaa72fd147d0a3a16b7f4123403d":{
      "scriptId":"u53"},
    "18fb93ee5d074e7cb007d59beaadf76e":{
      "scriptId":"u54"},
    "223cc925ca1241a5ae80e2840f6ccfb2":{
      "scriptId":"u55"},
    "70acd8e9589c43e497f46642778d2ead":{
      "scriptId":"u56"}}});