$axure.loadCurrentPage({
  "url":"侧栏.html",
  "generationDate":new Date(1406213773514.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6738b5b1f31f4e3eb8d62a777fb40fbc",
    "type":"Axure:Page",
    "name":"侧栏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2d0720cb1144e4b9732ffc8aed7dc19",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":30},
            "size":{
              "width":329,
              "height":570}},
          "adaptiveStyles":{
},
          "masterId":"6a20878ffbd44d4e8b763530fd86d774"},
{
          "id":"270425865357434b9b076f0dd1d3471e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF027BFF,
              "opacity":1},
            "location":{
              "x":162,
              "y":62},
            "size":{
              "width":64,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040d1909e983485686c53374e77eefb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF027BFF,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":62},
                "size":{
                  "width":64,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4500a389619745af9f22c726495cc93e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"30px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF02A8FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":312,
              "y":58},
            "size":{
              "width":29,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c407c433d694820b9ca93cc2338f3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"30px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF02A8FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":312,
                  "y":58},
                "size":{
                  "width":29,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56eca325f8224da1b60df6b96f82265e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFCFCFC},
{
                  "color":0xFFFCFCFC}]},
            "location":{
              "x":281,
              "y":53},
            "size":{
              "width":68,
              "height":547},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96849cb229b24587ad279e36b3470488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFCFCFC},
{
                      "color":0xFFFCFCFC}]},
                "location":{
                  "x":281,
                  "y":53},
                "size":{
                  "width":68,
                  "height":547},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u14.png"}},
{
          "id":"eaf1d993c9b94cbfb9d1fba95c0c5275",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":281,
              "y":52},
            "size":{
              "width":68,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6587438541844e8083f45881ffd3ccb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":281,
                  "y":52},
                "size":{
                  "width":68,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u16.png"}},
{
          "id":"af0c2ab6bf1b473f98443ce0175514a1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":63},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF02A8FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u7_line.png"}},
{
          "id":"ed0b27d60e5f4627a5450a4ad56368e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":69},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF02A8FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u7_line.png"}},
{
          "id":"d0151f82d38d43f3b5c4c4bdd0515f82",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":75},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF02A8FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u7_line.png"}},
{
          "id":"99060bccc3f245908feaeda17aef5fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":30,
              "y":52},
            "size":{
              "width":270,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1905c327a8f406facb13ec7d9055737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":30,
                  "y":52},
                "size":{
                  "width":270,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u21.png"}},
{
          "id":"325c772d8d904419bbcc93e98a152963",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":182},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b3b34a080504423a7c89e8c0b43a0b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":182},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1059cfad428048a491b40eed25662f72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":361},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5787d4d925f412885e2716189be1b3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":361},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d76700e58f742fba15171706ac2d5a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":407},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3eaee163b71453ea7a5812a5054b37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":407},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd2c265172e44aa3b29f26dbfdc73e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":451},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6573db016cab495ca75419fd1889e45b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":451},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f81df233a3b4d2eabddd74754520e17",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":232},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u31_line.png"}},
{
          "id":"70c16ab25eb64fc5aad14abec5e9b077",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":385},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u32_line.png"}},
{
          "id":"24a288099e9349f786b47119e9e899f7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":430},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u32_line.png"}},
{
          "id":"97dab374883848cf8622b8bcbf91fd02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":184},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1056c19c892642618afa4df5b5a4dee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":184},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u34.png"}},
{
          "id":"b6d58605a0a14a8986101cf30e0467a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":363},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbdadb515b7d486288c16d28a80bc15e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":363},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u36.png"}},
{
          "id":"97b17437c5a24742b5801993a5481cda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":409},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0872d07296df419a8b4ac6a56c35e547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":409},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u38.png"}},
{
          "id":"08dbe5202b524df3ab7b89e9664734cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":453},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b64cfcb15214431e93d6085f0c22eae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":453},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u40.png"}},
{
          "id":"146cfc81634944b6b6bc65b3397a5d9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":88},
            "size":{
              "width":60,
              "height":60},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed0be96d928b4bec801e2ef56ac5b9ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":88},
                "size":{
                  "width":60,
                  "height":60},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u42.png"}},
{
          "id":"0a9e1aa9297740d1a4dad35d3b28eb9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":129,
              "y":85},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f40332a033664b02ac3e4a4351ee94e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":129,
                  "y":85},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56b4f86462354b87a221f6a7c3312c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":531},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b223f5cf94f2413ca3af7c141f183722",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":531},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eafb2fe5ddfb4a07ac37600b87f16792",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":60,
              "y":533},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53e67d0e88b34aa690508539c955046e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":60,
                  "y":533},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u48.png"}},
{
          "id":"ed20a63b75954ed795c2033575b91df9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":472},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/侧栏/u32_line.png"}},
{
          "id":"c32ccda81bd6483cbd2d5d256fe8b198",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":129,
              "y":107},
            "size":{
              "width":150,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0fc95ee2614f71bde381f2ae013afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":129,
                  "y":107},
                "size":{
                  "width":150,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60167915d3064a42862b90eff8295283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":87,
              "y":492},
            "size":{
              "width":150,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3907e579ff01430f8bdc02359f113e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":492},
                "size":{
                  "width":150,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b338d7b0116a4d7088685141dcbe1f31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":59,
              "y":494},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f2ad8315854e1da70d662474634489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":59,
                  "y":494},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u55.png"}},
{
          "id":"2c6e379130ad4f3881738440964bd361",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF434343},
            "location":{
              "x":30,
              "y":212},
            "size":{
              "width":270,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426203127fff4ea5b3e49b4eefb9db1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF434343},
                "location":{
                  "x":30,
                  "y":212},
                "size":{
                  "width":270,
                  "height":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u57.png"}},
{
          "id":"9193b02d6c13417b8bde210920f2fff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"34px",
            "location":{
              "x":87,
              "y":213},
            "size":{
              "width":90,
              "height":136},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214bcb27aff243f08112071924f75c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"34px",
                "location":{
                  "x":87,
                  "y":213},
                "size":{
                  "width":90,
                  "height":136},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b68e1e7a9b2e47fea07f3b828bb28635",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3333},
            "location":{
              "x":115,
              "y":180},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"7.5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b190d053a1f24452bd6e14c1ca2c427e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3333},
                "location":{
                  "x":115,
                  "y":180},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"7.5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u61.png"}},
{
          "id":"2fcf4ce0f03f44dc8e37a0981a2636f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3333},
            "location":{
              "x":115,
              "y":359},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"7.5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a35da8eaf3674cdd9761abab78a841ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3333},
                "location":{
                  "x":115,
                  "y":359},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"7.5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/侧栏/u61.png"}}]}},
  "masters":{
    "6a20878ffbd44d4e8b763530fd86d774":{
      "packageId":"6a20878ffbd44d4e8b763530fd86d774",
      "type":"Axure:Master",
      "name":"bg(320*568)",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"951b49d473754710bc36e789336784d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":300,
                "y":30},
              "size":{
                "width":320,
                "height":568},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb456dd2939e4e1abe407a6e9926a607",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":300,
                    "y":30},
                  "size":{
                    "width":320,
                    "height":568},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/侧栏/u1.png"}},
{
            "id":"7730bf3ecebb4182b194b84223113798",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":296,
                "y":28},
              "size":{
                "width":329,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c2d4b046abf48bdbdafccf789067bca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":296,
                    "y":28},
                  "size":{
                    "width":329,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/侧栏/u3.png"}},
{
            "id":"f41c5dbea39e450387e952f9993cb3e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF7F7F7},
              "location":{
                "x":300,
                "y":50},
              "size":{
                "width":320,
                "height":44},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5dfe89403c2a48a29a8e5cb03ec74d8a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF7F7F7},
                  "location":{
                    "x":300,
                    "y":50},
                  "size":{
                    "width":320,
                    "height":44},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/侧栏/u5.png"}},
{
            "id":"b4e80882baf8469492048bfcb2633f30",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":315,
                "y":61},
              "size":{
                "width":20,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF02A8FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/侧栏/u7_line.png"}},
{
            "id":"0a483abd86bc47c180bda1628b4d5352",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":315,
                "y":67},
              "size":{
                "width":20,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF02A8FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/侧栏/u7_line.png"}},
{
            "id":"64714a3bf0ff4130bec6848d368777dc",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":315,
                "y":73},
              "size":{
                "width":20,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF02A8FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/侧栏/u7_line.png"}}]}}},
  "objectPaths":{
    "f2d0720cb1144e4b9732ffc8aed7dc19":{
      "scriptId":"u0",
      "951b49d473754710bc36e789336784d2":{
        "scriptId":"u1"},
      "bb456dd2939e4e1abe407a6e9926a607":{
        "scriptId":"u2"},
      "7730bf3ecebb4182b194b84223113798":{
        "scriptId":"u3"},
      "2c2d4b046abf48bdbdafccf789067bca":{
        "scriptId":"u4"},
      "f41c5dbea39e450387e952f9993cb3e3":{
        "scriptId":"u5"},
      "5dfe89403c2a48a29a8e5cb03ec74d8a":{
        "scriptId":"u6"},
      "b4e80882baf8469492048bfcb2633f30":{
        "scriptId":"u7"},
      "0a483abd86bc47c180bda1628b4d5352":{
        "scriptId":"u8"},
      "64714a3bf0ff4130bec6848d368777dc":{
        "scriptId":"u9"}},
    "270425865357434b9b076f0dd1d3471e":{
      "scriptId":"u10"},
    "040d1909e983485686c53374e77eefb6":{
      "scriptId":"u11"},
    "4500a389619745af9f22c726495cc93e":{
      "scriptId":"u12"},
    "3c407c433d694820b9ca93cc2338f3af":{
      "scriptId":"u13"},
    "56eca325f8224da1b60df6b96f82265e":{
      "scriptId":"u14"},
    "96849cb229b24587ad279e36b3470488":{
      "scriptId":"u15"},
    "eaf1d993c9b94cbfb9d1fba95c0c5275":{
      "scriptId":"u16"},
    "6587438541844e8083f45881ffd3ccb8":{
      "scriptId":"u17"},
    "af0c2ab6bf1b473f98443ce0175514a1":{
      "scriptId":"u18"},
    "ed0b27d60e5f4627a5450a4ad56368e8":{
      "scriptId":"u19"},
    "d0151f82d38d43f3b5c4c4bdd0515f82":{
      "scriptId":"u20"},
    "99060bccc3f245908feaeda17aef5fe7":{
      "scriptId":"u21"},
    "f1905c327a8f406facb13ec7d9055737":{
      "scriptId":"u22"},
    "325c772d8d904419bbcc93e98a152963":{
      "scriptId":"u23"},
    "7b3b34a080504423a7c89e8c0b43a0b0":{
      "scriptId":"u24"},
    "1059cfad428048a491b40eed25662f72":{
      "scriptId":"u25"},
    "a5787d4d925f412885e2716189be1b3e":{
      "scriptId":"u26"},
    "3d76700e58f742fba15171706ac2d5a8":{
      "scriptId":"u27"},
    "c3eaee163b71453ea7a5812a5054b37f":{
      "scriptId":"u28"},
    "dd2c265172e44aa3b29f26dbfdc73e8c":{
      "scriptId":"u29"},
    "6573db016cab495ca75419fd1889e45b":{
      "scriptId":"u30"},
    "9f81df233a3b4d2eabddd74754520e17":{
      "scriptId":"u31"},
    "70c16ab25eb64fc5aad14abec5e9b077":{
      "scriptId":"u32"},
    "24a288099e9349f786b47119e9e899f7":{
      "scriptId":"u33"},
    "97dab374883848cf8622b8bcbf91fd02":{
      "scriptId":"u34"},
    "1056c19c892642618afa4df5b5a4dee1":{
      "scriptId":"u35"},
    "b6d58605a0a14a8986101cf30e0467a1":{
      "scriptId":"u36"},
    "cbdadb515b7d486288c16d28a80bc15e":{
      "scriptId":"u37"},
    "97b17437c5a24742b5801993a5481cda":{
      "scriptId":"u38"},
    "0872d07296df419a8b4ac6a56c35e547":{
      "scriptId":"u39"},
    "08dbe5202b524df3ab7b89e9664734cf":{
      "scriptId":"u40"},
    "b64cfcb15214431e93d6085f0c22eae7":{
      "scriptId":"u41"},
    "146cfc81634944b6b6bc65b3397a5d9a":{
      "scriptId":"u42"},
    "ed0be96d928b4bec801e2ef56ac5b9ac":{
      "scriptId":"u43"},
    "0a9e1aa9297740d1a4dad35d3b28eb9d":{
      "scriptId":"u44"},
    "f40332a033664b02ac3e4a4351ee94e0":{
      "scriptId":"u45"},
    "56b4f86462354b87a221f6a7c3312c76":{
      "scriptId":"u46"},
    "b223f5cf94f2413ca3af7c141f183722":{
      "scriptId":"u47"},
    "eafb2fe5ddfb4a07ac37600b87f16792":{
      "scriptId":"u48"},
    "53e67d0e88b34aa690508539c955046e":{
      "scriptId":"u49"},
    "ed20a63b75954ed795c2033575b91df9":{
      "scriptId":"u50"},
    "c32ccda81bd6483cbd2d5d256fe8b198":{
      "scriptId":"u51"},
    "ce0fc95ee2614f71bde381f2ae013afa":{
      "scriptId":"u52"},
    "60167915d3064a42862b90eff8295283":{
      "scriptId":"u53"},
    "3907e579ff01430f8bdc02359f113e16":{
      "scriptId":"u54"},
    "b338d7b0116a4d7088685141dcbe1f31":{
      "scriptId":"u55"},
    "e7f2ad8315854e1da70d662474634489":{
      "scriptId":"u56"},
    "2c6e379130ad4f3881738440964bd361":{
      "scriptId":"u57"},
    "426203127fff4ea5b3e49b4eefb9db1a":{
      "scriptId":"u58"},
    "9193b02d6c13417b8bde210920f2fff3":{
      "scriptId":"u59"},
    "214bcb27aff243f08112071924f75c0a":{
      "scriptId":"u60"},
    "b68e1e7a9b2e47fea07f3b828bb28635":{
      "scriptId":"u61"},
    "b190d053a1f24452bd6e14c1ca2c427e":{
      "scriptId":"u62"},
    "2fcf4ce0f03f44dc8e37a0981a2636f6":{
      "scriptId":"u63"},
    "a35da8eaf3674cdd9761abab78a841ba":{
      "scriptId":"u64"}}});