$axure.loadCurrentPage({
  "url":"我的信息化门户.html",
  "generationDate":new Date(1406213768148.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2f1aeac4005445f7aa2defce2b395a60",
    "type":"Axure:Page",
    "name":"我的信息化门户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46b03fd3207547d389883bb8885c0d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFBFBFB},
            "location":{
              "x":211,
              "y":51},
            "size":{
              "width":320,
              "height":561},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c999b84f70b44f9b950ae8aeeb461e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFBFBFB},
                "location":{
                  "x":211,
                  "y":51},
                "size":{
                  "width":320,
                  "height":561},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u0.png"}},
{
          "id":"d12bc3df438540528ad5b52680f84b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF009191},
{
                  "color":0xFF009191},
{
                  "color":0xFF009999},
{
                  "color":0xFF009999}]},
            "location":{
              "x":211,
              "y":52},
            "size":{
              "width":320,
              "height":47},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9533b0498ccc43c3972e194079cbd6d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF009191},
{
                      "color":0xFF009191},
{
                      "color":0xFF009999},
{
                      "color":0xFF009999}]},
                "location":{
                  "x":211,
                  "y":52},
                "size":{
                  "width":320,
                  "height":47},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u46.png"}},
{
          "id":"bafc0ca331104cfba5ad253c014c79f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":59},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7587e45a799e4c4bb9fe4a0f1cefcdf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":59},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/方案3/u136.png"}},
{
          "id":"10b5e0c08d6f4b64a83f6e44b7831cab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":59},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8afd24588ce8416b869fde1e43ee6c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":59},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/方案3/u136.png"}},
{
          "id":"7050b367c7294869a6f1d66f86c7e18b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":284,
              "y":63},
            "size":{
              "width":175,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8cae802a66455d8db4d132e30f774b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":63},
                "size":{
                  "width":175,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ef446ac544d4e028d8f0309de7ac35e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":211,
              "y":101},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3ddb9fe87e9413b8e878a6ad25776f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":101},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"5fc9fe39d7bc4c99a1aeb721a976c73b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":291,
              "y":101},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e8852c131414e3b9433ad33d108c54a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":291,
                  "y":101},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"0df0a255fd1a436287b35a1adc9aeb78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":370,
              "y":101},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e669d405db654fe89c02520fc624b77b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":101},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"fdc2b3a4c4fa4b16b92ae0e9fd2e2584",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":450,
              "y":101},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f872aa65ee4c44fab3a66c5db00f094c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":101},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u74.png"}},
{
          "id":"232c37c0aef24f0f957b24b2939ee99d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":61},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68428bd1c3a04624978c25577f3cbb82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":61},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u18.png"}},
{
          "id":"18ce6fab697e49f093b0e67a4b933381",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":61},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68ae67eb8321452ea5fdffdc124368b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":61},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u18.png"}},
{
          "id":"e6be580621044d918d2436b17d2973c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":507,
              "y":60},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"16.5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf61f76c6ccb4ccaab19fb708d8b0e9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":507,
                  "y":60},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"16.5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u22.png"}},
{
          "id":"be8061ce55ab4a0c89ba2482e5ddefac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":157},
            "size":{
              "width":42,
              "height":43},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b732c6a4049244b6924ef8f581bdbfe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":157},
                "size":{
                  "width":42,
                  "height":43},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u24.png"}},
{
          "id":"3f0dc90835c044fd9ab226fb4a563ada",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":168},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7327dff6014d41b988887644702dd0b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":168},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a08d4e92b8764f10a5d8dc5e099c5ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":245},
            "size":{
              "width":41,
              "height":42},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd1dff19a6941a38cd7870b35afb1a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":245},
                "size":{
                  "width":41,
                  "height":42},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u28.png"}},
{
          "id":"4951238b25a4439fa1fc2757ce9c746f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":255},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb24a557f0a45b18b29ee44318af852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":255},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ee7cbbb0d74d818cdc763aed0f70f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":333},
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26982d0e6a9f4fd8b432a1896748e025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":333},
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u32.png"}},
{
          "id":"99fac2dfe6ee439e93d48f9a8f3e3f7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":342},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4cb0d6a66c147a1928365b2c7ccf301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":342},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4526c003ee04ab0bff32d44d2a3f53f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":164},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c524b1bfadf4a6f864683adc7a3eab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":164},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"5710f741343d435cbd3d5bfffc67a4cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":251},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61dc38f0faf142e89c8e205ca1a0585b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":251},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"af95965e268248c3957f5b8e4604cc38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":338},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"931fc732edd643a699fae0d6647e58d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":338},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"fd1eda541d5049709af91cf810d5d3c0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":216},
            "size":{
              "width":319,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的信息化门户/u42_line.png"}},
{
          "id":"4b99a6f94cbb47efa9942a0dd0c984fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":308},
            "size":{
              "width":319,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的信息化门户/u42_line.png"}},
{
          "id":"c2722cef0d844b67951810bf5d18412b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"3039d2abe31742d7b373be653788a5ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":733,
              "y":63},
            "size":{
              "width":175,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a15c8a2848444cbc21a29fe7554641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":733,
                  "y":63},
                "size":{
                  "width":175,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c29ed8ada6e149be84f5d188dd5c641a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":234,
              "y":399},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da0476e39594662bae166c997f52ab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":234,
                  "y":399},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0225237330ad4014a15708601e8e2b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399FF},
            "location":{
              "x":221,
              "y":400},
            "size":{
              "width":5,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8e3ddff872489eb7bb497af1ada61c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF},
                "location":{
                  "x":221,
                  "y":400},
                "size":{
                  "width":5,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业管家-标签展示页--详情页/u112.png"}},
{
          "id":"5c9716810fe7448cb384b2b9de288d3b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":435},
            "size":{
              "width":68,
              "height":88},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0c39ad377e4727a98ff2ac2f3face5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":435},
                "size":{
                  "width":68,
                  "height":88},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u48.png"}},
{
          "id":"d559da695878421888218e56e71703d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":435},
            "size":{
              "width":68,
              "height":89},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60438721be9249439e3ddcf8dd3abe68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":435},
                "size":{
                  "width":68,
                  "height":89},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u57.png"}},
{
          "id":"e29ae9f6a4754405b7052cb1fbd2f8e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":435},
            "size":{
              "width":68,
              "height":88},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cb0f2af93a4af09b1f22f2fc8d6cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":435},
                "size":{
                  "width":68,
                  "height":88},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信息化产品/u48.png"}},
{
          "id":"01b082a4a3644a318ab744cf56e2ed8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":435},
            "size":{
              "width":35,
              "height":89},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3534d1a46f75412b8fc539645387ccb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":435},
                "size":{
                  "width":35,
                  "height":89},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业管家-标签展示页--详情页/u140.png"}},
{
          "id":"ec36c85f87394318ac9cbdde41126a73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":683,
              "y":125},
            "size":{
              "width":262,
              "height":192},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ee466010ff4302afdde5f94c89feef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":683,
                  "y":125},
                "size":{
                  "width":262,
                  "height":192},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"411a6cdd14504624aaf52ad396b4082c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":796,
              "y":128},
            "size":{
              "width":200,
              "height":36},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0692a59a1944ac7aa8b939b5f9589cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":796,
                  "y":128},
                "size":{
                  "width":200,
                  "height":36},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48a50a4c1a0446aca3761231b31473c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":796,
              "y":178},
            "size":{
              "width":200,
              "height":36},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1485c6e2e5b74c5781b5104d69d809a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":796,
                  "y":178},
                "size":{
                  "width":200,
                  "height":36},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7a0a6cab2344f34ba5a08d84e5493c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":760,
              "y":225},
            "size":{
              "width":200,
              "height":36},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda16f2037784548922905783b080c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":760,
                  "y":225},
                "size":{
                  "width":200,
                  "height":36},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21c61b628aae4e4198db74cb536fc88d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":760,
              "y":275},
            "size":{
              "width":200,
              "height":36},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95452176e74944ac95e24a1163105b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":760,
                  "y":275},
                "size":{
                  "width":200,
                  "height":36},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e52a4a9c039d46bfa472b38a438ad407",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009595},
            "location":{
              "x":683,
              "y":342},
            "size":{
              "width":268,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3d5611a7e545f183f54fe87a2928cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009595},
                "location":{
                  "x":683,
                  "y":342},
                "size":{
                  "width":268,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的信息化门户/u77.png"}},
{
          "id":"b671dfc2a5364f8380fcda3c8fb2138f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c79ca32cc764f4b9feeaf7a69ab6864",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"59c8f506a8c94ecca0520ff052cd7731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cabe9d24df6d4c09bf2c4edf1568207e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"6ca94fb2dfc344fcbf80f0cd0d42dd14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3be835cbb66449e8e7ffb14639c2c30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"cb522798dda94845b687500e157329f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":930,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69dcad491e0644c7a4d2a6d60d322951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":930,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"4649975a514d47628487361715ebb5fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf390790e7447459241d84e51626598",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"ed1b48ae0d824e4e915d4c13d6213c31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bae86d6b3824eabb706e3522ca8eb99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"d2b6050a36d74076b2c1b16376bcc147",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":1000,
              "y":349},
            "size":{
              "width":297,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b53f27ed5cc4c33b9eb064bc8797b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":1000,
                  "y":349},
                "size":{
                  "width":297,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a5a22f7c8c0484e9ec9f9624ed96ffd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":1281,
              "y":51},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"647317ef7fe3418285316d0fbb132fcc"},
{
          "id":"79d41442a9f14762af8bff6c6f88f0bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1354,
              "y":63},
            "size":{
              "width":175,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4516a7a5ea5946a0b7fbd0849ebf3dfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1354,
                  "y":63},
                "size":{
                  "width":175,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec1284087f2f4598a7f9ca75f940e8b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"24px",
            "location":{
              "x":1304,
              "y":125},
            "size":{
              "width":277,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee11f1062875439a8fbe95288062fc93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"24px",
                "location":{
                  "x":1304,
                  "y":125},
                "size":{
                  "width":277,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc1d6e7d9c9548e39f8621852b51708c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":1551,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ed8f4ed44f4afd99aca556c66e3c2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":1551,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u219.png"}},
{
          "id":"dea9e939b145426e930944251000ff80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1551,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fe79b3c7d34375b1ec776b0b2f7337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1551,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"82dd6aa396354901bff0ddf763d5554f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1551,
              "y":484},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6c95c63e2340fe8682d73b59bacf2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1551,
                  "y":484},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机客户端-首页/u16.png"}},
{
          "id":"cb7cc84cc5ad42d3b95c33799cfa62da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":1281,
              "y":17},
            "size":{
              "width":320,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339962a2849146cd908e08ba460914ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":1281,
                  "y":17},
                "size":{
                  "width":320,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e102d2edc41943c28bd8105d85748a7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"24px",
            "location":{
              "x":1304,
              "y":193},
            "size":{
              "width":277,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0559919263874330a2cbb7ec4c55d6b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"24px",
                "location":{
                  "x":1304,
                  "y":193},
                "size":{
                  "width":277,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd23634bf96e4860955f38f2882f9bd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"24px",
            "location":{
              "x":1304,
              "y":261},
            "size":{
              "width":277,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f517a648a7cb4e79b250ebee3e1cbb29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"24px",
                "location":{
                  "x":1304,
                  "y":261},
                "size":{
                  "width":277,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8b2ae85bfe141d4bc5480c3a0e30ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":553},
            "size":{
              "width":300,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0520d46910b2409e851e15191540f10c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":553},
                "size":{
                  "width":300,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u50.png"}},
{
          "id":"0113f4e8c3374952b36609f6fa2b326e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":234,
              "y":562},
            "size":{
              "width":106,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4921ecf239dc47b58247dd3bf26f4c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":562},
                "size":{
                  "width":106,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"802a0243bb024982b4c8017c6ef3fc78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":557},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1042dfcca9c844bf8f16f1b28d501769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":557},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融/u56.png"}},
{
          "id":"a2425d002e6b45ca843a1398c2068f72",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":479},
            "size":{
              "width":473,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/发起预约音频通话/u61_end.png",
            "line~":"images/我的信息化门户/u124_line.png"}},
{
          "id":"cf021e85d2544ef9a35caa4cfa9f68fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":130,
              "y":459},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a79c6d9f59f4cac8dc2afc09bc8123a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":459},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c451a0b6b9f5444087186fad556e7558",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":21},
            "size":{
              "width":763,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/发起预约音频通话/u61_end.png",
            "line~":"images/我的信息化门户/u127_line.png"}},
{
          "id":"eaa865695aba46e3b8e1b6789ec4afae",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":26},
            "size":{
              "width":10,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF3399FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的信息化门户/u128_line.png"}}]}},
  "masters":{
    "647317ef7fe3418285316d0fbb132fcc":{
      "packageId":"647317ef7fe3418285316d0fbb132fcc",
      "type":"Axure:Master",
      "name":"导航2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f257cdb006b6494da1906d7ff4690208",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x4FF2F2F2},
              "location":{
                "x":16,
                "y":0},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c11e5dec201344d090e79192ddb67697",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x4FF2F2F2},
                  "location":{
                    "x":16,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u0.png",
              "normal~":"images/手机客户端-首页/u0.png"}},
{
            "id":"946845709c6d4700a25b9794f94b7b2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF009191},
{
                    "color":0xFF009191},
{
                    "color":0xFF009999},
{
                    "color":0xFF009999}]},
              "location":{
                "x":16,
                "y":1},
              "size":{
                "width":320,
                "height":47},
              "rotation":"180",
              "textRotation":"180",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45fa20d9bede4b10a2179db582a617dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF009191},
{
                        "color":0xFF009191},
{
                        "color":0xFF009999},
{
                        "color":0xFF009999}]},
                  "location":{
                    "x":16,
                    "y":1},
                  "size":{
                    "width":320,
                    "height":47},
                  "rotation":"180",
                  "textRotation":"180",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机客户端-首页/u46.png",
              "normal~":"images/手机客户端-首页/u46.png"}},
{
            "id":"b20f990e94114d8c8d860279c0456c7a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48ce4574fb184beaa50109c5926bacb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png",
              "normal~":"images/方案3/u136.png"}},
{
            "id":"380f78e23c1248aebe9bc85e8f9adc48",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":8},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96c4b7a37ab47cebbd28c7e3f47da14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":19,
                    "y":8},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/方案3/u136.png",
              "normal~":"images/方案3/u136.png"}}]}}},
  "objectPaths":{
    "46b03fd3207547d389883bb8885c0d2a":{
      "scriptId":"u0"},
    "8c999b84f70b44f9b950ae8aeeb461e9":{
      "scriptId":"u1"},
    "d12bc3df438540528ad5b52680f84b73":{
      "scriptId":"u2"},
    "9533b0498ccc43c3972e194079cbd6d4":{
      "scriptId":"u3"},
    "bafc0ca331104cfba5ad253c014c79f6":{
      "scriptId":"u4"},
    "7587e45a799e4c4bb9fe4a0f1cefcdf7":{
      "scriptId":"u5"},
    "10b5e0c08d6f4b64a83f6e44b7831cab":{
      "scriptId":"u6"},
    "8afd24588ce8416b869fde1e43ee6c6c":{
      "scriptId":"u7"},
    "7050b367c7294869a6f1d66f86c7e18b":{
      "scriptId":"u8"},
    "cf8cae802a66455d8db4d132e30f774b":{
      "scriptId":"u9"},
    "1ef446ac544d4e028d8f0309de7ac35e":{
      "scriptId":"u10"},
    "a3ddb9fe87e9413b8e878a6ad25776f4":{
      "scriptId":"u11"},
    "5fc9fe39d7bc4c99a1aeb721a976c73b":{
      "scriptId":"u12"},
    "9e8852c131414e3b9433ad33d108c54a":{
      "scriptId":"u13"},
    "0df0a255fd1a436287b35a1adc9aeb78":{
      "scriptId":"u14"},
    "e669d405db654fe89c02520fc624b77b":{
      "scriptId":"u15"},
    "fdc2b3a4c4fa4b16b92ae0e9fd2e2584":{
      "scriptId":"u16"},
    "f872aa65ee4c44fab3a66c5db00f094c":{
      "scriptId":"u17"},
    "232c37c0aef24f0f957b24b2939ee99d":{
      "scriptId":"u18"},
    "68428bd1c3a04624978c25577f3cbb82":{
      "scriptId":"u19"},
    "18ce6fab697e49f093b0e67a4b933381":{
      "scriptId":"u20"},
    "68ae67eb8321452ea5fdffdc124368b2":{
      "scriptId":"u21"},
    "e6be580621044d918d2436b17d2973c6":{
      "scriptId":"u22"},
    "cf61f76c6ccb4ccaab19fb708d8b0e9a":{
      "scriptId":"u23"},
    "be8061ce55ab4a0c89ba2482e5ddefac":{
      "scriptId":"u24"},
    "b732c6a4049244b6924ef8f581bdbfe2":{
      "scriptId":"u25"},
    "3f0dc90835c044fd9ab226fb4a563ada":{
      "scriptId":"u26"},
    "7327dff6014d41b988887644702dd0b3":{
      "scriptId":"u27"},
    "a08d4e92b8764f10a5d8dc5e099c5ec7":{
      "scriptId":"u28"},
    "dcd1dff19a6941a38cd7870b35afb1a0":{
      "scriptId":"u29"},
    "4951238b25a4439fa1fc2757ce9c746f":{
      "scriptId":"u30"},
    "bbb24a557f0a45b18b29ee44318af852":{
      "scriptId":"u31"},
    "24ee7cbbb0d74d818cdc763aed0f70f6":{
      "scriptId":"u32"},
    "26982d0e6a9f4fd8b432a1896748e025":{
      "scriptId":"u33"},
    "99fac2dfe6ee439e93d48f9a8f3e3f7f":{
      "scriptId":"u34"},
    "c4cb0d6a66c147a1928365b2c7ccf301":{
      "scriptId":"u35"},
    "f4526c003ee04ab0bff32d44d2a3f53f":{
      "scriptId":"u36"},
    "2c524b1bfadf4a6f864683adc7a3eab0":{
      "scriptId":"u37"},
    "5710f741343d435cbd3d5bfffc67a4cc":{
      "scriptId":"u38"},
    "61dc38f0faf142e89c8e205ca1a0585b":{
      "scriptId":"u39"},
    "af95965e268248c3957f5b8e4604cc38":{
      "scriptId":"u40"},
    "931fc732edd643a699fae0d6647e58d8":{
      "scriptId":"u41"},
    "fd1eda541d5049709af91cf810d5d3c0":{
      "scriptId":"u42"},
    "4b99a6f94cbb47efa9942a0dd0c984fc":{
      "scriptId":"u43"},
    "c2722cef0d844b67951810bf5d18412b":{
      "scriptId":"u44",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u45"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u46"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u47"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u48"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u49"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u50"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u51"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u52"}},
    "3039d2abe31742d7b373be653788a5ef":{
      "scriptId":"u53"},
    "10a15c8a2848444cbc21a29fe7554641":{
      "scriptId":"u54"},
    "c29ed8ada6e149be84f5d188dd5c641a":{
      "scriptId":"u55"},
    "2da0476e39594662bae166c997f52ab4":{
      "scriptId":"u56"},
    "0225237330ad4014a15708601e8e2b20":{
      "scriptId":"u57"},
    "da8e3ddff872489eb7bb497af1ada61c":{
      "scriptId":"u58"},
    "5c9716810fe7448cb384b2b9de288d3b":{
      "scriptId":"u59"},
    "cb0c39ad377e4727a98ff2ac2f3face5":{
      "scriptId":"u60"},
    "d559da695878421888218e56e71703d4":{
      "scriptId":"u61"},
    "60438721be9249439e3ddcf8dd3abe68":{
      "scriptId":"u62"},
    "e29ae9f6a4754405b7052cb1fbd2f8e2":{
      "scriptId":"u63"},
    "50cb0f2af93a4af09b1f22f2fc8d6cc5":{
      "scriptId":"u64"},
    "01b082a4a3644a318ab744cf56e2ed8d":{
      "scriptId":"u65"},
    "3534d1a46f75412b8fc539645387ccb8":{
      "scriptId":"u66"},
    "ec36c85f87394318ac9cbdde41126a73":{
      "scriptId":"u67"},
    "b1ee466010ff4302afdde5f94c89feef":{
      "scriptId":"u68"},
    "411a6cdd14504624aaf52ad396b4082c":{
      "scriptId":"u69"},
    "e0692a59a1944ac7aa8b939b5f9589cd":{
      "scriptId":"u70"},
    "48a50a4c1a0446aca3761231b31473c7":{
      "scriptId":"u71"},
    "1485c6e2e5b74c5781b5104d69d809a1":{
      "scriptId":"u72"},
    "f7a0a6cab2344f34ba5a08d84e5493c3":{
      "scriptId":"u73"},
    "bda16f2037784548922905783b080c6c":{
      "scriptId":"u74"},
    "21c61b628aae4e4198db74cb536fc88d":{
      "scriptId":"u75"},
    "95452176e74944ac95e24a1163105b4e":{
      "scriptId":"u76"},
    "e52a4a9c039d46bfa472b38a438ad407":{
      "scriptId":"u77"},
    "9b3d5611a7e545f183f54fe87a2928cc":{
      "scriptId":"u78"},
    "b671dfc2a5364f8380fcda3c8fb2138f":{
      "scriptId":"u79"},
    "5c79ca32cc764f4b9feeaf7a69ab6864":{
      "scriptId":"u80"},
    "59c8f506a8c94ecca0520ff052cd7731":{
      "scriptId":"u81"},
    "cabe9d24df6d4c09bf2c4edf1568207e":{
      "scriptId":"u82"},
    "6ca94fb2dfc344fcbf80f0cd0d42dd14":{
      "scriptId":"u83"},
    "b3be835cbb66449e8e7ffb14639c2c30":{
      "scriptId":"u84"},
    "cb522798dda94845b687500e157329f7":{
      "scriptId":"u85"},
    "69dcad491e0644c7a4d2a6d60d322951":{
      "scriptId":"u86"},
    "4649975a514d47628487361715ebb5fa":{
      "scriptId":"u87"},
    "6cf390790e7447459241d84e51626598":{
      "scriptId":"u88"},
    "ed1b48ae0d824e4e915d4c13d6213c31":{
      "scriptId":"u89"},
    "2bae86d6b3824eabb706e3522ca8eb99":{
      "scriptId":"u90"},
    "d2b6050a36d74076b2c1b16376bcc147":{
      "scriptId":"u91"},
    "3b53f27ed5cc4c33b9eb064bc8797b9a":{
      "scriptId":"u92"},
    "5a5a22f7c8c0484e9ec9f9624ed96ffd":{
      "scriptId":"u93",
      "f257cdb006b6494da1906d7ff4690208":{
        "scriptId":"u94"},
      "c11e5dec201344d090e79192ddb67697":{
        "scriptId":"u95"},
      "946845709c6d4700a25b9794f94b7b2a":{
        "scriptId":"u96"},
      "45fa20d9bede4b10a2179db582a617dc":{
        "scriptId":"u97"},
      "b20f990e94114d8c8d860279c0456c7a":{
        "scriptId":"u98"},
      "48ce4574fb184beaa50109c5926bacb1":{
        "scriptId":"u99"},
      "380f78e23c1248aebe9bc85e8f9adc48":{
        "scriptId":"u100"},
      "b96c4b7a37ab47cebbd28c7e3f47da14":{
        "scriptId":"u101"}},
    "79d41442a9f14762af8bff6c6f88f0bb":{
      "scriptId":"u102"},
    "4516a7a5ea5946a0b7fbd0849ebf3dfa":{
      "scriptId":"u103"},
    "ec1284087f2f4598a7f9ca75f940e8b2":{
      "scriptId":"u104"},
    "ee11f1062875439a8fbe95288062fc93":{
      "scriptId":"u105"},
    "cc1d6e7d9c9548e39f8621852b51708c":{
      "scriptId":"u106"},
    "83ed8f4ed44f4afd99aca556c66e3c2c":{
      "scriptId":"u107"},
    "dea9e939b145426e930944251000ff80":{
      "scriptId":"u108"},
    "57fe79b3c7d34375b1ec776b0b2f7337":{
      "scriptId":"u109"},
    "82dd6aa396354901bff0ddf763d5554f":{
      "scriptId":"u110"},
    "5b6c95c63e2340fe8682d73b59bacf2c":{
      "scriptId":"u111"},
    "cb7cc84cc5ad42d3b95c33799cfa62da":{
      "scriptId":"u112"},
    "339962a2849146cd908e08ba460914ce":{
      "scriptId":"u113"},
    "e102d2edc41943c28bd8105d85748a7e":{
      "scriptId":"u114"},
    "0559919263874330a2cbb7ec4c55d6b8":{
      "scriptId":"u115"},
    "cd23634bf96e4860955f38f2882f9bd3":{
      "scriptId":"u116"},
    "f517a648a7cb4e79b250ebee3e1cbb29":{
      "scriptId":"u117"},
    "b8b2ae85bfe141d4bc5480c3a0e30ab1":{
      "scriptId":"u118"},
    "0520d46910b2409e851e15191540f10c":{
      "scriptId":"u119"},
    "0113f4e8c3374952b36609f6fa2b326e":{
      "scriptId":"u120"},
    "4921ecf239dc47b58247dd3bf26f4c5b":{
      "scriptId":"u121"},
    "802a0243bb024982b4c8017c6ef3fc78":{
      "scriptId":"u122"},
    "1042dfcca9c844bf8f16f1b28d501769":{
      "scriptId":"u123"},
    "a2425d002e6b45ca843a1398c2068f72":{
      "scriptId":"u124"},
    "cf021e85d2544ef9a35caa4cfa9f68fa":{
      "scriptId":"u125"},
    "9a79c6d9f59f4cac8dc2afc09bc8123a":{
      "scriptId":"u126"},
    "c451a0b6b9f5444087186fad556e7558":{
      "scriptId":"u127"},
    "eaa865695aba46e3b8e1b6789ec4afae":{
      "scriptId":"u128"}}});