$axure.loadCurrentPage({
  "url":"搜索.html",
  "generationDate":new Date(1405078989692.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8b7086cb0754498fb038cc993d164a34",
    "type":"Axure:Page",
    "name":"搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cfab0fd5a2e64fa19f8ad2aec6d72478",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":39,
              "y":53},
            "size":{
              "width":67,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"583ae7c7a22541fdbb5bb7dd43735ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":39,
                  "y":53},
                "size":{
                  "width":67,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65bbc77021d34c2aaf008fd198890975",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":16},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7487c2c1f6f44589b399ea859c8ea4b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":16},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1a1cebda8445d48be82a33424835b6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":109}},
          "adaptiveStyles":{
},
          "masterId":"8e74194050be4c5f975f3549fb9f251e"},
{
          "id":"3734f2c11a144c9fb96f2224c7018995",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":58,
              "y":159},
            "size":{
              "width":512,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a71dbbdd7d44b780d534211c359bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":58,
                  "y":159},
                "size":{
                  "width":512,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1724e0b1c7d54d5aa3253d0593175e18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":60},
            "size":{
              "width":620,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c288c3dec20641e289e5012120185aca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":60},
                "size":{
                  "width":620,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u11.png"}},
{
          "id":"41881ef9f427487d8480b9a36fcf6ffa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":746,
              "y":71},
            "size":{
              "width":590,
              "height":138},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e764c69ebc042a2bf0d09806efd4861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":746,
                  "y":71},
                "size":{
                  "width":590,
                  "height":138},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u13.png"}},
{
          "id":"2a91e16c304e4473b92eb610f088c08a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":731,
              "y":280},
            "size":{
              "width":795,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e5df98cf1fb4583a2172a13f7c91cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":731,
                  "y":280},
                "size":{
                  "width":795,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u15.png"}},
{
          "id":"dd2fcb51d29e4fabba68a908ca49cf02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":290},
            "size":{
              "width":769,
              "height":101},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c70c793a4dbc4c7682a33ef05ad14208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":290},
                "size":{
                  "width":769,
                  "height":101},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u17.png"}},
{
          "id":"8e03d3f0cc3e4288a9006c1b462dbc70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":550},
            "size":{
              "width":460,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b31384b7014e3d983296a734a0d32b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":550},
                "size":{
                  "width":460,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u19.png"}},
{
          "id":"e6aa7d5d40d948ba9589b4dddd46c45f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":558},
            "size":{
              "width":449,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d2ea8bd93bc4c51ad2763d99f437437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":558},
                "size":{
                  "width":449,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u21.png"}},
{
          "id":"452cd7a973ea46dcbdaf773882caf730",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":630},
            "size":{
              "width":300,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4f47a166244f56932fbab07470ecbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":630},
                "size":{
                  "width":300,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u23.png"}},
{
          "id":"4541030c9a0847959f91b52040e75309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":800},
            "size":{
              "width":670,
              "height":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa35a3e20714dc3a7579953770dd7a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":800},
                "size":{
                  "width":670,
                  "height":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u25.png"}},
{
          "id":"0f70162830e14cf2a08b75b7cdacb5e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":820},
            "size":{
              "width":625,
              "height":178},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d911c3315e04dbf9623f9863d6ae579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":820},
                "size":{
                  "width":625,
                  "height":178},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u27.png"}}]}},
  "masters":{
    "8e74194050be4c5f975f3549fb9f251e":{
      "packageId":"8e74194050be4c5f975f3549fb9f251e",
      "type":"Axure:Master",
      "name":"定义",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"42964752674241b1a6df857fc323b96f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF3399FF},
              "size":{
                "width":10,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"02dc9cd588c94598abcd573136338e55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF3399FF},
                  "size":{
                    "width":10,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/check_box/u1.png"}},
{
            "id":"4a94a4881d034aa3b507f525bde6ad53",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":1},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fde41985e9314cfdaf3db7b91a13cd64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":1},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "cfab0fd5a2e64fa19f8ad2aec6d72478":{
      "scriptId":"u0"},
    "583ae7c7a22541fdbb5bb7dd43735ca2":{
      "scriptId":"u1"},
    "65bbc77021d34c2aaf008fd198890975":{
      "scriptId":"u2"},
    "7487c2c1f6f44589b399ea859c8ea4b4":{
      "scriptId":"u3"},
    "3e1a1cebda8445d48be82a33424835b6":{
      "scriptId":"u4",
      "42964752674241b1a6df857fc323b96f":{
        "scriptId":"u5"},
      "02dc9cd588c94598abcd573136338e55":{
        "scriptId":"u6"},
      "4a94a4881d034aa3b507f525bde6ad53":{
        "scriptId":"u7"},
      "fde41985e9314cfdaf3db7b91a13cd64":{
        "scriptId":"u8"}},
    "3734f2c11a144c9fb96f2224c7018995":{
      "scriptId":"u9"},
    "b5a71dbbdd7d44b780d534211c359bcf":{
      "scriptId":"u10"},
    "1724e0b1c7d54d5aa3253d0593175e18":{
      "scriptId":"u11"},
    "c288c3dec20641e289e5012120185aca":{
      "scriptId":"u12"},
    "41881ef9f427487d8480b9a36fcf6ffa":{
      "scriptId":"u13"},
    "5e764c69ebc042a2bf0d09806efd4861":{
      "scriptId":"u14"},
    "2a91e16c304e4473b92eb610f088c08a":{
      "scriptId":"u15"},
    "1e5df98cf1fb4583a2172a13f7c91cf2":{
      "scriptId":"u16"},
    "dd2fcb51d29e4fabba68a908ca49cf02":{
      "scriptId":"u17"},
    "c70c793a4dbc4c7682a33ef05ad14208":{
      "scriptId":"u18"},
    "8e03d3f0cc3e4288a9006c1b462dbc70":{
      "scriptId":"u19"},
    "22b31384b7014e3d983296a734a0d32b":{
      "scriptId":"u20"},
    "e6aa7d5d40d948ba9589b4dddd46c45f":{
      "scriptId":"u21"},
    "3d2ea8bd93bc4c51ad2763d99f437437":{
      "scriptId":"u22"},
    "452cd7a973ea46dcbdaf773882caf730":{
      "scriptId":"u23"},
    "1c4f47a166244f56932fbab07470ecbe":{
      "scriptId":"u24"},
    "4541030c9a0847959f91b52040e75309":{
      "scriptId":"u25"},
    "baa35a3e20714dc3a7579953770dd7a5":{
      "scriptId":"u26"},
    "0f70162830e14cf2a08b75b7cdacb5e3":{
      "scriptId":"u27"},
    "3d911c3315e04dbf9623f9863d6ae579":{
      "scriptId":"u28"}}});