$axure.loadCurrentPage({
  "url":"favorites.html",
  "generationDate":new Date(1406213758930.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e5c432c327b044c5a2915f3d11434b89",
    "type":"Axure:Page",
    "name":"favorites",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"543690c033164aa9972a6b19aeb1fa34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":28},
            "size":{
              "width":394,
              "height":656},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c3f696f92d4504b8f900617697476d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":28},
                "size":{
                  "width":394,
                  "height":656},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/favorites/u0.png"}},
{
          "id":"515f5a5ae96744baa81c7d8beda05bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":449,
              "y":637},
            "size":{
              "width":67,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d24d332512c44aa3859c5937f584c877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":449,
                  "y":637},
                "size":{
                  "width":67,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1a00e0675574e4ba0a0d100cd41f7a8",
          "label":"more",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":725,
              "y":596},
            "size":{
              "width":155,
              "height":38},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e2b582d0802946e7b4efc81ee7396181",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c90e430ba06141019328785c93131da7",
                  "label":"",
                  "parentDynamicPanel":"e1a00e0675574e4ba0a0d100cd41f7a8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF363636},
                    "size":{
                      "width":110,
                      "height":37},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59b0f0a28a834983b644cbb4324fa03b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1a00e0675574e4ba0a0d100cd41f7a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF363636},
                        "size":{
                          "width":110,
                          "height":37},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/favorites/u5.png"}},
{
                  "id":"7a443dece2c24131aea9f3797e9a2c25",
                  "label":"",
                  "parentDynamicPanel":"e1a00e0675574e4ba0a0d100cd41f7a8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":12,
                      "y":11},
                    "size":{
                      "width":138,
                      "height":19},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de4105b77cb94fce8cdb2e095b7219d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1a00e0675574e4ba0a0d100cd41f7a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":12,
                          "y":11},
                        "size":{
                          "width":138,
                          "height":19},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"41e81bb160094336a16a132a8d204bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":792,
              "y":637},
            "size":{
              "width":49,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"022ffb3af55c4c3081180d02def66081",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":792,
                  "y":637},
                "size":{
                  "width":49,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle more",
                      "objectsToFades":[{
                          "objectPath":["e1a00e0675574e4ba0a0d100cd41f7a8"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8269e1e6949441b3803e7fd92d7a136e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":183},
            "size":{
              "width":48,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/home/u38_end.png",
            "line~":"images/home/u38_line.png"}},
{
          "id":"3caf2a7cb15440ecb172519aa538a1e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":923,
              "y":180},
            "size":{
              "width":354,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d418278fd55847b89a97bc347413a13d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":923,
                  "y":180},
                "size":{
                  "width":354,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba216ec22041404da975278d5b821726",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF364E5A,
              "opacity":1},
            "lineSpacing":"25px",
            "location":{
              "x":140,
              "y":28},
            "size":{
              "width":240,
              "height":100},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9912bd0c4dbf43d1bb0868484a018094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF364E5A,
                  "opacity":1},
                "lineSpacing":"25px",
                "location":{
                  "x":140,
                  "y":28},
                "size":{
                  "width":240,
                  "height":100},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "543690c033164aa9972a6b19aeb1fa34":{
      "scriptId":"u0"},
    "86c3f696f92d4504b8f900617697476d":{
      "scriptId":"u1"},
    "515f5a5ae96744baa81c7d8beda05bb4":{
      "scriptId":"u2"},
    "d24d332512c44aa3859c5937f584c877":{
      "scriptId":"u3"},
    "e1a00e0675574e4ba0a0d100cd41f7a8":{
      "scriptId":"u4"},
    "c90e430ba06141019328785c93131da7":{
      "scriptId":"u5"},
    "59b0f0a28a834983b644cbb4324fa03b":{
      "scriptId":"u6"},
    "7a443dece2c24131aea9f3797e9a2c25":{
      "scriptId":"u7"},
    "de4105b77cb94fce8cdb2e095b7219d8":{
      "scriptId":"u8"},
    "41e81bb160094336a16a132a8d204bb0":{
      "scriptId":"u9"},
    "022ffb3af55c4c3081180d02def66081":{
      "scriptId":"u10"},
    "8269e1e6949441b3803e7fd92d7a136e":{
      "scriptId":"u11"},
    "3caf2a7cb15440ecb172519aa538a1e2":{
      "scriptId":"u12"},
    "d418278fd55847b89a97bc347413a13d":{
      "scriptId":"u13"},
    "ba216ec22041404da975278d5b821726":{
      "scriptId":"u14"},
    "9912bd0c4dbf43d1bb0868484a018094":{
      "scriptId":"u15"}}});